Released PSO*7*300 SEQ #272
Extracted from mail message
**KIDS**:PSO*7.0*300^

**INSTALL NAME**
PSO*7.0*300
"BLD",6338,0)
PSO*7.0*300^OUTPATIENT PHARMACY^0^3080815^y
"BLD",6338,1,0)
^9.61A^3^3^3080512^^^^
"BLD",6338,1,1,0)
The Pharmacy Prescription Practices V.1.0 package is being retired per
"BLD",6338,1,2,0)
PSI-07-114. Therefore, calls to the PPP package within Outpatient
"BLD",6338,1,3,0)
Pharmacy V.7.0 need to be removed.
"BLD",6338,4,0)
^9.64PA^^
"BLD",6338,6)
3^
"BLD",6338,6.3)
4
"BLD",6338,"KRN",0)
^9.67PA^^
"BLD",6338,"KRN",.4,0)
.4
"BLD",6338,"KRN",.4,"NM",0)
^9.68A^^0
"BLD",6338,"KRN",.401,0)
.401
"BLD",6338,"KRN",.401,"NM",0)
^9.68A^^0
"BLD",6338,"KRN",.402,0)
.402
"BLD",6338,"KRN",.402,"NM",0)
^9.68A^^0
"BLD",6338,"KRN",.403,0)
.403
"BLD",6338,"KRN",.5,0)
.5
"BLD",6338,"KRN",.84,0)
.84
"BLD",6338,"KRN",3.6,0)
3.6
"BLD",6338,"KRN",3.8,0)
3.8
"BLD",6338,"KRN",9.2,0)
9.2
"BLD",6338,"KRN",9.8,0)
9.8
"BLD",6338,"KRN",9.8,"NM",0)
^9.68A^9^9
"BLD",6338,"KRN",9.8,"NM",1,0)
PSOBBC^^0^B91067293
"BLD",6338,"KRN",9.8,"NM",2,0)
PSOORFI3^^0^B74326144
"BLD",6338,"KRN",9.8,"NM",3,0)
PSOPRF^^0^B35238813
"BLD",6338,"KRN",9.8,"NM",4,0)
PSOPRI^^0^B23541806
"BLD",6338,"KRN",9.8,"NM",5,0)
PSORX1^^0^B59364372
"BLD",6338,"KRN",9.8,"NM",6,0)
PSOSD^^0^B31217592
"BLD",6338,"KRN",9.8,"NM",7,0)
PSOTPRX1^^0^B51097782
"BLD",6338,"KRN",9.8,"NM",8,0)
PSOPRFSS^^0^B16329111
"BLD",6338,"KRN",9.8,"NM",9,0)
PSOORFI4^^0^B67401126
"BLD",6338,"KRN",9.8,"NM","B","PSOBBC",1)

"BLD",6338,"KRN",9.8,"NM","B","PSOORFI3",2)

"BLD",6338,"KRN",9.8,"NM","B","PSOORFI4",9)

"BLD",6338,"KRN",9.8,"NM","B","PSOPRF",3)

"BLD",6338,"KRN",9.8,"NM","B","PSOPRFSS",8)

"BLD",6338,"KRN",9.8,"NM","B","PSOPRI",4)

"BLD",6338,"KRN",9.8,"NM","B","PSORX1",5)

"BLD",6338,"KRN",9.8,"NM","B","PSOSD",6)

"BLD",6338,"KRN",9.8,"NM","B","PSOTPRX1",7)

"BLD",6338,"KRN",19,0)
19
"BLD",6338,"KRN",19.1,0)
19.1
"BLD",6338,"KRN",101,0)
101
"BLD",6338,"KRN",409.61,0)
409.61
"BLD",6338,"KRN",771,0)
771
"BLD",6338,"KRN",869.2,0)
869.2
"BLD",6338,"KRN",870,0)
870
"BLD",6338,"KRN",8994,0)
8994
"BLD",6338,"KRN","B",.4,.4)

"BLD",6338,"KRN","B",.401,.401)

"BLD",6338,"KRN","B",.402,.402)

"BLD",6338,"KRN","B",.403,.403)

"BLD",6338,"KRN","B",.5,.5)

"BLD",6338,"KRN","B",.84,.84)

"BLD",6338,"KRN","B",3.6,3.6)

"BLD",6338,"KRN","B",3.8,3.8)

"BLD",6338,"KRN","B",9.2,9.2)

"BLD",6338,"KRN","B",9.8,9.8)

"BLD",6338,"KRN","B",19,19)

"BLD",6338,"KRN","B",19.1,19.1)

"BLD",6338,"KRN","B",101,101)

"BLD",6338,"KRN","B",409.61,409.61)

"BLD",6338,"KRN","B",771,771)

"BLD",6338,"KRN","B",869.2,869.2)

"BLD",6338,"KRN","B",870,870)

"BLD",6338,"KRN","B",8994,8994)

"BLD",6338,"QUES",0)
^9.62^^
"BLD",6338,"REQB",0)
^9.611^1^1
"BLD",6338,"REQB",1,0)
PSO*7.0*225^2
"BLD",6338,"REQB","B","PSO*7.0*225",1)

"BLD",6338,"REQG",0)
^9.611^^
"MBREQ")
0
"PKG",141,-1)
1^1
"PKG",141,0)
OUTPATIENT PHARMACY^PSO^OUTPATIENT LABELS, PROFILE, INVENTORY, PRESCRIPTIONS
"PKG",141,20,0)
^9.402P^^
"PKG",141,22,0)
^9.49I^1^1
"PKG",141,22,1,0)
7.0^2971216^2980917^11712
"PKG",141,22,1,"PAH",1,0)
300^3080815^11863
"PKG",141,22,1,"PAH",1,1,0)
^^3^3^3080815
"PKG",141,22,1,"PAH",1,1,1,0)
The Pharmacy Prescription Practices V.1.0 package is being retired per
"PKG",141,22,1,"PAH",1,1,2,0)
PSI-07-114. Therefore, calls to the PPP package within Outpatient
"PKG",141,22,1,"PAH",1,1,3,0)
Pharmacy V.7.0 need to be removed.
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPI1",0)
YO
"QUES","XPI1","??")
^D INHIBIT^XPDH
"QUES","XPI1","A")
Want KIDS to INHIBIT LOGONs during the install
"QUES","XPI1","B")
NO
"QUES","XPI1","M")
D XPI1^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPO1",0)
Y
"QUES","XPO1","??")
^D MENU^XPDH
"QUES","XPO1","A")
Want KIDS to Rebuild Menu Trees Upon Completion of Install
"QUES","XPO1","B")
NO
"QUES","XPO1","M")
D XPO1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
NO
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
9
"RTN","PSOBBC")
0^1^B91067293^B92251311
"RTN","PSOBBC",1,0)
PSOBBC ;IHS/DSD/JCM-BATCH BARCODE DRIVER ;3/30/06 10:10am
"RTN","PSOBBC",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**11,22,27,34,46,130,146,185,242,264,300**;DEC 1997;Build 4
"RTN","PSOBBC",3,0)
 ;External reference to ^IBE(350.1,"ANEW" supported by DBIA 592
"RTN","PSOBBC",4,0)
 ;External references CHPUS^IBACUS and TRI^IBACUS supported by DBIA 2030
"RTN","PSOBBC",5,0)
 ;External references LK^ORX2 and ULK^ORX2 supported by DBIA 867
"RTN","PSOBBC",6,0)
 ;External references ^PS(55 supported by DBIA 2228
"RTN","PSOBBC",7,0)
 ;External references U, UL, PSOL, and PSOUL^PSSLOCK supported by DBIA 2789
"RTN","PSOBBC",8,0)
 ;PSO*242 change default to from Q to S
"RTN","PSOBBC",9,0)
 ;-------------------------------------------------------------------
"RTN","PSOBBC",10,0)
START ;
"RTN","PSOBBC",11,0)
 N PSODFN,PSOBBCNO
"RTN","PSOBBC",12,0)
 D INIT I '$D(PSOPAR) D ^PSOLSET G:'$D(PSOPAR) EOJ
"RTN","PSOBBC",13,0)
 I $G(PSOSITE) S PSOBARID=$G(^PS(59,PSOSITE,"IB")) I '$D(^IBE(350.1,"ANEW",+PSOBARID,1,1)) D  S PSORX("QFLG")=1 K PSOBARID G END
"RTN","PSOBBC",14,0)
 .W $C(7),!!,"WARNING: Pharmacy Copay not working,",!,?10,"Check IB SERVICE/SECTION in Pharmacy Site File.",!!!,"You will not be able to enter any new prescriptions until this is corrected!"
"RTN","PSOBBC",15,0)
 S PSOBBC("QFLG")=0,PSORX("BAR CODE")=1
"RTN","PSOBBC",16,0)
 D FROM I PSOBBC("QFLG") S PSORX("QFLG")=1 G END
"RTN","PSOBBC",17,0)
 D ASK I PSOBBC("QFLG") S PSORX("QFLG")=1 G END
"RTN","PSOBBC",18,0)
 D PROCESS
"RTN","PSOBBC",19,0)
END D EOJ
"RTN","PSOBBC",20,0)
 Q
"RTN","PSOBBC",21,0)
 ;--------------------------------------------------------------------
"RTN","PSOBBC",22,0)
INIT ;
"RTN","PSOBBC",23,0)
 S PSOBBC("QFLG")=0,PSORX("BAR CODE")=1 K PPL
"RTN","PSOBBC",24,0)
 I '$G(PSOINST) D
"RTN","PSOBBC",25,0)
 .K DIC,DR,DIQ S DA=$P($$SITE^VASITE(),"^") I DA D
"RTN","PSOBBC",26,0)
 ..K PSOINST S DIC=4,DIQ(0)="I",DR=99,DIQ="PSOINST" D EN^DIQ1
"RTN","PSOBBC",27,0)
 ..S PSOINST=PSOINST(4,DA,99,"I") K DIC,DA,DIQ,PSOINST(4)
"RTN","PSOBBC",28,0)
 Q
"RTN","PSOBBC",29,0)
FROM ;
"RTN","PSOBBC",30,0)
 S DIR(0)="S^1:REFILLS;2:RENEWS;"
"RTN","PSOBBC",31,0)
 S DIR("A")="Batch Barcode for",DIR("B")="REFILLS"
"RTN","PSOBBC",32,0)
 D DIR G:'Y FROMX
"RTN","PSOBBC",33,0)
 S PSOBBC1("FROM")=$S(Y=1:"REFILL",1:"NEW")
"RTN","PSOBBC",34,0)
FROMX K X,Y,DIR
"RTN","PSOBBC",35,0)
 Q
"RTN","PSOBBC",36,0)
 ;
"RTN","PSOBBC",37,0)
ASK ;
"RTN","PSOBBC",38,0)
 K BINGCRT,BINGRTE,BBRX
"RTN","PSOBBC",39,0)
 W !,"Please answer the following for this session of prescriptions",!
"RTN","PSOBBC",40,0)
 D EN^PSOREF2(.PSOBBC) I PSOBBC("DFLG") S PSOBBC("QFLG")=1 G ASKX
"RTN","PSOBBC",41,0)
 D SUSP
"RTN","PSOBBC",42,0)
 D INPT,CNH
"RTN","PSOBBC",43,0)
 D:'$P($G(PSOPAR),"^",6) EARLY
"RTN","PSOBBC",44,0)
 D SET
"RTN","PSOBBC",45,0)
 D:PSOBBC1("FROM")="NEW" NOORE^PSONEW(.PSOBBC) S:$G(PSOBBC("NOO"))'="" PSOBBCNO=$G(PSOBBC("NOO")) S:$G(PSOBBC("DFLG")) PSOBBC("QFLG")=1
"RTN","PSOBBC",46,0)
ASKX Q
"RTN","PSOBBC",47,0)
 ;
"RTN","PSOBBC",48,0)
SUSP ;
"RTN","PSOBBC",49,0)
 S DIR(0)="SAB^Q:QUEUED;S:SUSPENDED"
"RTN","PSOBBC",50,0)
 S DIR("A")="Will these refills be Queued or Suspended ? "
"RTN","PSOBBC",51,0)
 S DIR("B")="S"   ;PSO*242
"RTN","PSOBBC",52,0)
 D DIR G:PSOBBC("QFLG") SUSPX
"RTN","PSOBBC",53,0)
 S (PSOBBC1("QS"),PSOBBC("QS"))=Y S:PSOBBC1("QS")="S" BINGCRT=0
"RTN","PSOBBC",54,0)
SUSPX K X,Y,DIR
"RTN","PSOBBC",55,0)
 Q
"RTN","PSOBBC",56,0)
 ;
"RTN","PSOBBC",57,0)
INPT ;
"RTN","PSOBBC",58,0)
 S DIR(0)="YA"
"RTN","PSOBBC",59,0)
 S DIR("A")="Allow refills for inpatient ? "
"RTN","PSOBBC",60,0)
 S DIR("B")="N"
"RTN","PSOBBC",61,0)
 D DIR G:PSOBBC("QFLG") INPTX
"RTN","PSOBBC",62,0)
 S (PSOBBC1("INOK"),PSOBBC("INOK"))=Y
"RTN","PSOBBC",63,0)
INPTX K X,Y,DIR
"RTN","PSOBBC",64,0)
 Q
"RTN","PSOBBC",65,0)
CNH ;
"RTN","PSOBBC",66,0)
 S DIR(0)="YA"
"RTN","PSOBBC",67,0)
 S DIR("A")="Allow refills for CNH ? "
"RTN","PSOBBC",68,0)
 S DIR("B")="N"
"RTN","PSOBBC",69,0)
 D DIR G:PSOBBC("QFLG") CNHX
"RTN","PSOBBC",70,0)
 S (PSOBBC1("CNHOK"),PSOBBC("CNHOK"))=Y
"RTN","PSOBBC",71,0)
CNHX K X,Y,DIR
"RTN","PSOBBC",72,0)
 Q
"RTN","PSOBBC",73,0)
 ;
"RTN","PSOBBC",74,0)
EARLY ;
"RTN","PSOBBC",75,0)
 S DIR(0)="YA"
"RTN","PSOBBC",76,0)
 S DIR("A")="Allow early refills ? "
"RTN","PSOBBC",77,0)
 S DIR("B")="N"
"RTN","PSOBBC",78,0)
 D DIR G:PSOBBC("QFLG") EARLYX
"RTN","PSOBBC",79,0)
 S (PSOBBC1("EAOK"),PSOBBC("EAOK"))=Y
"RTN","PSOBBC",80,0)
EARLYX K X,Y,DIR
"RTN","PSOBBC",81,0)
 Q
"RTN","PSOBBC",82,0)
 ;
"RTN","PSOBBC",83,0)
SET ;
"RTN","PSOBBC",84,0)
 S PSOBBC1("MAIL/WINDOW")=PSOBBC("MAIL/WINDOW") S:PSOBBC1("MAIL/WINDOW")="W" BINGRTE="W"
"RTN","PSOBBC",85,0)
 S PSOBBC1("FILL DATE")=PSOBBC("FILL DATE")
"RTN","PSOBBC",86,0)
 S:$G(PSOBBC("CLERK CODE")) PSOBBC1("CLERK CODE")=PSOBBC("CLERK CODE")
"RTN","PSOBBC",87,0)
 S:$G(PSOBBC("EXPIRATION DATE")) PSOBBC1("EXPIRATION DATE")=PSOBBC("EXPIRATION DATE")
"RTN","PSOBBC",88,0)
 Q
"RTN","PSOBBC",89,0)
DIR ;
"RTN","PSOBBC",90,0)
 D ^DIR
"RTN","PSOBBC",91,0)
 S:$D(DIRUT) PSOBBC("QFLG")=1,PSORX("QFLG")=1
"RTN","PSOBBC",92,0)
 K DIRUT,DUOUT,DTOUT,DIROUT
"RTN","PSOBBC",93,0)
 Q
"RTN","PSOBBC",94,0)
 ;
"RTN","PSOBBC",95,0)
PROCESS ;
"RTN","PSOBBC",96,0)
 S PSOBBC("DFLG")=0 D NOW^%DTC S TM=$E(%,1,12),TM1=$P(TM,".",2)
"RTN","PSOBBC",97,0)
 S RXN=$O(^TMP("PSORXN",$J,0)) I RXN D
"RTN","PSOBBC",98,0)
 .S RXN1=^TMP("PSORXN",$J,RXN) D EN^PSOHLSN1(RXN,$P(RXN1,"^"),$P(RXN1,"^",2),"",$P(RXN1,"^",3))
"RTN","PSOBBC",99,0)
 .I $P(^PSRX(RXN,"STA"),"^")=5 D EN^PSOHLSN1(RXN,"SC","ZS","")
"RTN","PSOBBC",100,0)
 K RXN,RXN1,^TMP("PSORXN",$J) D CLEAN^PSOVER1 K ^TMP("PSORXDC",$J)
"RTN","PSOBBC",101,0)
 D GETRXM D:PSOBBC("QFLG") ULK,ULP,ULRX G:PSOBBC("QFLG") PROCESSX
"RTN","PSOBBC",102,0)
 I $G(PSODFN)'=$P(^PSRX(PSOBBC("IRXN"),0),"^",2) D  G:PSOBBC("DFLG") PROCESS
"RTN","PSOBBC",103,0)
 .I $G(PSODFN) D ULK,ULP
"RTN","PSOBBC",104,0)
 .D PT Q:PSOBBC("DFLG")
"RTN","PSOBBC",105,0)
 .D PROFILE^PSORX1
"RTN","PSOBBC",106,0)
 E  D PTC G:PSOBBC("DFLG") PROCESS
"RTN","PSOBBC",107,0)
 D:'$G(PSOSD) ^PSOBUILD
"RTN","PSOBBC",108,0)
 S PSOBBC("DONE")=PSOBBC("IRXN")_","
"RTN","PSOBBC",109,0)
 D @PSOBBC1("FROM") S:$G(PPL)&$D(BINGRTE) BBRX(1)=$S($D(PSOBBC("DONE")):PSOBBC("DONE"),1:BBRX) D:$D(BINGCRT)&($D(BINGRTE)&($D(DISGROUP))) ^PSOBING1 K BBRX D ULRX G PROCESS
"RTN","PSOBBC",110,0)
PROCESSX I $G(PPL) D SETX,TRI,Q^PSORXL K PPL,RXFL
"RTN","PSOBBC",111,0)
 Q
"RTN","PSOBBC",112,0)
GETRXM ;
"RTN","PSOBBC",113,0)
 K DIR,PSOBBC("IRXN"),PSOREFXM
"RTN","PSOBBC",114,0)
 S DIR(0)="FO^5:245^K:X'?3N1""-""1.N X"
"RTN","PSOBBC",115,0)
 S DIR("A")="WAND BARCODE"
"RTN","PSOBBC",116,0)
 S DIR("?",1)="Wand the barcoded number of the prescription to be processed."
"RTN","PSOBBC",117,0)
 S DIR("?",2)="The number should be of the form NNN-NNNNNN"
"RTN","PSOBBC",118,0)
 S DIR("?",3)="where the number before the dash is your station number."
"RTN","PSOBBC",119,0)
 S DIR("?")="Enter ""^"", or a RETURN to quit."
"RTN","PSOBBC",120,0)
 D DIR G:PSOBBC("QFLG") GETRXMX
"RTN","PSOBBC",121,0)
 I $P(X,"-")'=PSOINST W !?7,$C(7),$C(7),$C(7),"Not From this Institution" G GETRXM
"RTN","PSOBBC",122,0)
 S (PSOBBC("IRXN"),PSOBBC("OIRXN"),BBRX)=$P(X,"-",2)
"RTN","PSOBBC",123,0)
 I $G(^PSRX(PSOBBC("IRXN"),0))']"" W !,$C(7),"Rx data is not on file !",! G GETRXM
"RTN","PSOBBC",124,0)
 S PSOXDFN=+$P($G(^PSRX(PSOBBC("IRXN"),0)),"^",2) I PSOXDFN S PSOLOUD=1 D:$P($G(^PS(55,PSOXDFN,0)),"^",6)'=2 EN^PSOHLUP(PSOXDFN) K PSOLOUD
"RTN","PSOBBC",125,0)
 K PSOXDFN I $P($G(^PSRX(PSOBBC("IRXN"),"STA")),"^")=13 W !,$C(7),"Rx has already been deleted." G GETRXM
"RTN","PSOBBC",126,0)
 I $G(PSOBBC("DONE"))[PSOBBC("IRXN")_"," W !,$C(7),"Rx has already been entered" G GETRXM
"RTN","PSOBBC",127,0)
 I $G(PSOBBC1("FROM"))="REFILL" S PSOREFXM=$G(PSOBBC("IRXN")) I PSOREFXM D PSOL^PSSLOCK(PSOREFXM) I '$G(PSOMSG) D  K PSOMSG G GETRXM
"RTN","PSOBBC",128,0)
 .I $P($G(PSOMSG),"^",2)'="" W $C(7),!!?5,$P(PSOMSG,"^",2),! Q
"RTN","PSOBBC",129,0)
 .W $C(7),!!?5,"Another person is editing Rx "_$P($G(^PSRX(+$G(PSOBBC("IRXN")),0)),"^"),!
"RTN","PSOBBC",130,0)
 I '$D(PSODFNX(+$P(^PSRX(PSOBBC("IRXN"),0),"^",2))),$G(PSOBBC1("FROM"))="NEW" K PSONOERR D  G:'$G(PSOPLCK)!($G(PSONOERR)) GETRXM
"RTN","PSOBBC",131,0)
 .S PSOPLCK=$$L^PSSLOCK(+$P(^PSRX(PSOBBC("IRXN"),0),"^",2),0) I '$G(PSOPLCK) D LOCK^PSOORCPY Q
"RTN","PSOBBC",132,0)
 .S X=+$P(^PSRX(PSOBBC("IRXN"),0),"^",2)_";DPT(" D LK^ORX2 I 'Y S PSONOERR=1 D UL^PSSLOCK(+$P(^PSRX(PSOBBC("IRXN"),0),"^",2)) Q
"RTN","PSOBBC",133,0)
 .S PSODFNX(+$P(^PSRX(PSOBBC("IRXN"),0),"^",2))=""
"RTN","PSOBBC",134,0)
GETRXMX K X,Y,DIR,PSOOPT
"RTN","PSOBBC",135,0)
 Q
"RTN","PSOBBC",136,0)
 ;
"RTN","PSOBBC",137,0)
PT ;
"RTN","PSOBBC",138,0)
 S PSOBBC("DFLG")=0
"RTN","PSOBBC",139,0)
 W !,$C(7),"New Patient, please pause"
"RTN","PSOBBC",140,0)
 I $G(PPL) D SETX,TRI,Q^PSORXL K PPL
"RTN","PSOBBC",141,0)
 K RXFL
"RTN","PSOBBC",142,0)
 S (DFN,PSODFN)=$P(^PSRX(PSOBBC("IRXN"),0),"^",2),PSORX("NAME")=$P(^DPT(PSODFN,0),"^")
"RTN","PSOBBC",143,0)
 D ICN^PSODPT(DFN)
"RTN","PSOBBC",144,0)
 ;CHECK FOR BAD ADDRESS/SAB
"RTN","PSOBBC",145,0)
 S PSOLOUD=1 D:$P($G(^PS(55,PSODFN,0)),"^",6)'=2 EN^PSOHLUP(PSODFN) K PSOLOUD
"RTN","PSOBBC",146,0)
 D ^PSOBUILD
"RTN","PSOBBC",147,0)
 S PSOX=$G(^PS(55,PSODFN,"PS")) I PSOX]"" S PSORX("PATIENT STATUS")=$P($G(^PS(53,PSOX,0)),"^")
"RTN","PSOBBC",148,0)
 K PSOX
"RTN","PSOBBC",149,0)
PTC S (DFN,PSODFN)=$P(^PSRX(PSOBBC("IRXN"),0),"^",2)
"RTN","PSOBBC",150,0)
 S PSOLOUD=1 D:$P($G(^PS(55,PSODFN,0)),"^",6)'=2 EN^PSOHLUP(PSODFN) K PSOLOUD
"RTN","PSOBBC",151,0)
 S PSOBBC("DFLG")=0 D GET^PSOPTPST
"RTN","PSOBBC",152,0)
 I $G(PSOPTPST(2,PSODFN,.351))]"" S PSOBBC("DFLG")=1 D DEAD^PSOPTPST G PTX
"RTN","PSOBBC",153,0)
 N PSOTPEXT I $G(PSOBBC1("FROM"))="NEW",$D(^PS(52.91,PSODFN,0)) I '$P(^PS(52.91,PSODFN,0),"^",3)!($P(^(0),"^",3)>DT) D PDIR^PSOTPCAN(PSODFN) I $G(PSOTPEXT) K PSOTPEXT S PSOBBC("DFLG")=1 G PTX
"RTN","PSOBBC",154,0)
 K PSOTPEXT
"RTN","PSOBBC",155,0)
 I $G(PSOPTPST(2,PSODFN,.1))]"" D:'PSOBBC("INOK") PID W !,$C(7),?10,"PATIENT IS AN INPATIENT ON WARD ",PSOPTPST(2,PSODFN,.1)," !!" I 'PSOBBC("INOK") S PSOBBC("DFLG")=1 G PTX
"RTN","PSOBBC",156,0)
 K PSORX("CNH")
"RTN","PSOBBC",157,0)
 I $G(PSOPTPST(2,PSODFN,148))="YES" D:'PSOBBC("CNHOK") PID W !,$C(7),?10,"PATIENT IS IN A CONTRACT NURSING HOME !!" S:PSOBBC("CNHOK") PSORX("CNH")=1 I 'PSOBBC("CNHOK") S PSOBBC("DFLG")=1 G PTX
"RTN","PSOBBC",158,0)
 D:PSOBBC1("FROM")="NEW" COPAY^PSOPTPST
"RTN","PSOBBC",159,0)
PTX K PSOPTPST W:PSOBBC("DFLG") !!,$C(7),"Rx not filled"
"RTN","PSOBBC",160,0)
 Q
"RTN","PSOBBC",161,0)
 ;
"RTN","PSOBBC",162,0)
REFILL ;
"RTN","PSOBBC",163,0)
 N PSOFROM S PSOFROM="REFILL",XFROM="BATCH"
"RTN","PSOBBC",164,0)
 D EN^PSOREF0(.PSOBBC)
"RTN","PSOBBC",165,0)
 Q
"RTN","PSOBBC",166,0)
REFILLX ;
"RTN","PSOBBC",167,0)
 Q
"RTN","PSOBBC",168,0)
 ;
"RTN","PSOBBC",169,0)
NEW ;
"RTN","PSOBBC",170,0)
 N PSOFROM S (PSOFROM,XFROM)="BATCH"
"RTN","PSOBBC",171,0)
 S PSOBBC("OIRXN")=PSOBBC("IRXN")
"RTN","PSOBBC",172,0)
 S PSORNW("FILL DATE")=PSOBBC1("FILL DATE"),PSOOPT=3
"RTN","PSOBBC",173,0)
 S PSORX("DFLG")=0,PSOBBC("NOO")=$G(PSOBBCNO) D EN^PSORENW0(.PSOBBC)
"RTN","PSOBBC",174,0)
 S PSOBBC("MAIL/WINDOW")=PSOBBC1("MAIL/WINDOW")
"RTN","PSOBBC",175,0)
 S PSOBBC("EAOK")=$G(PSOBBC1("EAOK"))
"RTN","PSOBBC",176,0)
 S PSOBBC("QS")=PSOBBC1("QS")
"RTN","PSOBBC",177,0)
 S PSOBBC("INOK")=PSOBBC1("INOK")
"RTN","PSOBBC",178,0)
 S PSOBBC("CNHOK")=PSOBBC1("CNHOK")
"RTN","PSOBBC",179,0)
 S:$G(PSOBBC1("CLERK CODE")) PSOBBC("CLERK CODE")=PSOBBC1("CLERK CODE")
"RTN","PSOBBC",180,0)
 S:$G(PSOBBC1("EXPIRATION DATE")) PSOBBC("EXPIRATION DATE")=PSOBBC1("EXPIRATION DATE")
"RTN","PSOBBC",181,0)
 K PSORNW,PSOOPT
"RTN","PSOBBC",182,0)
 Q
"RTN","PSOBBC",183,0)
 ;
"RTN","PSOBBC",184,0)
EOJ ;
"RTN","PSOBBC",185,0)
 K PSOMSG,PSOREFXM,PSONOERR,PSOPLCK,PSOSD,PSOBBC,PSOBBC1,PSOBARID,Y,X,XFROM,PSOCOUU,PSOCOU,ACNT,ADFN,CLS,CMOP,CNT,FDR,HDR,PSCAN,JJ,POERR,PSOBCK,PSONEW3,PSORENW3,RXFL,PSOOPT
"RTN","PSOBBC",186,0)
 K PSORX,RFDT,RX1,RXS,SDA,PSONOOR,VALMBCK,VALMSG,SIG,SIGOK,STA,TM,TM1,VA,VADM,VAEL,VAPA
"RTN","PSOBBC",187,0)
 D CLEAN^PSOVER1 K ^TMP("PSORXDC",$J)
"RTN","PSOBBC",188,0)
 Q
"RTN","PSOBBC",189,0)
TRI ;Check for Tricare Rx's
"RTN","PSOBBC",190,0)
 S X="IBACUS" X ^%ZOSF("TEST") I '$T Q
"RTN","PSOBBC",191,0)
 I '$$TRI^IBACUS Q
"RTN","PSOBBC",192,0)
 Q:'$G(PPL)
"RTN","PSOBBC",193,0)
 ;PREV LINE, IN V 7 D ZOSF FIRST
"RTN","PSOBBC",194,0)
 N DA,NEWPPL,WWFLAG,PSOWRX,PSOWW,WWNEXT,WXRX,WPAT,WSITE,WDUZ,WFILL,WLOOP,WBILL,WPPLFLG,WWW
"RTN","PSOBBC",195,0)
 D DEV^PSOCPTRI
"RTN","PSOBBC",196,0)
 S NEWPPL=PPL S PPL=""
"RTN","PSOBBC",197,0)
 S (WWFLAG,WPPLFLG)=0 F PSOWW=1:1 S PSOWRX=$P(NEWPPL,",",PSOWW) D  Q:$G(WWFLAG)
"RTN","PSOBBC",198,0)
 .S WWNEXT=$P(NEWPPL,",",(PSOWW+1)) I WWNEXT=""!(WWNEXT=",") S WWFLAG=1
"RTN","PSOBBC",199,0)
 .I '$G(DT) S DT=$$DT^XLFDT
"RTN","PSOBBC",200,0)
 .S WPAT=$P($G(^PSRX(+PSOWRX,0)),"^",2),WSITE=+$G(PSOSITE),WDUZ=+$G(DUZ)
"RTN","PSOBBC",201,0)
 .S WFILL=0 F WLOOP=0:0 S WLOOP=$O(^PSRX(+PSOWRX,1,WLOOP)) Q:'WLOOP  S WFILL=WLOOP
"RTN","PSOBBC",202,0)
 .S WBILL=$$CHPUS^IBACUS(WPAT,DT,PSOWRX,WFILL,PSOLAP,WSITE,WDUZ)
"RTN","PSOBBC",203,0)
 .I '$G(WBILL) S WXRX(PSOWW,PSOWRX)="" Q
"RTN","PSOBBC",204,0)
 .S WPPLFLG=1
"RTN","PSOBBC",205,0)
 .S FLD(99)="99",FLD(99.1)="Awaiting CHAMPUS billing approval"
"RTN","PSOBBC",206,0)
 .N RSDT,ACT,PSUS,RXF,I,PSDA,NOW,IR,FDA,RFN S DA=PSOWRX D H^PSOCPTRH Q
"RTN","PSOBBC",207,0)
 I '$G(WPPLFLG) S PPL=NEWPPL Q
"RTN","PSOBBC",208,0)
 S WWW="" F  S WWW=$O(WXRX(WWW)) Q:WWW=""  D
"RTN","PSOBBC",209,0)
 .I $G(PPL)="" S PPL=$O(WXRX(WWW,0))_"," Q
"RTN","PSOBBC",210,0)
 .S PPL=PPL_$O(WXRX(WWW,0))_","
"RTN","PSOBBC",211,0)
 Q
"RTN","PSOBBC",212,0)
ULK ;
"RTN","PSOBBC",213,0)
 Q:$G(PSOBBC1("FROM"))'="NEW"
"RTN","PSOBBC",214,0)
 I '$G(PSODFN) Q
"RTN","PSOBBC",215,0)
 S X=PSODFN_";DPT(" D ULK^ORX2 K PSODFNX(PSODFN) Q
"RTN","PSOBBC",216,0)
ULP Q:$G(PSOBBC1("FROM"))'="NEW"
"RTN","PSOBBC",217,0)
 Q:'$G(PSODFN)
"RTN","PSOBBC",218,0)
 D UL^PSSLOCK(PSODFN)
"RTN","PSOBBC",219,0)
 Q
"RTN","PSOBBC",220,0)
ULRX ;
"RTN","PSOBBC",221,0)
 Q:$G(PSOBBC1("FROM"))'="REFILL"
"RTN","PSOBBC",222,0)
 Q:'$G(PSOREFXM)
"RTN","PSOBBC",223,0)
 D PSOUL^PSSLOCK(PSOREFXM)
"RTN","PSOBBC",224,0)
 K PSOREFXM
"RTN","PSOBBC",225,0)
 Q
"RTN","PSOBBC",226,0)
 ;
"RTN","PSOBBC",227,0)
SETX ;
"RTN","PSOBBC",228,0)
 S:$G(PSOBBC1("FROM"))="REFILL" XFROM="BATCH"
"RTN","PSOBBC",229,0)
 S:$G(PSOBBC1("FROM"))="NEW" XFROM="BATCH"
"RTN","PSOBBC",230,0)
 Q
"RTN","PSOBBC",231,0)
PID ;
"RTN","PSOBBC",232,0)
 I '$G(DFN) S DFN=+$G(PSODFN)
"RTN","PSOBBC",233,0)
 Q:'$G(DFN)
"RTN","PSOBBC",234,0)
 K VAPTYP D PID^VADPT
"RTN","PSOBBC",235,0)
 W !!,?9,$G(PSORX("NAME"))_"    ",$G(VA("BID"))
"RTN","PSOBBC",236,0)
 K VA("BID"),VA("PID")
"RTN","PSOBBC",237,0)
 Q
"RTN","PSOORFI3")
0^2^B74326144^B74814603
"RTN","PSOORFI3",1,0)
PSOORFI3 ;BIR/RTR-finish CPRS orders by Clinic ;11/09/98
"RTN","PSOORFI3",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**15,27,32,46,84,99,130,117,139,172,225,300**;DEC 1997;Build 4
"RTN","PSOORFI3",3,0)
 ;SC(-2675,40.8-728,51.2-2226,50.607-2221,55-2228,PSSLOCK-2789,DPT-10035,ORX2-867
"RTN","PSOORFI3",4,0)
 ;
"RTN","PSOORFI3",5,0)
 K ^TMP($J,"PSOCL"),^TMP($J,"PSOCLX"),PSOCLIN,PSOCLINF,PSOXINST
"RTN","PSOORFI3",6,0)
 N PSOCFLAG,PSONPTRX,PSOINPTR,PSCLP,PSOCLINS,PSOSTC,PSOLGD,PSODIEN,PSOCTMP
"RTN","PSOORFI3",7,0)
 K DIR S DIR(0)="SMB^C:CLINIC;S:SORT GROUP;E:EXIT",DIR("A")="Select By",DIR("B")="Clinic",DIR("?",1)="Enter 'C' to process orders for one individual Clinic,"
"RTN","PSOORFI3",8,0)
 S DIR("?",2)="      'S' to process orders for all Clinics associated with a Sort Group,",DIR("?",3)="      '^' or 'E' to exit" S DIR("?")=" "
"RTN","PSOORFI3",9,0)
 W ! D ^DIR K DIR I $D(DTOUT)!($D(DUOUT))!(Y="E") W ! G EXIT
"RTN","PSOORFI3",10,0)
 I Y="S" G SORT
"RTN","PSOORFI3",11,0)
CLIN W ! K DIC S DIC="^SC(",DIC(0)="QEAMZ",DIC("A")="Select CLINIC: " D ^DIC K DIC I Y<1!($D(DTOUT))!($D(DUOUT)) G EXIT
"RTN","PSOORFI3",12,0)
 S PSOCLIN=+Y,PSOCLINF=1 D CHECK I $G(PSOCFLAG) D INSTNM^PSOORFI2 W !!,"You are signed in under the "_$G(PSODINST)_" CPRS Ordering",!,"Institution, which does not match the Institution for this Clinic!",! K PSODINST G CLIN
"RTN","PSOORFI3",13,0)
 S ^TMP($J,"PSOCL",PSOCLIN)=PSOCLIN K PSOCLIN G START
"RTN","PSOORFI3",14,0)
SORT W ! K DIC S DIC="^PS(59.8,",DIC(0)="QEAMZ",DIC("A")="Select CLINIC SORT GROUP: " D ^DIC K DIC I Y<1!($D(DTOUT))!($D(DUOUT)) G EXIT
"RTN","PSOORFI3",15,0)
 S PSOCLINS=+Y
"RTN","PSOORFI3",16,0)
 K ^TMP($J,"PSOCL"),^TMP($J,"PSOCLX") F PSCLP=0:0 S PSCLP=$O(^PS(59.8,PSOCLINS,1,PSCLP)) Q:'PSCLP  S PSOSTC=+$P($G(^PS(59.8,PSOCLINS,1,PSCLP,0)),"^") S:$G(PSOSTC)&($D(^SC(PSOSTC,0))) ^TMP($J,"PSOCL",PSOSTC)=PSOSTC
"RTN","PSOORFI3",17,0)
 I '$O(^TMP($J,"PSOCL",0)) W !!,"There are no Clinics associated with this Sort Group!",! K ^TMP($J,"PSOCL") G SORT
"RTN","PSOORFI3",18,0)
 F PSCLP=0:0 S PSCLP=$O(^TMP($J,"PSOCL",PSCLP)) Q:'PSCLP  S PSOCLIN=PSCLP D CHECK I $G(PSOCFLAG) S ^TMP($J,"PSOCLX",PSCLP)=PSCLP K ^TMP($J,"PSOCL",PSCLP)
"RTN","PSOORFI3",19,0)
 I $O(^TMP($J,"PSOCLX",0)) H 1 W @IOF W !,"Orders for these Clinics in the Sort Group will not be displayed for Finishing",!,"because the CPRS Ordering Institution does not match the Institution that is",!,"associated with the Clinic:",! D
"RTN","PSOORFI3",20,0)
 .F PSCLP=0:0 S PSCLP=$O(^TMP($J,"PSOCLX",PSCLP)) Q:'PSCLP  D:($Y+4)>IOSL  W !,$P($G(^SC(PSCLP,0)),"^")
"RTN","PSOORFI3",21,0)
 ..W ! K DIR S DIR(0)="E",DIR("A")="Press RETURN to continue" D ^DIR K DIR W @IOF
"RTN","PSOORFI3",22,0)
 I $O(^TMP($J,"PSOCLX",0)) D EOP
"RTN","PSOORFI3",23,0)
 K ^TMP($J,"PSOCLX") I '$O(^TMP($J,"PSOCL",0)) W !!,"There are no Clinics that have a matching Institution!",! D EOP G SORT
"RTN","PSOORFI3",24,0)
 ;
"RTN","PSOORFI3",25,0)
 S PSOCLINF=2
"RTN","PSOORFI3",26,0)
START K MEDP,MEDA,PSOQUIT,POERR("QFLG"),POERR("DFLG"),DIR
"RTN","PSOORFI3",27,0)
 G:'$O(^TMP($J,"PSOCL",0)) EXIT
"RTN","PSOORFI3",28,0)
 S PATA=0 F PSOCLIN=0:0 S PSOCLIN=$O(^TMP($J,"PSOCL",PSOCLIN)) Q:'PSOCLIN!($G(POERR("QFLG")))  F PSOLGD=0:0 S PSOLGD=$O(^PS(52.41,"ACL",PSOCLIN,PSOLGD)) Q:'PSOLGD!($G(POERR("QFLG")))  D
"RTN","PSOORFI3",29,0)
 .F PSODIEN=0:0 S PSODIEN=$O(^PS(52.41,"ACL",PSOCLIN,PSOLGD,PSODIEN)) Q:'PSODIEN!($G(POERR("QFLG")))  D
"RTN","PSOORFI3",30,0)
 ..I $P($G(^PS(52.41,PSODIEN,0)),"^",3)'="NW",$P($G(^(0)),"^",3)'="RNW",$P($G(^(0)),"^",3)'="RF" Q
"RTN","PSOORFI3",31,0)
 ..I $G(PSOPINST)'=$P($G(^PS(52.41,PSODIEN,"INI")),"^") Q
"RTN","PSOORFI3",32,0)
 ..Q:$G(PAT($P(^PS(52.41,PSODIEN,0),"^",2)))=$P(^PS(52.41,PSODIEN,0),"^",2)  S PAT=$P(^PS(52.41,PSODIEN,0),"^",2)
"RTN","PSOORFI3",33,0)
 ..I PAT'=PATA,$O(PSORX("PSOL",0))!($D(RXRS)) D LBL^PSOORFIN
"RTN","PSOORFI3",34,0)
 ..D LK^PSOORFIN I $G(POERR("QFLG")) K POERR("QFLG") S PSOLK=1,PAT(PAT)=PAT Q
"RTN","PSOORFI3",35,0)
 ..I $$CHK^PSODPT(PAT_"^"_$P($G(^DPT(PAT,0)),"^"),1,1)<0 S PSOLK=1,PAT(PAT)=PAT S X=PAT D ULP^PSOORFIN Q
"RTN","PSOORFI3",36,0)
 ..S (PSODFN,Y)=PAT_"^"_$P($G(^DPT(+$G(PAT),0)),"^"),PATA=PAT
"RTN","PSOORFI3",37,0)
 ..D:'$G(MEDA) PROFILE^PSOORFI2 S Y=PSODFN I $G(MEDP) K PSOFIN S POERR("QFLG")=0 S PSONOLCK=1,PSOPTLOK=PAT D OERR^PSORX1 S PSOFIN=1 D QU^PSOORFIN S X=PSOPTLOK D KLLP^PSOORFIN,ULP^PSOORFIN,KLL^PSOORFIN Q
"RTN","PSOORFI3",38,0)
 ..D SDFN^PSOORFIN D POST^PSOORFI1 I $G(PSOQFLG)!($G(PSOQUIT)) S:$G(PSOQUIT) POERR("QFLG")=1 S:$G(PSOQFLG) PAT(PAT)=PAT S X=PAT D ULP^PSOORFIN K PSOQFLG Q
"RTN","PSOORFI3",39,0)
 ..S PAT(PAT)=PAT
"RTN","PSOORFI3",40,0)
 ..F ORD=0:0 S ORD=$O(^PS(52.41,"AOR",PAT,PSOPINST,ORD)) Q:'ORD!($G(POERR("QFLG")))  I '$P($G(^PS(52.41,ORD,0)),"^",23) D
"RTN","PSOORFI3",41,0)
 ...S PSODFN=PAT D NOW^%DTC S TM=$E(%,1,12),TM1=$P(TM,".",2)
"RTN","PSOORFI3",42,0)
 ...D LK1^PSOORFIN,ORD^PSOORFIN S X=PAT D ULP^PSOORFIN
"RTN","PSOORFI3",43,0)
 I $O(PSORX("PSOL",0))!($D(RXRS)) D LBL^PSOORFIN
"RTN","PSOORFI3",44,0)
 ;
"RTN","PSOORFI3",45,0)
EXIT K ^TMP($J,"PSOCL"),^TMP($J,"PSOCLX"),PSOCLIN,PSOCLINF,PSOXINST G EX^PSOORFIN
"RTN","PSOORFI3",46,0)
 Q
"RTN","PSOORFI3",47,0)
CHECK ; check Institution
"RTN","PSOORFI3",48,0)
 K PSOXINST,PSOCFLAG
"RTN","PSOORFI3",49,0)
 I $P($G(^SC(PSOCLIN,0)),"^",4),$P($G(^(0)),"^",4)'=$G(PSOPINST) S PSOCFLAG=1 Q
"RTN","PSOORFI3",50,0)
 I $P($G(^SC(PSOCLIN,0)),"^",4) Q
"RTN","PSOORFI3",51,0)
 S PSONPTRX=$P($G(^SC(PSOCLIN,0)),"^",15)
"RTN","PSOORFI3",52,0)
 I '$G(PSONPTRX) S PSONPTRX=$O(^DG(40.8,0))
"RTN","PSOORFI3",53,0)
 I '$G(DT) S DT=$$DT^XLFDT
"RTN","PSOORFI3",54,0)
 S PSOINPTR=+$$SITE^VASITE(DT,PSONPTRX) I PSOINPTR'=$G(PSOPINST) S PSOCFLAG=1
"RTN","PSOORFI3",55,0)
 Q
"RTN","PSOORFI3",56,0)
EOP W ! K DIR S DIR(0)="E",DIR("A")="Press RETURN to continue" D ^DIR K DIR
"RTN","PSOORFI3",57,0)
 Q
"RTN","PSOORFI3",58,0)
L1 ;Lock single order
"RTN","PSOORFI3",59,0)
 I '$G(ORD) Q
"RTN","PSOORFI3",60,0)
 K PSOMSG D PSOL^PSSLOCK(+ORD_"S") I '$G(PSOMSG) W !!,$S($P($G(PSOMSG),"^",2)'="":$P($G(PSOMSG),"^",2),1:"This Order is being edited by another person."),! K DIR S DIR(0)="E",DIR("A")="Press Return to Continue" D ^DIR K DIR
"RTN","PSOORFI3",61,0)
 Q
"RTN","PSOORFI3",62,0)
UL1 ;Unlock single order
"RTN","PSOORFI3",63,0)
 I '$G(ORD) Q
"RTN","PSOORFI3",64,0)
 I '$D(^PS(52.41,ORD,0)) D  Q
"RTN","PSOORFI3",65,0)
 . D UNLK1^ORX2(+$G(OR0))
"RTN","PSOORFI3",66,0)
 . Q
"RTN","PSOORFI3",67,0)
 D PSOUL^PSSLOCK(+ORD_"S")
"RTN","PSOORFI3",68,0)
 Q
"RTN","PSOORFI3",69,0)
DOSE ;pending orders
"RTN","PSOORFI3",70,0)
 K DOENT S DS=1
"RTN","PSOORFI3",71,0)
 F I=0:0 S I=$O(^PS(52.41,ORD,1,I)) Q:'I  S DOSE=$G(^PS(52.41,ORD,1,I,1)),DOSE1=$G(^(2)) D  D DOSE1
"RTN","PSOORFI3",72,0)
 .S PSONEW("DOSE",I)=$P(DOSE1,"^"),PSONEW("DOSE ORDERED",I)=$P(DOSE1,"^",2),PSONEW("UNITS",I)=$P(DOSE,"^",9),PSONEW("NOUN",I)=$P(DOSE,"^",5)
"RTN","PSOORFI3",73,0)
 .S:$P(DOSE,"^",9) UNITS=$P(^PS(50.607,$P(DOSE,"^",9),0),"^")
"RTN","PSOORFI3",74,0)
 .S PSONEW("VERB",I)=$P(DOSE,"^",10),PSONEW("ROUTE",I)=$P(DOSE,"^",8)
"RTN","PSOORFI3",75,0)
 .S:$P(DOSE,"^",8) ROUTE=$P(^PS(51.2,$P(DOSE,"^",8),0),"^")
"RTN","PSOORFI3",76,0)
 .S PSONEW("SCHEDULE",I)=$P(DOSE,"^"),PSONEW("DURATION",I)=$P(DOSE,"^",2)
"RTN","PSOORFI3",77,0)
 .S DOENT=$G(DOENT)+1 S PSONEW("CONJUNCTION",I)=$S($P(DOSE,"^",6)="A":"AND",$P(DOSE,"^",6)="S":"THEN",$P(DOSE,"^",6)="X":"EXCEPT",1:"")
"RTN","PSOORFI3",78,0)
 .I 'PSONEW("DOSE ORDERED",I),$G(PSONEW("VERB",I))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Verb: "_$G(PSONEW("VERB",I))
"RTN","PSOORFI3",79,0)
 .S:$G(DS) IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" (3)"
"RTN","PSOORFI3",80,0)
 S PSONEW("ENT")=DOENT K DOSE,DOSE1,I,UNITS,ROUTE,DOENT
"RTN","PSOORFI3",81,0)
 Q
"RTN","PSOORFI3",82,0)
DOSE1 I $G(DS)=1 S ^TMP("PSOPO",$J,IEN,0)=^TMP("PSOPO",$J,IEN,0)_"        *Dosage:" D FMD G DU
"RTN","PSOORFI3",83,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="            *Dosage:" D FMD
"RTN","PSOORFI3",84,0)
DU I 'PSONEW("DOSE ORDERED",I),$P($G(^PS(55,PSODFN,"LAN")),"^") S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="  Oth. Lang. Dosage: "_$G(PSONEW("ODOSE",I))
"RTN","PSOORFI3",85,0)
 I PSONEW("DOSE ORDERED",I),$G(PSONEW("VERB",I))]"" D
"RTN","PSOORFI3",86,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Verb: "_$G(PSONEW("VERB",I))
"RTN","PSOORFI3",87,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="     Dispense Units: "_$S($E(PSONEW("DOSE ORDERED",I),1)=".":"0",1:"")_PSONEW("DOSE ORDERED",I)
"RTN","PSOORFI3",88,0)
 I PSONEW("NOUN",I) S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Noun: "_PSONEW("NOUN",I)
"RTN","PSOORFI3",89,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="             *Route: "_$G(ROUTE)
"RTN","PSOORFI3",90,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="          *Schedule: "_PSONEW("SCHEDULE",I)
"RTN","PSOORFI3",91,0)
 I $P(DOSE,"^",2)]"" D
"RTN","PSOORFI3",92,0)
 .S DUR=$S($E($P(DOSE,"^",2),1)'?.N:$E($P(DOSE,"^",2),2,99)_$E($P(DOSE,"^",2),1),1:$P(DOSE,"^",2))
"RTN","PSOORFI3",93,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="          *Duration: "_DUR_" ("_$S($P(DOSE,"^",2)["M":"MINUTES",$P(DOSE,"^",2)["H":"HOURS",$P(DOSE,"^",2)["L":"MONTHS",$P(DOSE,"^",2)["W":"WEEKS",1:"DAYS")_")"
"RTN","PSOORFI3",94,0)
 I $P(DOSE,"^",6)]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="       *Conjunction: "_$S($P(DOSE,"^",6)="A":"AND",$P(DOSE,"^",6)="S":"THEN",$P(DOSE,"^",6)="X":"EXCEPT",1:"")
"RTN","PSOORFI3",95,0)
 Q
"RTN","PSOORFI3",96,0)
DOSE2 ;displays pending order after edits
"RTN","PSOORFI3",97,0)
 S DS=1
"RTN","PSOORFI3",98,0)
 F I=1:1:PSONEW("ENT") Q:'I  D  D DOSE3 K COJ
"RTN","PSOORFI3",99,0)
 .S:$G(PSONEW("UNITS",I))]"" UNITS=$P(^PS(50.607,PSONEW("UNITS",I),0),"^") S:$G(PSONEW("ROUTE",I))]"" ROUTE=$P(^PS(51.2,PSONEW("ROUTE",I),0),"^")
"RTN","PSOORFI3",100,0)
 .S DUR=$G(PSONEW("DURATION",I)) S:$G(PSONEW("CONJUNCTION",I))]"" COJ=PSONEW("CONJUNCTION",I)
"RTN","PSOORFI3",101,0)
 .S NOUN=PSONEW("NOUN",I),VERB=$G(PSONEW("VERB",I))
"RTN","PSOORFI3",102,0)
 .I 'PSONEW("DOSE ORDERED",I),$P($G(^PS(55,PSODFN,"LAN")),"^") S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="  Oth. Lang. Dosage: "_$G(PSONEW("ODOSE",I))
"RTN","PSOORFI3",103,0)
 .I '$G(PSONEW("DOSE ORDERED",I)),$G(PSONEW("VERB",I))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Verb: "_$G(PSONEW("VERB",I))
"RTN","PSOORFI3",104,0)
 .S:$G(DS) IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" (3)"
"RTN","PSOORFI3",105,0)
 K I,UNITS,ROUTE,DUR,COJ,VERB,NOUN
"RTN","PSOORFI3",106,0)
 Q
"RTN","PSOORFI3",107,0)
DOSE3 I $G(DS)=1 S ^TMP("PSOPO",$J,IEN,0)=^TMP("PSOPO",$J,IEN,0)_"        *Dosage:" D FMD G DO
"RTN","PSOORFI3",108,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="            *Dosage:" D FMD
"RTN","PSOORFI3",109,0)
DO I 'PSONEW("DOSE ORDERED",I),$P($G(^PS(55,PSODFN,"LAN")),"^") S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="  Oth. Lang. Dosage: "_$G(PSONEW("ODOSE",I))
"RTN","PSOORFI3",110,0)
 I $G(PSONEW("DOSE ORDERED",I)),$G(PSONEW("VERB",I))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Verb: "_$G(PSONEW("VERB",I))
"RTN","PSOORFI3",111,0)
 I $G(PSONEW("DOSE ORDERED",I)) S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="     Dispense Units: "_$S($E(PSONEW("DOSE ORDERED",I),1)=".":"0",1:"")_PSONEW("DOSE ORDERED",I)
"RTN","PSOORFI3",112,0)
 I $G(PSONEW("DOSE ORDERED",I)) S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               NOUN: "_PSONEW("NOUN",I)
"RTN","PSOORFI3",113,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="             *Route: "_$G(ROUTE)
"RTN","PSOORFI3",114,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="          *Schedule: "_PSONEW("SCHEDULE",I)
"RTN","PSOORFI3",115,0)
 I $G(DUR)]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="          *Duration: "_DUR_" ("_$S(DUR["M":"MINUTES",DUR["H":"HOURS",DUR["L":"MONTHS",DUR["W":"WEEKS",1:"DAYS")_")"
"RTN","PSOORFI3",116,0)
 I $G(COJ)]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="       *Conjunction: "_$S(COJ="A":"AND",COJ="T":"THEN",COJ="X":"EXCEPT",1:"")
"RTN","PSOORFI3",117,0)
 Q
"RTN","PSOORFI3",118,0)
FMD Q:$G(PSONEW("DOSE",II))']""  S MIG=PSONEW("DOSE",II)
"RTN","PSOORFI3",119,0)
 I $E(MIG,1)=".",$G(PSONEW("DOSE ORDERED",II)) S MIG="0"_MIG
"RTN","PSOORFI3",120,0)
 F SG=1:1:$L(MIG," ") S:$L(^TMP("PSOPO",$J,IEN,0)_" "_$P(MIG," ",SG))>80 IEN=IEN+1,$P(^TMP("PSOPO",$J,IEN,0)," ",20)=" " S ^TMP("PSOPO",$J,IEN,0)=$G(^TMP("PSOPO",$J,IEN,0))_" "_$P(MIG," ",SG)
"RTN","PSOORFI3",121,0)
 I $G(UNITS)]"" S:$L(^TMP("PSOPO",$J,IEN,0)_" ("_UNITS_")")>80 IEN=IEN+1,$P(^TMP("PSOPO",$J,IEN,0)," ",20)=" " S ^TMP("PSOPO",$J,IEN,0)=$G(^TMP("PSOPO",$J,IEN,0))_" ("_UNITS_")"
"RTN","PSOORFI3",122,0)
 K DS,MIG,SG
"RTN","PSOORFI3",123,0)
 I '$G(PSONEW("DOSE ORDERED",II)),$P($G(^PS(55,PSODFN,"LAN")),"^") D LAN^PSOORED5
"RTN","PSOORFI3",124,0)
 Q
"RTN","PSOORFI3",125,0)
SQR ;
"RTN","PSOORFI3",126,0)
 D SQR^PSOORFIN
"RTN","PSOORFI3",127,0)
 Q
"RTN","PSOORFI3",128,0)
SQN ;
"RTN","PSOORFI3",129,0)
 K MAXRF,PSOSIG,MPSDY,PSOMAX,STA,PSORX0,ORCHK,ORDRG
"RTN","PSOORFI3",130,0)
 I $G(PSOQUIT) S PSOQQ=1 K PSOQUIT
"RTN","PSOORFI3",131,0)
 Q
"RTN","PSOORFI4")
0^9^B67401126^B68531413
"RTN","PSOORFI4",1,0)
PSOORFI4 ;BIR/SAB-CPRS order checks and display con't ; 6/28/07 7:36am
"RTN","PSOORFI4",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**46,74,78,99,117,131,207,258,274,300**;DEC 1997;Build 4
"RTN","PSOORFI4",3,0)
 ;External reference to ^PS(51.2 supported by DBIA 2226
"RTN","PSOORFI4",4,0)
 ;External reference to ^PS(50.607 supported by DBIA 2221
"RTN","PSOORFI4",5,0)
 ;External reference ^PS(55 supported by DBIA 2228
"RTN","PSOORFI4",6,0)
 ;External reference to ^PS(50.7 is supported by DBIA 2223
"RTN","PSOORFI4",7,0)
 ;
"RTN","PSOORFI4",8,0)
ORCHK D ORCHK^PSOORNE6
"RTN","PSOORFI4",9,0)
 Q
"RTN","PSOORFI4",10,0)
INST ;displays patient instructions
"RTN","PSOORFI4",11,0)
 I $O(PSONEW("SIG",0)) G INST1
"RTN","PSOORFI4",12,0)
 S INST=0 F  S INST=$O(^PS(52.41,ORD,"INS1",INST)) Q:'INST  S (MIG,PSONEW("SIG",INST))=^PS(52.41,ORD,"INS1",INST,0) D
"RTN","PSOORFI4",13,0)
 .F SG=1:1:$L(MIG," ") S:$L(^TMP("PSOPO",$J,IEN,0)_" "_$P(MIG," ",SG))>80 IEN=IEN+1,$P(^TMP("PSOPO",$J,IEN,0)," ",20)=" " S ^TMP("PSOPO",$J,IEN,0)=$G(^TMP("PSOPO",$J,IEN,0))_" "_$P(MIG," ",SG)
"RTN","PSOORFI4",14,0)
 I $P($G(^PS(55,PSODFN,"LAN")),"^"),$O(^PS(52.41,ORD,"INS1",0)) D
"RTN","PSOORFI4",15,0)
 .I $G(^PS(50.7,PSODRUG("OI"),"INS1"))]"" S (X,PSONEW("SINS"))=^PS(50.7,PSODRUG("OI"),"INS1") D SSIG^PSOHELP
"RTN","PSOORFI4",16,0)
 .I $G(SINS1)]"" S PSONEW("SINS")=$E(SINS1,2,250)
"RTN","PSOORFI4",17,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" Other Pat Instruct: "_$S($G(PSONEW("SINS"))]"":PSONEW("SINS"),1:"")
"RTN","PSOORFI4",18,0)
 K INST,TY,MIG,SG,SINS1
"RTN","PSOORFI4",19,0)
 Q
"RTN","PSOORFI4",20,0)
INST1 ;
"RTN","PSOORFI4",21,0)
 S INS=0 F  S INS=$O(PSONEW("SIG",INS)) Q:'INS  S MIG=PSONEW("SIG",INS) D
"RTN","PSOORFI4",22,0)
 .F SG=1:1:$L(MIG," ") S:$L(^TMP("PSOPO",$J,IEN,0)_" "_$P(MIG," ",SG))>80 IEN=IEN+1,$P(^TMP("PSOPO",$J,IEN,0)," ",20)=" " S ^TMP("PSOPO",$J,IEN,0)=$G(^TMP("PSOPO",$J,IEN,0))_" "_$P(MIG," ",SG)
"RTN","PSOORFI4",23,0)
 K INST,TY,MIG,SG
"RTN","PSOORFI4",24,0)
 I $P($G(^PS(55,PSODFN,"LAN")),"^") S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" Other Pat Instruct: "_$S($G(PSONEW("SINS"))]"":PSONEW("SINS"),1:"")
"RTN","PSOORFI4",25,0)
 Q
"RTN","PSOORFI4",26,0)
PROVCOM ;
"RTN","PSOORFI4",27,0)
 I $G(PKI1)=1,'$G(PSORX("VERIFY")) D REA^PSOPKIV1 Q:$G(PSORX("DFLG"))
"RTN","PSOORFI4",28,0)
 I $O(PRC(0)),'$G(PSOPRC) D  D KV^PSOVER1
"RTN","PSOORFI4",29,0)
 .D EN^DDIOL("Provider Comments: ","","!")
"RTN","PSOORFI4",30,0)
 .F I=0:0 S I=$O(PRC(I)) Q:'I  D EN^DDIOL(PRC(I),"","!")
"RTN","PSOORFI4",31,0)
 .D KV^PSOVER1 S DIR(0)="Y",DIR("A")="Copy Provider Comments into the Patient Instructions",DIR("B")="No"
"RTN","PSOORFI4",32,0)
 .D ^DIR Q:'Y!($D(DIRUT))
"RTN","PSOORFI4",33,0)
 .S PSOPRC=1,NI=0 F I=0:0 S I=$O(PSONEW("SIG",I)) Q:'I  S NI=I
"RTN","PSOORFI4",34,0)
 .S NC=0 F I=0:0 S I=$O(PRC(I)) Q:'I  S NC=NC+1
"RTN","PSOORFI4",35,0)
 .I NI'>1,NC=1,($L($G(PSONEW("SIG",NI)))+$L(PRC(1)))'>250 D  Q 
"RTN","PSOORFI4",36,0)
 ..S X=PRC(1) D SIGONE^PSOHELP
"RTN","PSOORFI4",37,0)
 ..S PSONEW("SIG",1)=$G(PSONEW("SIG",NI))_INS1 K INS1,X
"RTN","PSOORFI4",38,0)
 ..S:$E(PSONEW("SIG",1))=" " PSONEW("SIG",1)=$E(PSONEW("SIG",1),2,250) S PSONEW("INS")=PSONEW("SIG",1) D EN^PSOFSIG(.PSONEW,1) K NI,NC
"RTN","PSOORFI4",39,0)
 .F I=0:0 S I=$O(PRC(I)) Q:'I  S NI=NI+1,(PSONEW("INS",NI),X)=PRC(I) D SIGONE^PSOHELP S PSONEW("SIG",NI)=INS1 K INS1
"RTN","PSOORFI4",40,0)
 .I $E(PSONEW("SIG",1))=" " S PSONEW("SIG",1)=$E(PSONEW("SIG",1),2,250)
"RTN","PSOORFI4",41,0)
 .D EN^PSOFSIG(.PSONEW,1) K NI,NC,X
"RTN","PSOORFI4",42,0)
 Q
"RTN","PSOORFI4",43,0)
DOSE ;displays dosing info for pending orders.  called from psoorfi1
"RTN","PSOORFI4",44,0)
 K II,UNITS S DS=1
"RTN","PSOORFI4",45,0)
 I '$O(^PS(52.41,ORD,1,0)) S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" (3)        *Dosage:" G DOSEX
"RTN","PSOORFI4",46,0)
 F I=0:0 S I=$O(^PS(52.41,ORD,1,I)) Q:'I  S DOSE=$G(^PS(52.41,ORD,1,I,1)),DOSE1=$G(^(2)) D  D DOSE1
"RTN","PSOORFI4",47,0)
 .S II=$G(II)+1 K PSONEW("UNITS",II)
"RTN","PSOORFI4",48,0)
 .S PSONEW("DOSE",II)=$P(DOSE1,"^"),PSONEW("DOSE ORDERED",II)=$P(DOSE1,"^",2),PSONEW("UNITS",II)=$P(DOSE,"^",9),PSONEW("NOUN",II)=$P(DOSE,"^",5)
"RTN","PSOORFI4",49,0)
 .S:$P(DOSE,"^",9) UNITS=$P(^PS(50.607,$P(DOSE,"^",9),0),"^")
"RTN","PSOORFI4",50,0)
 .S PSONEW("VERB",II)=$P(DOSE,"^",10),PSONEW("ROUTE",II)=$P(DOSE,"^",8)
"RTN","PSOORFI4",51,0)
 .S:$P(DOSE,"^",8) ROUTE=$P(^PS(51.2,$P(DOSE,"^",8),0),"^")
"RTN","PSOORFI4",52,0)
 .S PSONEW("SCHEDULE",II)=$P(DOSE,"^"),PSONEW("DURATION",II)=$P(DOSE,"^",2)
"RTN","PSOORFI4",53,0)
 .S DOENT=$G(DOENT)+1 I $P(DOSE,"^",6)]"" S PSONEW("CONJUNCTION",II)=$S($P(DOSE,"^",6)="S":"T",$P(DOSE,"^",6)="X":"X",1:"A")
"RTN","PSOORFI4",54,0)
 .I 'PSONEW("DOSE ORDERED",II),$G(PSONEW("VERB",II))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Verb: "_$G(PSONEW("VERB",II))
"RTN","PSOORFI4",55,0)
 .S:$G(DS) IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" (3)"
"RTN","PSOORFI4",56,0)
DOSEX S PSONEW("ENT")=+$G(II) K DOSE,DOSE1,II,I,UNITS,ROUTE,DG
"RTN","PSOORFI4",57,0)
 Q
"RTN","PSOORFI4",58,0)
DOSE1 I $G(DS)=1 S ^TMP("PSOPO",$J,IEN,0)=^TMP("PSOPO",$J,IEN,0)_"        *Dosage:" D FMD^PSOORFI3 G DU
"RTN","PSOORFI4",59,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="            *Dosage:" D FMD^PSOORFI3
"RTN","PSOORFI4",60,0)
DU I 'PSONEW("DOSE ORDERED",I),$P($G(^PS(55,PSODFN,"LAN")),"^") S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" *Oth. Lang. Dosage: "_$G(PSONEW("ODOSE",I))
"RTN","PSOORFI4",61,0)
 I PSONEW("DOSE ORDERED",II),$G(PSONEW("VERB",II))]"" D
"RTN","PSOORFI4",62,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Verb: "_$G(PSONEW("VERB",II))
"RTN","PSOORFI4",63,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="     Dispense Units: "_$S($E(PSONEW("DOSE ORDERED",II),1)=".":"0",1:"")_PSONEW("DOSE ORDERED",II)
"RTN","PSOORFI4",64,0)
 I PSONEW("NOUN",II)]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Noun: "_PSONEW("NOUN",II)
"RTN","PSOORFI4",65,0)
 I $G(ROUTE)]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="             *Route: "_$G(ROUTE)
"RTN","PSOORFI4",66,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="          *Schedule: "_PSONEW("SCHEDULE",II)
"RTN","PSOORFI4",67,0)
 I $G(PSONEW("DURATION",II))]"" D
"RTN","PSOORFI4",68,0)
 .S PSONEW("DURATION",II)=$S($E(PSONEW("DURATION",II),1)'?.N:$E(PSONEW("DURATION",II),2,99)_$E(PSONEW("DURATION",II),1),1:PSONEW("DURATION",II))
"RTN","PSOORFI4",69,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="          *Duration: "_PSONEW("DURATION",II)_" ("_$S(PSONEW("DURATION",II)["M":"MINUTES",PSONEW("DURATION",II)["H":"HOURS",PSONEW("DURATION",II)["L":"MONTHS",PSONEW("DURATION",II)["W":"WEEKS",1:"DAYS")_")"
"RTN","PSOORFI4",70,0)
 I $G(PSONEW("CONJUNCTION",II))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="       *Conjunction: "_$S(PSONEW("CONJUNCTION",II)="T":"THEN",PSONEW("CONJUNCTION",II)="X":"EXCEPT",1:"AND")
"RTN","PSOORFI4",71,0)
 Q
"RTN","PSOORFI4",72,0)
DOSE2 ;displays pending order after edits.  called from psoornew
"RTN","PSOORFI4",73,0)
 I '$O(PSONEW("DOSE",0))!($O(PSONEW("DOSE",0))="") S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" (3)        *Dosage:" Q
"RTN","PSOORFI4",74,0)
 S DS=1
"RTN","PSOORFI4",75,0)
 F I=1:1:PSONEW("ENT") Q:'I  D  D DOSE3 K COJ
"RTN","PSOORFI4",76,0)
 .S:$G(PSONEW("UNITS",I))]"" UNITS=$P(^PS(50.607,PSONEW("UNITS",I),0),"^")
"RTN","PSOORFI4",77,0)
 .I $G(PSONEW("ROUTE",I))]"",$G(^PS(51.2,PSONEW("ROUTE",I),0))]"" S ROUTE=$P(^PS(51.2,PSONEW("ROUTE",I),0),"^")
"RTN","PSOORFI4",78,0)
 .S DUR=$G(PSONEW("DURATION",I)) S:$G(PSONEW("CONJUNCTION",I))]"" COJ=PSONEW("CONJUNCTION",I)
"RTN","PSOORFI4",79,0)
 .S NOUN=$G(PSONEW("NOUN",I)),VERB=$G(PSONEW("VERB",I))
"RTN","PSOORFI4",80,0)
 .I '$G(PSONEW("DOSE ORDERED",I)),$G(PSONEW("VERB",I))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Verb: "_$G(PSONEW("VERB",I))
"RTN","PSOORFI4",81,0)
 .S:$G(DS) IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" (3)"
"RTN","PSOORFI4",82,0)
 K I,UNITS,ROUTE,DUR,COJ,VERB,NOUN,DG
"RTN","PSOORFI4",83,0)
 Q
"RTN","PSOORFI4",84,0)
DOSE3 I $G(DS)=1 S II=I,^TMP("PSOPO",$J,IEN,0)=^TMP("PSOPO",$J,IEN,0)_"        *Dosage:" D FMD^PSOORFI3 G DO
"RTN","PSOORFI4",85,0)
 S II=I,IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="            *Dosage:" D FMD^PSOORFI3
"RTN","PSOORFI4",86,0)
DO I '$G(PSONEW("DOSE ORDERED",I)),$P($G(^PS(55,PSODFN,"LAN")),"^") S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" *Oth. Lang. Dosage: "_$G(PSONEW("ODOSE",I))
"RTN","PSOORFI4",87,0)
 I $G(PSONEW("DOSE ORDERED",I)),$G(PSONEW("VERB",I))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               Verb: "_$G(PSONEW("VERB",I))
"RTN","PSOORFI4",88,0)
 I $G(PSONEW("DOSE ORDERED",I)) S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="     Dispense Units: "_$S($E(PSONEW("DOSE ORDERED",I),1)=".":"0",1:"")_PSONEW("DOSE ORDERED",I)
"RTN","PSOORFI4",89,0)
 I $G(PSONEW("NOUN",I))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="               NOUN: "_PSONEW("NOUN",I)
"RTN","PSOORFI4",90,0)
 I $G(ROUTE)]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="             *Route: "_$G(ROUTE)
"RTN","PSOORFI4",91,0)
 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="          *Schedule: "_PSONEW("SCHEDULE",I)
"RTN","PSOORFI4",92,0)
 I $G(PSONEW("DURATION",I))]"" D
"RTN","PSOORFI4",93,0)
 .S PSONEW("DURATION",I)=$S($E(PSONEW("DURATION",I),1)'?.N:$E(PSONEW("DURATION",I),2,99)_$E(PSONEW("DURATION",I),1),1:PSONEW("DURATION",I))
"RTN","PSOORFI4",94,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="          *Duration: "_PSONEW("DURATION",I)_" ("_$S(PSONEW("DURATION",I)["M":"MINUTES",PSONEW("DURATION",I)["H":"HOURS",PSONEW("DURATION",I)["L":"MONTHS",PSONEW("DURATION",I)["W":"WEEKS",1:"DAYS")_")"
"RTN","PSOORFI4",95,0)
 I $G(PSONEW("CONJUNCTION",I))]"" S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="       *Conjunction: "_$S(PSONEW("CONJUNCTION",I)="T":"THEN",PSONEW("CONJUNCTION",I)="X":"EXCEPT",1:"AND")
"RTN","PSOORFI4",96,0)
 Q
"RTN","PSOORFI4",97,0)
OBX ;formats obx section
"RTN","PSOORFI4",98,0)
 N COM,II
"RTN","PSOORFI4",99,0)
 D:$G(PKI1) L1^PSOPKIV1
"RTN","PSOORFI4",100,0)
 I $O(^PS(52.41,ORD,"OBX",0)) S (T,IEN)=0,IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="Order Checks:" F  S T=$O(^PS(52.41,ORD,"OBX",T)) Q:'T  D  S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)=" "
"RTN","PSOORFI4",101,0)
 .S COM=$G(^PS(52.41,ORD,"OBX",T,0))
"RTN","PSOORFI4",102,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="     " F II=1:1:$L(COM," ") D
"RTN","PSOORFI4",103,0)
 ..I $L(^TMP("PSOPO",$J,IEN,0)_" "_$P(COM," ",II))>80 S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="     "
"RTN","PSOORFI4",104,0)
 ..S ^TMP("PSOPO",$J,IEN,0)=^TMP("PSOPO",$J,IEN,0)_" "_$P(COM," ",II)
"RTN","PSOORFI4",105,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="     Overriding Provider: "_$G(^PS(52.41,ORD,"OBX",T,1))
"RTN","PSOORFI4",106,0)
 .S IEN=IEN+1,^TMP("PSOPO",$J,IEN,0)="     Overriding Reason:"
"RTN","PSOORFI4",107,0)
 .F T1=0:0 S T1=$O(^PS(52.41,ORD,"OBX",T,2,T1)) Q:'T1  D
"RTN","PSOORFI4",108,0)
 ..S MIG=^PS(52.41,ORD,"OBX",T,2,T1,0)
"RTN","PSOORFI4",109,0)
 ..F SG=1:1:$L(MIG," ") S:$L(^TMP("PSOPO",$J,IEN,0)_" "_$P(MIG," ",SG))>80 IEN=IEN+1,$P(^TMP("PSOPO",$J,IEN,0)," ",23)=" " S ^TMP("PSOPO",$J,IEN,0)=$G(^TMP("PSOPO",$J,IEN,0))_" "_$P(MIG," ",SG)
"RTN","PSOORFI4",110,0)
 Q
"RTN","PSOORFI4",111,0)
PP S PSODFN=PAT D NOW^%DTC S TM=$E(%,1,12),TM1=$P(TM,".",2)
"RTN","PSOORFI4",112,0)
 Q
"RTN","PSOORFI4",113,0)
SPL K PSOFIN S POERR("QFLG")=0 S PSONOLCK=1,PSOPTLOK=PAT
"RTN","PSOORFI4",114,0)
 Q
"RTN","PSOORFI4",115,0)
CLQTY ;
"RTN","PSOORFI4",116,0)
 K PSONEW("QTY")
"RTN","PSOORFI4",117,0)
 D QTY^PSOSIG(.PSONEW)
"RTN","PSOORFI4",118,0)
 S:'$G(PSONEW("QTY")) PSONEW("QTY")=0
"RTN","PSOORFI4",119,0)
 Q
"RTN","PSOORFI4",120,0)
PQTY ;
"RTN","PSOORFI4",121,0)
 S ^TMP("PSOPO",$J,IEN,0)=^TMP("PSOPO",$J,IEN,0)_", days supply of "_+$P(OR0,"^",22)_" and a qty of "_+$P(OR0,"^",10)
"RTN","PSOORFI4",122,0)
 Q
"RTN","PSOORFI4",123,0)
REF Q:$G(PSODRUG("DEA"))']""
"RTN","PSOORFI4",124,0)
 S CS=0 F DEA=1:1 Q:$E(PSODRUG("DEA"),DEA)=""  I $E(+PSODRUG("DEA"),DEA)>1,$E(+PSODRUG("DEA"),DEA)<6 S CS=1
"RTN","PSOORFI4",125,0)
 S PTRF=PSONEW("# OF REFILLS"),PSDAYS=PSONEW("DAYS SUPPLY")
"RTN","PSOORFI4",126,0)
 I CS D
"RTN","PSOORFI4",127,0)
 .S PSOX1=$S(PTRF>5:5,1:PTRF),PSOX=$S(PSOX1=5:5,1:PSOX1)
"RTN","PSOORFI4",128,0)
 .S PSOX=$S('PSOX:0,PSDAYS=90:1,1:PSOX),PSDY1=$S(PSDAYS<60:5,PSDAYS'<60&(PSDAYS'>89):2,PSDAYS=90:1,1:0)
"RTN","PSOORFI4",129,0)
 E  D
"RTN","PSOORFI4",130,0)
 .S PSOX1=PTRF,PSOX=$S(PSOX1=11:11,1:PSOX1),PSOX=$S('PSOX:0,PSDAYS=90:3,1:PSOX)
"RTN","PSOORFI4",131,0)
 .S PSDY1=$S(PSDAYS<60:11,PSDAYS'<60&(PSDAYS'>89):5,PSDAYS=90:3,1:0)
"RTN","PSOORFI4",132,0)
 S PSONEW("# OF REFILLS")=$S(PSONEW("# OF REFILLS")>PSDY1:PSDY1,1:PSONEW("# OF REFILLS"))
"RTN","PSOORFI4",133,0)
 Q
"RTN","PSOPRF")
0^3^B35238813^B36401491
"RTN","PSOPRF",1,0)
PSOPRF ;BHAM ISC/SAB - PRINTS A PROFILE ;11/18/92
"RTN","PSOPRF",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**19,132,300**;DEC 1997;Build 4
"RTN","PSOPRF",3,0)
 ;External reference to File #55 supported by DBIA 2228
"RTN","PSOPRF",4,0)
 ;External reference ^PS(50.606 supported by DBIA 2174
"RTN","PSOPRF",5,0)
 ;External reference ^PS(50.7 supported by DBIA 2223
"RTN","PSOPRF",6,0)
 ;External reference ^PSDRUG( supported by DBIA 221
"RTN","PSOPRF",7,0)
 ;PHARMACIST IN REVEIWING RX'S WHEN ADDING A 'NEW' RX
"RTN","PSOPRF",8,0)
Q D CUTDATE^PSOFUNC
"RTN","PSOPRF",9,0)
QOLD D PLBL^PSORXL
"RTN","PSOPRF",10,0)
 Q
"RTN","PSOPRF",11,0)
 ;
"RTN","PSOPRF",12,0)
DQ S:'$D(PFIO) PFIO=IO D START D KILL^%ZTLOAD Q
"RTN","PSOPRF",13,0)
 ;
"RTN","PSOPRF",14,0)
START D:('$D(PSOBMST)) EN1P^PSOBSET K Z S IOP=PFIO D ^%ZIS U IO I '$D(PSODTCUT) D CUTDATE^PSOFUNC
"RTN","PSOPRF",15,0)
 S:'$D(Z) Z=1 S:'$D(NEW1) (NEW1,NEW11)="^" S %DT="",X="T" D ^%DT S DT=Y S X1=DT,X2=-365 D C^%DTC S EXPS=X S X1=DT,X2=-182 D C^%DTC S EXP=X
"RTN","PSOPRF",16,0)
 K ^TMP($J,"PRF") S LINE="" F I=1:1:110 S LINE=LINE_"-"
"RTN","PSOPRF",17,0)
 F RXX=0:0 S RXX=$O(^PS(55,DFN,"P",RXX)) Q:'RXX  S RXNN=+^(RXX,0) I $D(^PSRX(RXNN,0)),$P($G(^("STA")),"^")'=13 S RXPX=^PSRX(RXNN,0),$P(RXPX,"^",15)=$P($G(^("STA")),"^"),RXPX2=^(2) D CHK
"RTN","PSOPRF",18,0)
 D HD I '$D(^TMP($J,"PRF")) W !!?Z+15,"****** NO RX DATA ******",! G PPP
"RTN","PSOPRF",19,0)
 ;
"RTN","PSOPRF",20,0)
SD F SD="A","C","S" W:SD="S" !,?Z+1,"SUPPLIES",$E(LINE,1,89) I $D(^TMP($J,"PRF",SD)) S DRNME="" D DRNME
"RTN","PSOPRF",21,0)
PPP D PEND,NVA
"RTN","PSOPRF",22,0)
 W !!,"NAME: "_$P(^DPT(DFN,0),"^"),!,"ID#: "_VA("PID"),!
"RTN","PSOPRF",23,0)
 W:IOF]"" @IOF K ^TMP($J,"PRF"),A,B,DRNME,DRP,EXP,EXPS,I,II,ISSD,J,LINE,LN,MESS,MJK,NEW1,NEW11,PHYS,POP,QTY,TTTT,RFL,RFS,RXF,RXNN,RXPX,RXPX2,RXPNO,RXX,SD,SIG,STA,X,X1,X2,Y,Z
"RTN","PSOPRF",24,0)
 Q
"RTN","PSOPRF",25,0)
 ;
"RTN","PSOPRF",26,0)
DRNME S DRNME=$O(^TMP($J,"PRF",SD,DRNME)) Q:DRNME=""  D ISSD G DRNME
"RTN","PSOPRF",27,0)
 ;
"RTN","PSOPRF",28,0)
ISSD F ISSD=0:0 S ISSD=$O(^TMP($J,"PRF",SD,DRNME,ISSD)) Q:'ISSD  S RXPNO="" D RXPNO
"RTN","PSOPRF",29,0)
 Q
"RTN","PSOPRF",30,0)
 ;
"RTN","PSOPRF",31,0)
RXPNO S RXPNO=$O(^TMP($J,"PRF",SD,DRNME,ISSD,RXPNO)) Q:RXPNO=""  S RXNN=^(RXPNO) I $D(^PSRX(RXNN,0)) S RXPX=^(0),RXPX2=^(2) D PRT G RXPNO
"RTN","PSOPRF",32,0)
 W "END***************"
"RTN","PSOPRF",33,0)
 ;
"RTN","PSOPRF",34,0)
CHK Q:PSODTCUT>$P(RXPX2,"^",6)
"RTN","PSOPRF",35,0)
 I $P(^PSRX(RXNN,"STA"),"^")=12 S II=RXNN D LAST^PSORFL Q:PSODTCUT>RFDATE
"RTN","PSOPRF",36,0)
 I $P(RXPX,"^",3)=7!($P(RXPX,"^",3)=8)&('PSOPRPAS) Q
"RTN","PSOPRF",37,0)
 S J="^"_RXNN_"^" Q:(NEW1[J)!(NEW11[J)  Q:$P(RXPX,"^",13)<EXPS  S RXPNO=$P(RXPX,"^"),ISSD=$P(RXPX,"^",13)
"RTN","PSOPRF",38,0)
 Q:'$D(^PSDRUG($P(RXPX,"^",6),0))  S DRP=^(0),SD=$S($P(DRP,"^",3)["S":"S",$P(RXPX,"^",15)=12:"C",1:"A"),DRNME=$P(DRP,"^"),^TMP($J,"PRF",SD,DRNME,ISSD,RXPNO)=RXNN
"RTN","PSOPRF",39,0)
 Q
"RTN","PSOPRF",40,0)
 ;
"RTN","PSOPRF",41,0)
PRT S RFS=$P(RXPX,"^",9),QTY=$P(RXPX,"^",7)
"RTN","PSOPRF",42,0)
 S PHYS=$S($D(^VA(200,$P(RXPX,"^",4),0)):$P(^(0),"^"),1:"UNKNOWN"),II=RXNN D LAST^PSORFL S RXF=0 F MJK=0:0 S MJK=$O(^PSRX(RXNN,1,MJK)) Q:'MJK  S RXF=RXF+1
"RTN","PSOPRF",43,0)
 S STA=$S($P(^PSRX(RXNN,"STA"),"^")=14:"DC",$P(^PSRX(RXNN,"STA"),"^")=15:"DE",$P(^PSRX(RXNN,"STA"),"^")=16:"PH",1:$E("ANRHPS     ECD",(1+$P(^PSRX(RXNN,"STA"),"^")))),STA=$S(DT>$P(RXPX2,"^",6):"E",1:STA)
"RTN","PSOPRF",44,0)
 W !,?Z+1,RXPNO,?Z+15,DRNME,?Z+55,$E(ISSD,4,5),"/",$E(ISSD,6,7)," ",$E(RFL,1,5)," ",?Z+67,$J(RFS,2)," ",$J(RXF,2)," ",?Z+73,$J(QTY,12)," ",?Z+86,STA," ",?Z+88,$E(PHYS,1,20)
"RTN","PSOPRF",45,0)
 D SIG F TTTT=0:0 S TTTT=$O(FSIG(TTTT)) Q:'TTTT  W !,?Z+19,FSIG(TTTT)
"RTN","PSOPRF",46,0)
 Q
"RTN","PSOPRF",47,0)
 ;
"RTN","PSOPRF",48,0)
HD D PID^VADPT
"RTN","PSOPRF",49,0)
 W !,?Z+17,"PRESCRIPTION PROFILE AS OF ",$E(DT,4,5),"/",$E(DT,6,7),"/",($E(DT,1,3)+1700),!!,?Z+20,"NAME: "_$P(^DPT(DFN,0),"^"),!,?Z+20,"ID# : "_VA("PID")
"RTN","PSOPRF",50,0)
 I $D(^PS(55,DFN,1)) S MESS=^(1),LN=$L(MESS),A=0 W ! F B=1:1 Q:$P(MESS," ",B,99)=""  W:$X>(Z+63) ! W ?Z+31,$P(MESS," ",B)," "
"RTN","PSOPRF",51,0)
 W !!?Z+20,"PHARMACIST: ___________________________  DATE: ____________"
"RTN","PSOPRF",52,0)
 W !!?Z+52,"   DATES   ",?Z+67,"REFS ",?Z+86,"S"
"RTN","PSOPRF",53,0)
 W !?Z+1,"RX #     ",?Z+15,"DRUG/STRENGTH/SIG",?Z+55,"ISSD  LAST ",?Z+67,"AL AC",?Z+77,"QTY",?Z+86,"T",?Z+93,"PROVIDER"
"RTN","PSOPRF",54,0)
 W !?Z+1,$E(LINE,1,12),?Z+15,$E(LINE,1,35),?Z+55,"----- -----",?Z+67,"-- --",?Z+73,"------------",?Z+86,"-",?Z+88,$E(LINE,1,20)
"RTN","PSOPRF",55,0)
 Q
"RTN","PSOPRF",56,0)
SIG ;Format Sig
"RTN","PSOPRF",57,0)
 S PSPROSIG=$P($G(^PSRX(RXNN,"SIG")),"^",2) K FSIG,BSIG D
"RTN","PSOPRF",58,0)
 .I PSPROSIG D FSIG^PSOUTLA("R",RXNN,80) Q
"RTN","PSOPRF",59,0)
 .D EN2^PSOUTLA1(RXNN,80) F GGGGG=0:0 S GGGGG=$O(BSIG(GGGGG)) Q:'GGGGG  S FSIG(GGGGG)=BSIG(GGGGG)
"RTN","PSOPRF",60,0)
 K PSPROSIG,GGGGG,BSIG Q
"RTN","PSOPRF",61,0)
PEND ;Print Pending Orders
"RTN","PSOPRF",62,0)
 N PSPCOUNT,PSPPEND,ZXXX,PSPSTAT,FSIGZZ,PZZDRUG,PSSODRUG,PZXZERO,PPPPP,GGGGG
"RTN","PSOPRF",63,0)
 S PSPCOUNT=1,PSPPEND="" F PPPPP=0:0 S PPPPP=$O(^PS(52.41,"P",DFN,PPPPP)) Q:'PPPPP  S PSPSTAT=$P($G(^PS(52.41,PPPPP,0)),"^",3) I PSPSTAT="NW"!(PSPSTAT="HD")!(PSPSTAT="RNW") S PSPPEND(PSPCOUNT)=PPPPP,PSPCOUNT=PSPCOUNT+1
"RTN","PSOPRF",64,0)
 Q:'$O(PSPPEND(0))
"RTN","PSOPRF",65,0)
 W !!,?48,"PENDING ORDERS",!,LINE,!
"RTN","PSOPRF",66,0)
 F ZXXX=0:0 S ZXXX=$O(PSPPEND(ZXXX)) Q:'ZXXX  S PZXZERO=$G(^PS(52.41,PSPPEND(ZXXX),0)) D:$P(PZXZERO,"^")
"RTN","PSOPRF",67,0)
 .S PZZDRUG=$P(PZXZERO,"^",9),PZZODRUG=$P(PZXZERO,"^",8)
"RTN","PSOPRF",68,0)
 .W !,"Drug: ",$S(PZZDRUG:$P($G(^PSDRUG(+PZZDRUG,0)),"^"),1:$P($G(^PS(50.7,+PZZODRUG,0)),"^")_" "_$P($G(^PS(50.606,+$P($G(^(0)),"^",2),0)),"^"))
"RTN","PSOPRF",69,0)
 .W !?3,"Eff. Date: ",$E($P(PZXZERO,"^",6),4,5)_"/"_$E($P(PZXZERO,"^",6),6,7)_"/"_($E($P(PZXZERO,"^",6),1,3)+1700)
"RTN","PSOPRF",70,0)
 .W ?25,"Qty: ",$P(PZXZERO,"^",10),?50,"Refills: ",$P(PZXZERO,"^",11),?65,"Provider: ",$P($G(^VA(200,+$P(PZXZERO,"^",5),0)),"^")
"RTN","PSOPRF",71,0)
 .D FSIG^PSOUTLA("P",PSPPEND(ZXXX),100) W !?3,"Sig: ",$G(FSIG(1)) F FSIGZZ=1:0 S FSIGZZ=$O(FSIG(FSIGZZ)) Q:'FSIGZZ  W !?8,$G(FSIG(FSIGZZ))
"RTN","PSOPRF",72,0)
 Q
"RTN","PSOPRF",73,0)
NVA ;displays non-va meds
"RTN","PSOPRF",74,0)
 Q:'$G(DFN)!('$O(^PS(55,DFN,"NVA",0)))
"RTN","PSOPRF",75,0)
 W !!?48,"Non-VA MEDS (Not dispensed by VA)",!,LINE
"RTN","PSOPRF",76,0)
 F NVA=0:0 S NVA=$O(^PS(55,DFN,"NVA",NVA)) Q:'NVA  D
"RTN","PSOPRF",77,0)
 .S DUPRX0=^PS(55,DFN,"NVA",NVA,0) Q:'$P(DUPRX0,"^")
"RTN","PSOPRF",78,0)
 .W !!,"Orderable Item: "_$P(^PS(50.7,$P(DUPRX0,"^"),0),"^")_" "_$P(^PS(50.606,$P(^(0),"^",2),0),"^")_"   Drug: "_$S($P(DUPRX0,"^",2):$P(^PSDRUG($P(DUPRX0,"^",2),0),"^"),1:"No Dispense Drug Selected")
"RTN","PSOPRF",79,0)
 .W !,"Status: "_$S($P(DUPRX0,"^",7):"Discontinued ("_$$FMTE^XLFDT($P($P(DUPRX0,"^",7),"."))_")",1:"Active")
"RTN","PSOPRF",80,0)
 .W !,"Drug Class: "_$S($P(DUPRX0,"^",2):$P(^PSDRUG($P(DUPRX0,"^",2),0),"^",2),1:"")
"RTN","PSOPRF",81,0)
 .W !,"Dosage: "_$P(DUPRX0,"^",3),!,"Schedule: "_$P(DUPRX0,"^",5),!,"Medication Route: "_$P(DUPRX0,"^",4)
"RTN","PSOPRF",82,0)
 .W !,"Start Date: "_$$FMTE^XLFDT($P(DUPRX0,"^",9)),?40,"CPRS Oder #: "_$P(DUPRX0,"^",8)
"RTN","PSOPRF",83,0)
 .W !,"Documented By: "_$P(^VA(200,$P(DUPRX0,"^",11),0),"^")_" on "_$$FMTE^XLFDT($P(DUPRX0,"^",10))
"RTN","PSOPRF",84,0)
 W ! K NVA,DUPRXO
"RTN","PSOPRF",85,0)
 Q
"RTN","PSOPRFSS")
0^8^B16329111^B17329169
"RTN","PSOPRFSS",1,0)
PSOPRFSS ;BHAM ISC/SAB - PRINTS A PROFILE FROM SUSPENSE ; 11/18/92 19:38
"RTN","PSOPRFSS",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**19,300**;DEC 1997;Build 4
"RTN","PSOPRFSS",3,0)
 ;PHARMACIST IN REVEIWING RX'S WHEN ADDING A 'NEW' RX
"RTN","PSOPRFSS",4,0)
Q D CUTDATE^PSOFUNC
"RTN","PSOPRFSS",5,0)
QOLD D PLBL^PSORXL
"RTN","PSOPRFSS",6,0)
 Q
"RTN","PSOPRFSS",7,0)
 ;
"RTN","PSOPRFSS",8,0)
DQ D START Q
"RTN","PSOPRFSS",9,0)
 ;
"RTN","PSOPRFSS",10,0)
START D:('$D(PSOBMST)) EN1P^PSOBSET K Z I '$D(PSODTCUT) D CUTDATE^PSOFUNC
"RTN","PSOPRFSS",11,0)
 S:'$D(Z) Z=1 S:'$D(NEW1) (NEW1,NEW11)="^" S %DT="",X="T" D ^%DT S DT=Y S X1=DT,X2=-365 D C^%DTC S EXPS=X S X1=DT,X2=-182 D C^%DTC S EXP=X
"RTN","PSOPRFSS",12,0)
 K ^TMP($J,"PRF") S LINE="" F I=1:1:110 S LINE=LINE_"-"
"RTN","PSOPRFSS",13,0)
 F RXX=0:0 S RXX=$O(^PS(55,DFN,"P",RXX)) Q:'RXX  S RXNN=+^(RXX,0) I $D(^PSRX(RXNN,0)),$P($G(^("STA")),"^")'=13 S RXPX=^PSRX(RXNN,0),$P(RXPX,"^",15)=$P($G(^("STA")),"^"),RXPX2=^(2) D CHK
"RTN","PSOPRFSS",14,0)
 D HD I '$D(^TMP($J,"PRF")) W !!?Z+15,"****** NO RX DATA ******",! G PPP
"RTN","PSOPRFSS",15,0)
 ;
"RTN","PSOPRFSS",16,0)
SD F SD="A","C","S" W:SD="S" !,?Z+1,"SUPPLIES",$E(LINE,1,89) I $D(^TMP($J,"PRF",SD)) S DRNME="" D DRNME
"RTN","PSOPRFSS",17,0)
PPP D PEND^PSOPRF
"RTN","PSOPRFSS",18,0)
 W !!,"NAME: "_$P(^DPT(DFN,0),"^"),!,"ID#: "_VA("PID"),!
"RTN","PSOPRFSS",19,0)
 W:IOF]"" @IOF K ^TMP($J,"PRF"),A,B,DRNME,DRP,EXP,EXPS,I,II,ISSD,J,LINE,LN,MESS,MJK,NEW1,NEW11,PHYS,POP,QTY,TTTT,RFL,RFS,RXF,RXNN,RXPX,RXPX2,RXPNO,RXX,SD,SIG,STA,X,X1,X2,Y,Z
"RTN","PSOPRFSS",20,0)
 Q
"RTN","PSOPRFSS",21,0)
 ;
"RTN","PSOPRFSS",22,0)
DRNME S DRNME=$O(^TMP($J,"PRF",SD,DRNME)) Q:DRNME=""  D ISSD G DRNME
"RTN","PSOPRFSS",23,0)
 ;
"RTN","PSOPRFSS",24,0)
ISSD F ISSD=0:0 S ISSD=$O(^TMP($J,"PRF",SD,DRNME,ISSD)) Q:'ISSD  S RXPNO="" D RXPNO
"RTN","PSOPRFSS",25,0)
 Q
"RTN","PSOPRFSS",26,0)
 ;
"RTN","PSOPRFSS",27,0)
RXPNO S RXPNO=$O(^TMP($J,"PRF",SD,DRNME,ISSD,RXPNO)) Q:RXPNO=""  S RXNN=^(RXPNO) I $D(^PSRX(RXNN,0)) S RXPX=^(0),RXPX2=^(2) D PRT G RXPNO
"RTN","PSOPRFSS",28,0)
 W "END***************"
"RTN","PSOPRFSS",29,0)
 ;
"RTN","PSOPRFSS",30,0)
CHK Q:PSODTCUT>$P(RXPX2,"^",6)
"RTN","PSOPRFSS",31,0)
 I $P(^PSRX(RXNN,"STA"),"^")=12 S II=RXNN D LAST^PSORFL Q:PSODTCUT>RFDATE
"RTN","PSOPRFSS",32,0)
 I $P(RXPX,"^",3)=7!($P(RXPX,"^",3)=8)&('PSOPRPAS) Q
"RTN","PSOPRFSS",33,0)
 S J="^"_RXNN_"^" Q:(NEW1[J)!(NEW11[J)  Q:$P(RXPX,"^",13)<EXPS  S RXPNO=$P(RXPX,"^"),ISSD=$P(RXPX,"^",13)
"RTN","PSOPRFSS",34,0)
 Q:'$D(^PSDRUG($P(RXPX,"^",6),0))  S DRP=^(0),SD=$S($P(DRP,"^",3)["S":"S",$P(RXPX,"^",15)=12:"C",1:"A"),DRNME=$P(DRP,"^"),^TMP($J,"PRF",SD,DRNME,ISSD,RXPNO)=RXNN
"RTN","PSOPRFSS",35,0)
 Q
"RTN","PSOPRFSS",36,0)
 ;
"RTN","PSOPRFSS",37,0)
PRT S RFS=$P(RXPX,"^",9),QTY=$P(RXPX,"^",7)
"RTN","PSOPRFSS",38,0)
 S PHYS=$S($D(^VA(200,$P(RXPX,"^",4),0)):$P(^(0),"^"),1:"UNKNOWN"),II=RXNN D LAST^PSORFL S RXF=0 F MJK=0:0 S MJK=$O(^PSRX(RXNN,1,MJK)) Q:'MJK  S RXF=RXF+1
"RTN","PSOPRFSS",39,0)
 S STA=$S($P(^PSRX(RXNN,"STA"),"^")=14:"DC",$P(^PSRX(RXNN,"STA"),"^")=15:"DE",$P(^PSRX(RXNN,"STA"),"^")=16:"PH",1:$E("ANRHPS     ECD",(1+$P(^PSRX(RXNN,"STA"),"^")))),STA=$S(DT>$P(RXPX2,"^",6):"E",1:STA)
"RTN","PSOPRFSS",40,0)
 W !,?Z+1,RXPNO,?Z+15,DRNME,?Z+55,$E(ISSD,4,5),"/",$E(ISSD,6,7)," ",$E(RFL,1,5)," ",?Z+67,$J(RFS,2)," ",$J(RXF,2)," ",?Z+73,$J(QTY,12)," ",?Z+86,STA," ",?Z+88,$E(PHYS,1,20)
"RTN","PSOPRFSS",41,0)
 D SIG^PSOPRF F TTTT=0:0 S TTTT=$O(FSIG(TTTT)) Q:'TTTT  W !,?Z+19,FSIG(TTTT)
"RTN","PSOPRFSS",42,0)
 Q
"RTN","PSOPRFSS",43,0)
 ;
"RTN","PSOPRFSS",44,0)
HD D PID^VADPT
"RTN","PSOPRFSS",45,0)
 W !,?Z+17,"PRESCRIPTION PROFILE AS OF ",$E(DT,4,5),"/",$E(DT,6,7),"/",($E(DT,1,3)+1700)
"RTN","PSOPRFSS",46,0)
 W !!,?Z+20,"NAME: ",$P(^DPT(DFN,0),"^"),!,?Z+20,"ID# : "_VA("PID")
"RTN","PSOPRFSS",47,0)
 I $D(^PS(55,DFN,1)) S MESS=^(1),LN=$L(MESS),A=0 W ! F B=1:1 Q:$P(MESS," ",B,99)=""  W:$X>(Z+63) ! W ?Z+31,$P(MESS," ",B)," "
"RTN","PSOPRFSS",48,0)
 W !!?Z+20,"PHARMACIST: ___________________________  DATE: ____________"
"RTN","PSOPRFSS",49,0)
 W !!?Z+52,"   DATES   ",?Z+67,"REFS ",?Z+86,"S"
"RTN","PSOPRFSS",50,0)
 W !?Z+1,"RX #     ",?Z+15,"DRUG/STRENGTH/SIG",?Z+55,"ISSD  LAST ",?Z+67,"AL AC",?Z+77,"QTY",?Z+86,"T",?Z+93,"PROVIDER"
"RTN","PSOPRFSS",51,0)
 W !?Z+1,$E(LINE,1,12),?Z+15,$E(LINE,1,35),?Z+55,"----- -----",?Z+67,"-- --",?Z+73,"------------",?Z+86,"-",?Z+88,$E(LINE,1,20)
"RTN","PSOPRI")
0^4^B23541806^B24224309
"RTN","PSOPRI",1,0)
PSOPRI ;BIR/JLC - INTERNET PRESCRIPTION REFILL PROCESSOR ;3/27/06 2:23pm
"RTN","PSOPRI",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**116,204,242,264,300**;DEC 1997;Build 4
"RTN","PSOPRI",3,0)
 ;
"RTN","PSOPRI",4,0)
 ;Reference to ^PSSLOCK supported by DBIA 2789
"RTN","PSOPRI",5,0)
 ;Reference to DIC(19 supported by DBIA 2246
"RTN","PSOPRI",6,0)
 ;
"RTN","PSOPRI",7,0)
 ;PSO*242 do not init PSODFN, it should only be set by label print
"RTN","PSOPRI",8,0)
 ;
"RTN","PSOPRI",9,0)
START L +^XTMP("PSOATRF"):5 I '$T D  Q
"RTN","PSOPRI",10,0)
 .D BMES^XPDUTL("The scheduled job is currently running - Please try it later.")
"RTN","PSOPRI",11,0)
 .D MES^XPDUTL("")
"RTN","PSOPRI",12,0)
 L -^XTMP("PSOATRF") S PSOVEX=1
"RTN","PSOPRI",13,0)
 K PSOVEXI,PSOISITE,PSOVEXFL,PSONOF
"RTN","PSOPRI",14,0)
 S PSOVX=0 F  S PSOVX=$O(^PS(59,PSOVX)) Q:'PSOVX  I $P($G(^PS(59,PSOVX,"I")),"^"),DT>$P($G(^("I")),"^") S PSOVEXI(PSOVX)=""
"RTN","PSOPRI",15,0)
 I $O(PSOVEXI(0)) W !,"Looking for refill requests for inactive Outpatient divisions..." D
"RTN","PSOPRI",16,0)
 . S PSOVIN=0 F  S PSOVIN=$O(^PS(52.43,"AINST",PSOVIN)) Q:'PSOVIN  S PSOVXLP="" F  S PSOVXLP=$O(^PS(52.43,"AINST",PSOVIN,PSOVXLP)) Q:PSOVXLP=""  D
"RTN","PSOPRI",17,0)
 .. S PSOIEN=$O(^PS(52.43,"AINST",PSOVIN,PSOVXLP,""))
"RTN","PSOPRI",18,0)
 .. S PSOISITE=$P($G(^PSRX(PSOVXLP,2)),"^",9) Q:$G(PSOVEXI(+$G(PSOISITE)))
"RTN","PSOPRI",19,0)
 .. I PSOISITE,$D(PSOVEXI(PSOISITE)),$P($G(^PS(52.43,PSOIEN,0)),"^",5)="" S PSOVEXI(PSOISITE)=1,PSOVEXFL=1
"RTN","PSOPRI",20,0)
 . I '$G(PSOVEXFL) W ".none found.",!
"RTN","PSOPRI",21,0)
 I $G(PSOVEXFL) W !!,"The following Inactive Outpatient sites have refill requests:",! D  I Y'=1 G END
"RTN","PSOPRI",22,0)
 . S PSOVX=0 F  S PSOVX=$O(PSOVEXI(PSOVX)) Q:'PSOVX  I $G(PSOVEXI(PSOVX)) W !?5,$P($G(^PS(59,+$G(PSOVX),0)),"^")
"RTN","PSOPRI",23,0)
 . K DIR W ! S DIR(0)="E",DIR("A")="Press Return to Continue, '^' to exit" D ^DIR W ! I Y'=1 Q
"RTN","PSOPRI",24,0)
 D:'$D(PSOPAR) ^PSOLSET G:'$D(PSOPAR) END
"RTN","PSOPRI",25,0)
 W !!!?20,"Division: "_$P(^PS(59,PSOSITE,0),"^"),!!
"RTN","PSOPRI",26,0)
 S PSOBBC1("FROM")="REFILL",PSOBBC("QFLG")=0,PSOBBC("DFLG")=0
"RTN","PSOPRI",27,0)
 I '$D(^PS(52.43,"AINST",PSOINST)) S PSOANS="N" W !!?7,$C(7),"There are no internet refills to process." G END
"RTN","PSOPRI",28,0)
 D ASK^PSOBBC W:PSOBBC("QFLG")=1 !?7,$C(7),"No internet refills were processed." G:PSOBBC("QFLG")=1 END
"RTN","PSOPRI",29,0)
IPR W ! S DIR("B")="YES",DIR("A")="Process internet refill requests at this time",DIR(0)="Y" D ^DIR K DIR S PSOANS="N" I $G(DIRUT) S PSOPTRX="" G END
"RTN","PSOPRI",30,0)
 G:Y=0 END S PSOPTRX="" I Y=1 S PSOANS="Y"
"RTN","PSOPRI",31,0)
 I PSOANS["Y" S DIR("B")="NO",DIR("A")="Process internet refills for all divisions",DIR(0)="Y" D ^DIR K DIR S PSOANS2="S" S:Y=1 PSOANS2="M" I $G(DIRUT) S PSOANS="N" G END
"RTN","PSOPRI",32,0)
IPR6 I PSOANS["Y",$G(PSOPTRX),'$G(PSOMHV) D IPR5 ;MARK PROCESSED NODES
"RTN","PSOPRI",33,0)
 D IPR3 I $G(PSOANS)="N" D ULK G END
"RTN","PSOPRI",34,0)
 ;I $P(X,"-")'=PSOINST W !?7,$C(7),$C(7),$C(7),"Not from this institution.",! D ULK G IPR6
"RTN","PSOPRI",35,0)
 S (PSOBBC("IRXN"),PSOBBC("OIRXN"))=$P(X,"-",2)
"RTN","PSOPRI",36,0)
 I $G(^PSRX(PSOBBC("IRXN"),0))']"" W !,$C(7),"Rx data is not on file!",! D ULK G IPR6
"RTN","PSOPRI",37,0)
 I $P($G(^PSRX(PSOBBC("IRXN"),"STA")),"^")=13 W !,$C(7),"Rx has already been deleted." D ULK G IPR6
"RTN","PSOPRI",38,0)
 I $G(PSOBBC("DONE"))[PSOBBC("IRXN")_"," W !,$C(7),"Rx has already been entered." D ULK G IPR6
"RTN","PSOPRI",39,0)
 K X,Y D:PSOBBC("QFLG") PROCESSX^PSOBBC
"RTN","PSOPRI",40,0)
 S PSOSELSE=0 I $G(PSODFN)'=$P(^PSRX(PSOBBC("IRXN"),0),"^",2) S PSOSELSE=1 D PT^PSOBBC I $G(PSOBBC("DFLG")) K PSOSELSE D ULK G IPR6
"RTN","PSOPRI",41,0)
 I '$G(PSOSELSE) D PTC^PSOBBC I $G(PSOBBC("DFLG")) K PSOSELSE D ULK G IPR6
"RTN","PSOPRI",42,0)
 K PSOSELSE D PROFILE^PSORX1
"RTN","PSOPRI",43,0)
 S PSOBBC("DONE")=PSOBBC("IRXN")_",",PSOMHV=0 D REFILL^PSOBBC D ULK G IPR6
"RTN","PSOPRI",44,0)
 Q
"RTN","PSOPRI",45,0)
IPR3 K PSOBBC("IRXN"),PSOXFLAG F  S PSOPTRX=$O(^PS(52.43,"AINST",PSOINST,PSOPTRX)) D  Q:PSOANS="N"!($G(PSOXFLAG))
"RTN","PSOPRI",46,0)
 .I PSOPTRX="" S PSOANS="N" Q
"RTN","PSOPRI",47,0)
 .S PSOIEN=$O(^PS(52.43,"AINST",PSOINST,PSOPTRX,""))
"RTN","PSOPRI",48,0)
 .I '$D(^PSRX(+PSOPTRX,0)),$P(^PS(52.43,PSOIEN,0),"^",5)="" S PSONOF=1 D IPR5 K PSONOF Q  ;SKIPS ERRONEOUS ENTRIES
"RTN","PSOPRI",49,0)
IPR4 .I PSOANS["Y" Q:$P(^PS(52.43,PSOIEN,0),"^",5)'=""  S X=PSOINST_"-"_PSOPTRX     ;SKIPS ENTRIES ALREADY PROCESSED AND FORMATS VARIABLE X
"RTN","PSOPRI",50,0)
IPR10 .I PSOANS2["S",$D(^PSRX(+PSOPTRX,0)),PSOSITE'=$P($G(^PSRX(+PSOPTRX,2)),"^",9) Q
"RTN","PSOPRI",51,0)
 .S PSOPSORX=+$G(PSOPTRX) I PSOPSORX D PSOL^PSSLOCK(PSOPSORX) I '$G(PSOMSG) K PSOPSORX,PSOMSG Q
"RTN","PSOPRI",52,0)
 .K PSOMSG S PSOXFLAG=1
"RTN","PSOPRI",53,0)
 Q
"RTN","PSOPRI",54,0)
 ;LINES CALLED TO MARK PROCESSED NODES
"RTN","PSOPRI",55,0)
IPR5 K DA,DR,DIE S DA=$O(^PS(52.43,"AINST",PSOINST,PSOPTRX,""))
"RTN","PSOPRI",56,0)
 S DIE="^PS(52.43,",DR="5////"_DT_";6///"_$S($G(PSOBBC("DFLG"))=1:"NOT FILLED",$G(PSONOF)=1:"NOT FILLED",1:"FILLED") D ^DIE ; MARKS NODE AS PROCESSED
"RTN","PSOPRI",57,0)
 K ^PS(52.43,"AINST",PSOINST,PSOPTRX,DA)
"RTN","PSOPRI",58,0)
 Q
"RTN","PSOPRI",59,0)
END D PROCESSX^PSOBBC
"RTN","PSOPRI",60,0)
 I $P($G(^PS(59,+$G(PSOSITE),"I")),"^"),DT>$P($G(^("I")),"^") D FINAL^PSOLSET W !!,"Your Outpatient Site parameters have been deleted because you selected an",!,"inactive Outpatient Site!",!
"RTN","PSOPRI",61,0)
 K DIR,PSOBBC,PSOBBC1,PSOVIN,PSOISITE,PSOVEXFL,PSOVXLP,PSOVEX,PSOVX,PSOVEXI,PSOANS,PSOANS2,PSOPTRX,PSOXFLAG,PSOPSORX,X,Y,PSODFN,PSOMHV
"RTN","PSOPRI",62,0)
 Q
"RTN","PSOPRI",63,0)
ULK ;
"RTN","PSOPRI",64,0)
 I '$G(PSOPSORX) Q
"RTN","PSOPRI",65,0)
 D PSOUL^PSSLOCK(PSOPSORX)
"RTN","PSOPRI",66,0)
 K PSOPSORX
"RTN","PSOPRI",67,0)
 Q
"RTN","PSORX1")
0^5^B59364372^B60587964
"RTN","PSORX1",1,0)
PSORX1 ;BIR/SAB-medication processing driver ;3/28/05 1:14pm
"RTN","PSORX1",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**7,22,23,57,62,46,74,71,90,95,115,117,146,139,135,182,195,233,268,300**;DEC 1997;Build 4
"RTN","PSORX1",3,0)
 ;External reference ^PS(55 supported by DBIA 2228
"RTN","PSORX1",4,0)
 ;External reference ^DIC(31 supported by DBIA 658
"RTN","PSORX1",5,0)
 ;External reference ^DPT(D0,.372 supported by DBIA 1476
"RTN","PSORX1",6,0)
 ;External reference DISPPRF^DGPFAPI supported by DBIA #4563
"RTN","PSORX1",7,0)
 ;External reference ^ORRDI1 is supported by DBIA 4659
"RTN","PSORX1",8,0)
 ;External reference ^XTMP("ORRDI" is supported by DBIA 4660
"RTN","PSORX1",9,0)
 ;
"RTN","PSORX1",10,0)
 ;PSO*195 add call to display Patient Record Flag (DISPPRF^DGPFAPI)
"RTN","PSORX1",11,0)
 ;
"RTN","PSORX1",12,0)
START K PSOQFLG,PSOID,PSOFIN,PSOQUIT,PSODRUG S (PSOBCK,PSOERR)=1 D INIT G:PSORX("QFLG") END
"RTN","PSORX1",13,0)
 D PT G:$G(PSORX("QFLG")) END D FULL^VALM1 I $G(NOPROC) K NOPROC G NX
"RTN","PSORX1",14,0)
 ;call to add bingo board data to file 52.11
"RTN","PSORX1",15,0)
 F SLPPL=0:0 S SLPPL=$O(RXRS(SLPPL)) Q:'SLPPL  D
"RTN","PSORX1",16,0)
 .I $P($G(^PSRX(SLPPL,"STA")),"^")'=5 K RXRS(SLPPL) Q
"RTN","PSORX1",17,0)
 .S RXREC=SLPPL D WIND^PSOSUPOE I $G(PBINGRTE) D BBADD^PSOSUPOE S (BINGCRT,BINGRTE)=1 S:$G(PSOFROM)'="NEW" PSOFROM="REFILL"
"RTN","PSORX1",18,0)
 K TM,TM1 I $G(PSORX("PSOL",1))]""!($D(RXRS)) D ^PSORXL K PSORX S PSOPBM1=1
"RTN","PSORX1",19,0)
 G:$G(NOBG) NX
"RTN","PSORX1",20,0)
 S TM=$P(^TMP("PSOBB",$J),"^"),TM1=$P(^TMP("PSOBB",$J),"^",2) K ^TMP("PSOBB",$J)
"RTN","PSORX1",21,0)
 I $G(PSOFROM)="NEW"!($G(PSOFROM)="REFILL")!($G(PSOFROM)="PARTIAL") D:$D(BINGCRT)&($D(BINGRTE)&($D(DISGROUP))) ^PSOBING1 K BINGCRT,BINGRTE,BBRX,BBFLG
"RTN","PSORX1",22,0)
 I $G(PSOPBM),$G(PSOPBM1) S $P(^PS(55,PSODFN,0),"^",7)=PSOPBM,$P(^(0),"^",8)="A" K PSOPBM,PSOPBM1
"RTN","PSORX1",23,0)
NX I $G(POERR("DEAD"))!$G(PSOQFLG) D EOJ G START
"RTN","PSORX1",24,0)
 D EOJ G START
"RTN","PSORX1",25,0)
END Q
"RTN","PSORX1",26,0)
 ;---------------------------------------------------------
"RTN","PSORX1",27,0)
INIT ;
"RTN","PSORX1",28,0)
 S PSORX("QFLG")=0
"RTN","PSORX1",29,0)
 D:'$D(PSOPAR) ^PSOLSET I '$D(PSOPAR) S PSORX("QFLG")=1
"RTN","PSORX1",30,0)
 I $P($G(PSOPAR),"^",2),'$D(^XUSEC("PSORPH",DUZ)) S PSORX("VERIFY")=1
"RTN","PSORX1",31,0)
INITX Q
"RTN","PSORX1",32,0)
 ;
"RTN","PSORX1",33,0)
PT ;
"RTN","PSORX1",34,0)
 K ^TMP("PSORXDC",$J),CLOZPAT,DIC,PSODFN,PSOPBM,PSOPBM1 S PSORX("QFLG")=0,DIC=2,DIC(0)="QEAM" D ^DIC K DIC,DA
"RTN","PSORX1",35,0)
 I +Y'>0 S PSORX("QFLG")=1 G PTX
"RTN","PSORX1",36,0)
OERR N:$G(MEDP) PAT,POERR K PSOXFLG S (DFN,PSODFN)=+Y,PSORX("NAME")=$P(Y,"^",2)
"RTN","PSORX1",37,0)
 K NPPROC,PSOQFLG,DIC,DR,DIQ S DIC=2,DA=PSODFN,DR=.351,DIQ="PSOPTPST" D EN^DIQ1 K DIC,DA,DR,DIQ D DEAD^PSOPTPST I $G(PSOQFLG) S NOPROC=1 Q
"RTN","PSORX1",38,0)
 ;PSO*195 move SSN write to here and add DISPPRF call
"RTN","PSORX1",39,0)
 S SSN=$P(^DPT(PSODFN,0),"^",9) W !!?10,$C(7),PSORX("NAME")
"RTN","PSORX1",40,0)
 W " ("_$E(SSN,1,3)_"-"_$E(SSN,4,5)_"-"_$E(SSN,6,9)_")" K SSN
"RTN","PSORX1",41,0)
 S PSONOAL="" D ALLERGY^PSOORUT2 D  I PSONOAL'="" D PAUSE
"RTN","PSORX1",42,0)
 .I PSONOAL'="" W !,$C(7),"     No Allergy Assessment!"
"RTN","PSORX1",43,0)
 D REMOTE
"RTN","PSORX1",44,0)
 N PSOUPDT
"RTN","PSORX1",45,0)
 S PSOUPDT=1
"RTN","PSORX1",46,0)
 I XQY0["PSO LMOE FINISH" S PSOUPDT=0
"RTN","PSORX1",47,0)
 D CHKADDR^PSOBAI(PSODFN,1,PSOUPDT)
"RTN","PSORX1",48,0)
 D:(XQY0["PSO LMOE FINISH")&('$G(SNGLPAT)) DISPPRF^DGPFAPI(PSODFN)
"RTN","PSORX1",49,0)
 ;
"RTN","PSORX1",50,0)
 I $P($G(^PS(55,PSODFN,"LAN")),"^") W !?10,"Patient has another language preference!",! H 3
"RTN","PSORX1",51,0)
 I $G(^PS(55,"ASTALK",PSODFN)) W !,"Patient is enrolled to receive ScripTalk 'talking' prescription labels.",! H 2 D MAIL
"RTN","PSORX1",52,0)
 D NOW^%DTC S TM=$E(%,1,12),TM1=$P(TM,".",2) S ^TMP("PSOBB",$J)=TM_"^"_TM1
"RTN","PSORX1",53,0)
 S PSOQFLG=0,DIC="^PS(55,",DLAYGO=55
"RTN","PSORX1",54,0)
 K PSOPBM ; KILL SO THAT WON'T CARRY OVER PRIOR PATIENT'S VALUE
"RTN","PSORX1",55,0)
 I '$D(^PS(55,PSODFN,0)) D
"RTN","PSORX1",56,0)
 .S PSOPBM=$P(TM,".")
"RTN","PSORX1",57,0)
 .K DD,DO S DIC(0)="L",(DINUM,X)=PSODFN D FILE^DICN D:Y<1  K DIC,DA,DR,DD,DO
"RTN","PSORX1",58,0)
 ..S $P(^PS(55,PSODFN,0),"^")=PSODFN K DIK S DA=PSODFN,DIK="^PS(55,",DIK(1)=.01 D EN^DIK K DIK
"RTN","PSORX1",59,0)
 D RXSTA
"RTN","PSORX1",60,0)
 S PSOLOUD=1 D:$P($G(^PS(55,PSODFN,0)),"^",6)'=2 EN^PSOHLUP(PSODFN) K PSOLOUD
"RTN","PSORX1",61,0)
 I $G(^PS(55,PSODFN,"PS"))']"" D  I $G(POERR("QFLG")) G EOJ
"RTN","PSORX1",62,0)
 .L +^PS(55,PSODFN):$S(+$G(^DD("DILOCKTM"))>0:+^DD("DILOCKTM"),1:3) I '$T W $C(7),!!,"Patient Data is Being Edited by Another User!",! S POERR("QFLG")=1 S:$G(PSOFIN) PSOQUIT=1 Q
"RTN","PSORX1",63,0)
 .S PSOXFLG=1,SSN=$P(^DPT(PSODFN,0),"^",9) W !!?10,$C(7),PSORX("NAME")_" ("_$E(SSN,1,3)_"-"_$E(SSN,4,5)_"-"_$E(SSN,6,9)_")",! K SSN
"RTN","PSORX1",64,0)
 .S DIE=55,DR=".02;.03;.04;.05;1;D ELIG^PSORX1;3;50;106;106.1",DA=PSODFN W !!,?5,">>PHARMACY PATIENT DATA<<",! D ^DIE L -^PS(55,PSODFN)
"RTN","PSORX1",65,0)
 S PSOX=$G(^PS(55,PSODFN,"PS")) I PSOX]"" S PSORX("PATIENT STATUS")=$P($G(^PS(53,PSOX,0)),"^")
"RTN","PSORX1",66,0)
 I $G(^PS(55,PSODFN,"PS"))']"" D  I $G(POERR("QFLG")) G EOJ
"RTN","PSORX1",67,0)
 .W !!,"Patient Status Required!!",! D ELIG
"RTN","PSORX1",68,0)
 .W ! K POERR("QFLG"),DIC,DR,DIE S DIC("A")="RX PATIENT STATUS: ",DIC(0)="QEAMZ",DIC=53 D ^DIC K DIC
"RTN","PSORX1",69,0)
 .I $D(DIRUT)!(Y=-1) D  Q
"RTN","PSORX1",70,0)
 ..W $C(7),"Required Data!",! S POERR("QFLG")=1 S:$G(PSOFIN) PSOQUIT=1
"RTN","PSORX1",71,0)
 ..I $G(PSOPBM) D  K PSOPBM
"RTN","PSORX1",72,0)
 ...I $O(^PS(55,PSODFN,0))="" S DA=PSODFN,DIK="^PS(55," D ^DIK
"RTN","PSORX1",73,0)
 .S ^PS(55,PSODFN,"PS")=+Y,PSORX("PATIENT STATUS")=$P(^PS(53,+Y,0),"^")
"RTN","PSORX1",74,0)
 .K DIRUT,DTOUT,DUOUT,X,Y,DA
"RTN","PSORX1",75,0)
 Q:$G(PSOFIN)
"RTN","PSORX1",76,0)
 I '$G(PSOPBM),'$P(^PS(55,PSODFN,0),"^",7),$P(^(0),"^",8)']"" S PSOPBM=$P(TM,".")
"RTN","PSORX1",77,0)
 D ^PSOBUILD
"RTN","PSORX1",78,0)
 F PT="GET","DEAD","INP","CNH","TPB","ADDRESS","COPAY" S RTN=PT_"^PSOPTPST" D @RTN Q:$G(POERR("DEAD"))!($G(PSOQFLG))
"RTN","PSORX1",79,0)
 I $G(POERR("DEAD")) S POERR("QFLG")=1 F II=0:0 S II=$O(^PS(52.41,"P",PSODFN,II)) D:$P($G(^PS(52.41,II,0)),"^",3)'="DC"&($P($G(^(0)),"^",3)'="DE") DC^PSOORFI2
"RTN","PSORX1",80,0)
 K PSOERR("DEAD"),II I $G(PSOQFLG) S POERR("QFLG")=1 G EOJ Q
"RTN","PSORX1",81,0)
 S (PAT,PSOXXDFN)=PSODFN,POERR=1 D ^PSOORUT2,BLD^PSOORUT1,EN^PSOLMUTL
"RTN","PSORX1",82,0)
 D CLEAR^VALM1 G:$G(PSOQUIT) PTX D EN^PSOLMAO
"RTN","PSORX1",83,0)
 S (DFN,PSODFN)=PSOXXDFN K DIE,DIC,DLAYGO,DR,DA,PSOX,PSORXED
"RTN","PSORX1",84,0)
PTX ;
"RTN","PSORX1",85,0)
 K X,Y,^TMP("PS",$J),C,DEA,PRC,PSCNT,PSOACT,PSOCLC,PSOCS,PSOCT,PSOFINFL,PSOHD,PSOLST,PSOOPT,PSOPF,PSOX,PSOX1,PSOXXDFN,SIGOK,STP,STR
"RTN","PSORX1",86,0)
 Q
"RTN","PSORX1",87,0)
EOJ ;
"RTN","PSORX1",88,0)
 K PSOERR,PSOMED,PSORX,PSOSD,PSODRUG,PSODFN,PSOOPT,PSOBILL,PSOIBQS,PSOCPAY,PSOPF,PSOPI,COMM,DGI,DGS,PT,PTDY,PTRF,RN,RTN,SERS,ST0,STAT,DFN,STOP,SLPPL,RXREC,PSOPBM
"RTN","PSORX1",89,0)
 K:'$G(MEDP) PSOQFLG
"RTN","PSORX1",90,0)
 D KVA^VADPT,FULL^VALM1 K PSOLST,PSOXFLG,PSCNT,PSDIS,PSOAL,P1,LOG,%,%DT,%I,D0,DAT,DFN,DRG,ORX,PSON,PSOPTPST,PSORX,PTST,PSOBCK,PSOID,PSOBXPUL
"RTN","PSORX1",91,0)
 K INCOM,SIG,SG,STP,RX0,RXN,RX2,RX3,RTS,C,DEAD,PS,PSOCLC,PSOCNT,PSOCT,PSODA,PSOFROM,PSOHD,R3,REA,RF,RFD,RFM,RLD,RXNUM,RXP,RXPR,RXRP,RXRS,STR,POERR,VALMSG
"RTN","PSORX1",92,0)
 K ^TMP("PSORXDC",$J),^TMP("PSOAL",$J),^TMP("PSOAO",$J),^TMP("PSOSF",$J),^TMP("PSOPF",$J),^TMP("PSOPI",$J),^TMP("PSOPO",$J),^TMP("PSOHDR",$J) I '$G(MEDP),'$G(PSOQUIT) K PAT
"RTN","PSORX1",93,0)
 K PSORX,RFN,PSOXXDFN,VALM,VALMKEY,PSOBCK,SPOERR,PSOFLAG,VALMBCK,D,GMRA,GMRAL,GMRAREC,PSOSTA,PSODT,RXFL,NOBG,BBRX,BBFLG
"RTN","PSORX1",94,0)
 Q
"RTN","PSORX1",95,0)
ELIG ; shows eligibility and disabilities
"RTN","PSORX1",96,0)
 D ELIG^VADPT W !,"Eligibility: "_$P(VAEL(1),"^",2)_$S(+VAEL(3):"     SC%: "_$P(VAEL(3),"^",2),1:"") S N=0 F  S N=$O(VAEL(1,N)) Q:'N  W !,?10,$P(VAEL(1,N),"^",2)
"RTN","PSORX1",97,0)
 W !,"Disabilities: " F I=0:0 S I=$O(^DPT(DFN,.372,I)) Q:'I  S I1=$S($D(^DPT(DFN,.372,I,0)):^(0),1:"") D:+I1
"RTN","PSORX1",98,0)
 .S PSDIS=$S($P($G(^DIC(31,+I1,0)),"^")]""&($P($G(^(0)),"^",4)']""):$P(^(0),"^"),$P($G(^DIC(31,+I1,0)),"^",4)]"":$P(^(0),"^",4),1:""),PSCNT=$P(I1,"^",2)
"RTN","PSORX1",99,0)
 .W:$L(PSDIS_"-"_PSCNT_"% ("_$S($P(I1,"^",3):"SC",1:"NSC")_"), ")>80 !,?15
"RTN","PSORX1",100,0)
 .W $S($G(PSDIS)]"":PSDIS_"-",1:"")_PSCNT_"% ("_$S($P(I1,"^",3):"SC",1:"NSC")_"), "
"RTN","PSORX1",101,0)
 K N
"RTN","PSORX1",102,0)
 Q
"RTN","PSORX1",103,0)
PROFILE ;
"RTN","PSORX1",104,0)
 S (PSORX("REFILL"),PSORX("RENEW"))=0,PSOX="" D ^PSOBUILD
"RTN","PSORX1",105,0)
 I '$G(PSOSD) W !,"This patient has no prescriptions" S:'$D(DFN) DFN=PSODFN D GMRA^PSODEM G PROFILEX
"RTN","PSORX1",106,0)
 S (PSODRG,PSOX)="" F  S PSODRG=$O(PSOSD(PSODRG)) Q:PSODRG=""  F  S PSOX=$O(PSOSD(PSODRG,PSOX)) Q:PSOX=""  S:$P(PSOSD(PSODRG,PSOX),"^",3)="" PSORX("RENEW")=1 S:$P(PSOSD(PSODRG,PSOX),"^",4)="" PSORX("REFILL")=1
"RTN","PSORX1",107,0)
 K PSOX
"RTN","PSORX1",108,0)
PROFILEX Q
"RTN","PSORX1",109,0)
 ;
"RTN","PSORX1",110,0)
MAIL ; MAKE SURE MAIL STATUS IS COMPATIBLE WITH SCRIPTALK PATIENT
"RTN","PSORX1",111,0)
 I $P($G(^PS(59,PSOSITE,"STALK")),"^")="" Q  ; NO SCRIPTALK PRINTER SET UP FOR THIS DIVISION
"RTN","PSORX1",112,0)
 N MAIL
"RTN","PSORX1",113,0)
 S MAIL=$G(^PS(55,PSODFN,0)) I $P(MAIL,"^",3)>1 Q
"RTN","PSORX1",114,0)
MAILP W !!,"REMINDER: CMOP does not fill ScripTalk prescriptions.Please select mail"
"RTN","PSORX1",115,0)
 W !,"status:  2 (DO NOT MAIL), 3 (LOCAL REGULAR MAIL) or 4 (LOCAL CERTFIED MAIL)."
"RTN","PSORX1",116,0)
 R !,"MAIL: ",MAIL:120
"RTN","PSORX1",117,0)
 I MAIL?1"^".E Q
"RTN","PSORX1",118,0)
 I MAIL<2!(MAIL>4) W !,"INVALID MAIL SETTING - ENTER 2,3, OR 4" G MAILP
"RTN","PSORX1",119,0)
 W "  ",$S(MAIL=2:"DO NOT MAIL",MAIL=3:"LOCAL REGULAR MAIL",1:"LOCAL CERTIFIED MAIL")
"RTN","PSORX1",120,0)
 S $P(^PS(55,PSODFN,0),"^",3)=MAIL
"RTN","PSORX1",121,0)
 Q
"RTN","PSORX1",122,0)
REMOTE ; 
"RTN","PSORX1",123,0)
 I $T(HAVEHDR^ORRDI1)']"" Q
"RTN","PSORX1",124,0)
 I '$$HAVEHDR^ORRDI1 Q
"RTN","PSORX1",125,0)
 I $D(^XTMP("ORRDI","OUTAGE INFO","DOWN")) W !,"Remote data not available - Only local order checks processed." D  Q
"RTN","PSORX1",126,0)
 .K DIR W ! S DIR(0)="EA",DIR("A")="Press Return to continue..." D ^DIR W ! K DIR
"RTN","PSORX1",127,0)
 Q
"RTN","PSORX1",128,0)
PAUSE ;
"RTN","PSORX1",129,0)
 W ! K DIR S DIR(0)="E",DIR("A")="Press Return to continue" D ^DIR K DIR
"RTN","PSORX1",130,0)
 Q
"RTN","PSORX1",131,0)
 ;
"RTN","PSORX1",132,0)
RXSTA ; DISPLAY ELIGIBILITY & PROMPT FOR RX PATIENT STATUS
"RTN","PSORX1",133,0)
 N DA,PSOSTA
"RTN","PSORX1",134,0)
 I '$G(PSODFN) Q
"RTN","PSORX1",135,0)
 S DA=PSODFN,PSOSTA=$G(^PS(55,PSODFN,"PS"))
"RTN","PSORX1",136,0)
 I XQY0["PSO LMOE FINISH"!(XQY0["PSO LM BACKDOOR ORDERS") I PSOSTA]"" D
"RTN","PSORX1",137,0)
 .D ELIG^VADPT W !,"Eligibility: "_$P(VAEL(1),"^",2)_$S(+VAEL(3):"     SC%: "_$P(VAEL(3),"^",2),1:"")
"RTN","PSORX1",138,0)
 .S N=0 F  S N=$O(VAEL(1,N)) Q:'N  W !,?10,$P(VAEL(1,N),"^",2)
"RTN","PSORX1",139,0)
 .S DIC("A")="RX PATIENT STATUS: ",DIC("B")=PSOSTA,DIC(0)="QEAMZ",DIC=53 D ^DIC K DIC
"RTN","PSORX1",140,0)
 .I +Y>0,+Y'=PSOSTA S DIE="^PS(55,",DR="3////"_+Y D ^DIE
"RTN","PSORX1",141,0)
 Q
"RTN","PSOSD")
0^6^B31217592^B32487567
"RTN","PSOSD",1,0)
PSOSD ;BHAM ISC/SAB - action or informational profile ;11/18/92 18:30
"RTN","PSOSD",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**2,17,155,176,300**;DEC 1997;Build 4
"RTN","PSOSD",3,0)
 ;External reference to ^PS(55 supported by DBIA 2228
"RTN","PSOSD",4,0)
 ;External reference to ^PSDRUG( supported by DBIA 221
"RTN","PSOSD",5,0)
 ;
"RTN","PSOSD",6,0)
START S X=$$SITE^VASITE,PSOINST=$P(X,"^",3) K X
"RTN","PSOSD",7,0)
 K IOP,DIR S DIR("A")="Action or Informational (A or I): ",DIR("?",1)="Enter 'A' for action profile",DIR("?",2)="      'I' for informational profile",DIR("?")="      'E' to EXIT process",DIR("B")="A",DIR(0)="SAM^1:Action;0:Informational;E:Exit"
"RTN","PSOSD",8,0)
 D ^DIR G:Y="E"!($D(DIRUT)) PAT1 S PSTYPE=Y
"RTN","PSOSD",9,0)
 S PSONUM=0 I 'PSTYPE!'$P($G(PSOSYS),"^",6) S PSOPOL=0 G ASK
"RTN","PSOSD",10,0)
 K DIR S DIR("A")="Do you want generate a Polypharmacy report?: ",DIR("?",1)="Enter 'Y' to generate report",DIR("?",2)="      'N' if you do not want the report",DIR("?")="      'E' to EXIT process",DIR("B")="NO",DIR(0)="SA^1:YES;0:NO;E:Exit"
"RTN","PSOSD",11,0)
 D ^DIR S PSOPOL=$S(Y:1,1:0) G:Y="E"!($D(DIRUT)) PAT1 G:'PSOPOL ASK
"RTN","PSOSD",12,0)
 K DIR S DIR("A")="Minimum Number of Active Prescriptions",DIR("B")=7,DIR(0)="N^1:100:0" D ^DIR S PSONUM=Y G:$D(DIRUT) PAT1
"RTN","PSOSD",13,0)
 ;
"RTN","PSOSD",14,0)
ASK K DIR S DIR("A")="By Patient, Clinic or Clinic Group (P/C/G): ",DIR("?",1)="Enter 'P' to print by patient ",DIR("?",2)="      'C' for printing by clinic",DIR("?",3)="      'G' for printing by clinic group"
"RTN","PSOSD",15,0)
 S DIR("?")="      'E' to exit process",DIR("B")="P",DIR(0)="SAM^P:Patient;C:Clinic;G:Clinic Group;E:Exit"
"RTN","PSOSD",16,0)
 D ^DIR G:Y="E"!($D(DIRUT)) PAT1 S PSOUT=Y
"RTN","PSOSD",17,0)
 K DIR,DTOUT,DIRUT,DUOUT S DIR("A")="Do you want this Profile to print in 80 column or 132 column: ",DIR("B")="132",DIR(0)="SAM^1:132;8:80;E:Exit"
"RTN","PSOSD",18,0)
 D ^DIR G:Y="E"!($D(DIRUT)) PAT1 S PSORM=$S(Y=1:1,1:0) K DIR,X,Y
"RTN","PSOSD",19,0)
 G:PSOUT="P" ^PSOSD1 G:PSOUT="G" CLSG^PSOSDP
"RTN","PSOSD",20,0)
CLINIC N RSLT K DIR,X,Y R !!,"FOR CLINIC (TYPE 'ALL' FOR ALL CLINICS): ",X:DTIME S:'$T X="^" G:"^"[X EXIT
"RTN","PSOSD",21,0)
 S DIC="^SC(",DIC(0)="QEM",FR="ALL",TO="" I X'="ALL" D ^DIC G CLINIC:Y<0 S (FR,TO)=+Y
"RTN","PSOSD",22,0)
 S %DT="AEFX",%DT("A")="FOR DATE: " D ^%DT G CLINIC:Y<0 S FR=FR_","_Y,TO=TO_","_Y_".2359",PSOT=Y
"RTN","PSOSD",23,0)
CLSG D DAYS^PSOSD1 G:$D(DIRUT) EXIT S X1=DT,X2=-PSDAYS D C^%DTC S PSDATE=X S PSTYPE=$S($D(PSTYPE):PSTYPE,1:0),$P(LINE,"-",132)="-"
"RTN","PSOSD",24,0)
 N PSOBARS,PSOBAR0,PSOBAR1
"RTN","PSOSD",25,0)
 D DEV^PSOSDRAP Q:$D(DTOUT)!($D(DUOUT))
"RTN","PSOSD",26,0)
 S (IOP,APRT)=ION,PSOIOS=IOS D DEVBAR^PSOBMST
"RTN","PSOSD",27,0)
 K PSOION I $D(IO("Q")) S ZTDESC="Outpatient Pharmacy Action Profile",ZTRTN="QUE^PSOSD",ZTSAVE("ZTREQ")="@" D  D EXIT G START
"RTN","PSOSD",28,0)
 .F G="FR","TO","LINE","PSOT","APRT","PSOPOL","PSOSYS","PSOINST","PSOBAR0","PSOBAR1","PSOBAR2","PSOPAR","PSOPAR7","PRF","PSDAYS","PSDATE","PSTYPE","PSOSITE","PSDATE","PSDAY","PSONUM","PSORM" S:$D(@G) ZTSAVE(G)=""
"RTN","PSOSD",29,0)
 .S ZTSAVE("DOD*")="" D ^%ZTLOAD W:$D(ZTSK) !,"Report Queued to Print !!",! K:'$G(LM) ZTSK,IO("Q")
"RTN","PSOSD",30,0)
 ;S DISTOP="I $D(DIRUT)"
"RTN","PSOSD",31,0)
 I $P(FR,",",1)'="ALL" D CLINIC^PSOSDRAP
"RTN","PSOSD",32,0)
 I $P(FR,",",1)="ALL" D CLINALL^PSOSDRAP
"RTN","PSOSD",33,0)
 S (X,PSTY)=PSTYPE D EXIT S PSTYPE=PSTY Q:$G(CLSP)  G START
"RTN","PSOSD",34,0)
 ;
"RTN","PSOSD",35,0)
PAT N K D:$P($G(^PS(55,DFN,0)),"^",6)'=2 EN^PSOHLUP(DFN)
"RTN","PSOSD",36,0)
 S PSDT=PSDATE-1 I '$O(^PS(55,DFN,"P","A",PSDT)) D HD^PSOSD2 Q:$D(DIRUT)  W !!?13,">>>> NO PRESCRIPTIONS ON FILE <<<<" G PAT1
"RTN","PSOSD",37,0)
 K ^TMP($J,DFN),^TMP($J,"PRF"),^TMP($J,"ACT")
"RTN","PSOSD",38,0)
 F Z1=0:0 S PSDT=$O(^PS(55,DFN,"P","A",PSDT)) Q:'PSDT  D RX
"RTN","PSOSD",39,0)
 I '$D(^TMP($J,"PRF")) D HD^PSOSD2 W !!?13,">>>>> NO CURRENT PRESCRIPTIONS DATA FOUND <<<<<" D PAT1 Q
"RTN","PSOSD",40,0)
 D ^PSOSDP:$G(PSOPOL)&('$D(CLINICX))
"RTN","PSOSD",41,0)
 D HD^PSOSD2:'$D(CLINICX)
"RTN","PSOSD",42,0)
 D ^PSOSD0,PAT1 Q:($D(DIRUT))
"RTN","PSOSD",43,0)
 Q
"RTN","PSOSD",44,0)
RX F J=0:0 S J=$O(^PS(55,DFN,"P","A",PSDT,J)) Q:'J  D RX1
"RTN","PSOSD",45,0)
 Q
"RTN","PSOSD",46,0)
RX1 Q:'$D(^PSRX(J,0))  S RXNO=J
"RTN","PSOSD",47,0)
 S RX0=$G(^PSRX(J,0)),$P(RX0,"^",15)=+$G(^("STA")),RX2=$G(^(2)),RX3=$G(^(3)) I RX0]"" D
"RTN","PSOSD",48,0)
 .S DRUG="" S:$D(^PSDRUG(+$P(RX0,"^",6),0)) DRUG=$P(^(0),"^"),CLASS=$P(^(0),"^",2) S:CLASS="" CLASS="zz" I DRUG]"" D STAT^PSOFUNC,STORE
"RTN","PSOSD",49,0)
 .I $G(PSOPOL),$P($G(^PSDRUG(+$P(RX0,"^",6),0)),"^",3)'["S" S:'$D(^TMP($J,DFN)) ^TMP($J,DFN)=0 S:"05"[$E(+$P(RX0,"^",15)) ^TMP($J,DFN)=^TMP($J,DFN)+1,^TMP($J,DFN,DRUG,J)=""
"RTN","PSOSD",50,0)
 Q
"RTN","PSOSD",51,0)
PAT1 K DUPD,DIR,X,Y,CLASS,ZCLASS,DRUG,CLAPP,HDFL,RXN,PSDOB,ADDR,RX,ST,ST0,II,FA,FN,PRI,DIC,PSRENW,PSLC,PI,Z2,Z,P,Z0,Z1,Z3,Z4,Z5,FDATE,AL,RFL,DRG,ELN,FDT,FILLDATE,FN,LN,PSOIFSUP,PSOPRPAS,RX3,RXCNT,SG,SGC,PSOUT,PSOPOLP
"RTN","PSOSD",52,0)
 Q
"RTN","PSOSD",53,0)
 ;
"RTN","PSOSD",54,0)
STORE I $P(^PSRX(J,"STA"),"^")=13!($P($G(^(3)),"^",7)="CANCELLED FROM SUSPENSE BEFORE FILLING")!($P($G(^(3)),"^",7)="DISCONTINUED FROM SUSPENSE BEFORE FILLING") Q
"RTN","PSOSD",55,0)
 I 'PSDAYS,ST]"","DE"[$E(ST) Q
"RTN","PSOSD",56,0)
 S FILLDATE=9999999-$P(^PSRX(J,3),"^") I "DE"[$E(ST) S FILLDATE=FILLDATE+10000
"RTN","PSOSD",57,0)
 I $E(ST)="D" S CNDT=0 F PSIIX=0:0 S PSIIX=$O(^PSRX(J,"A",PSIIX)) Q:'PSIIX  I $P($G(^(0)),"^",2)="C",+$P(^(0),"^")>CNDT S CNDT=+$P(^(0),"^")
"RTN","PSOSD",58,0)
 Q:"AHPSDE"'[$E(ST)  S ^TMP($J,"PRF",CLASS,DRUG,FILLDATE,J)=$P(RX0,"^",1,14)_"^"_ST_"^"_$S($D(CNDT):CNDT,1:"") S:"AHPS"[$E(ST) ^TMP($J,"ACT",CLASS,DRUG)=""
"RTN","PSOSD",59,0)
 K CNDT Q
"RTN","PSOSD",60,0)
 ;
"RTN","PSOSD",61,0)
EXIT K ^TMP($J,"PRF"),^("ACT"),PSOT,%DT,ADDR,ADDRFL,BY,CLASS,PCLASS,CLDT
"RTN","PSOSD",62,0)
 K CLINICX,CNDT,DFN,DHD,DRUG,FLDS,FR,CLAPP,HDFL,I,II,J,L,LINE,P,POP,PSDATE
"RTN","PSOSD",63,0)
 K PSDAYS,PSDOB,PSIIX,PSNAME,PSSN,PSTYPE,RX,RX0,RX2,RX3,RXN,ST,ST0,TO,VAR,Z1
"RTN","PSOSD",64,0)
 K APRT,DIE,DR,X,Y,DIC,ZTSAVE,PSORM,PSOUT,PSOPOLP,G,LM,PSDT,ZTDESC,ZTRTN,ZTSK
"RTN","PSOSD",65,0)
 K PSOIOS,PSONUM,PSOPOL,RXNO,X1,X2,RSLT,DIR,DIRUT,DTOUT,DUOUT
"RTN","PSOSD",66,0)
 K CS,DOD,GMRVSTR,PAGE,PSOBAR2,PSOBAR3,PSOBAR4,VA,VADM,VAPA,VAIN
"RTN","PSOSD",67,0)
 D ^%ZISC
"RTN","PSOSD",68,0)
 Q
"RTN","PSOSD",69,0)
ACT ;
"RTN","PSOSD",70,0)
 S PSTYPE=1 G START
"RTN","PSOSD",71,0)
INFO ;
"RTN","PSOSD",72,0)
 S PSTYPE=0 G START
"RTN","PSOSD",73,0)
 ;
"RTN","PSOSD",74,0)
QUE ;prints clinics when queued
"RTN","PSOSD",75,0)
 I $P(FR,",",1)'="ALL" D CLINIC^PSOSDRAP
"RTN","PSOSD",76,0)
 I $P(FR,",",1)="ALL" D CLINALL^PSOSDRAP
"RTN","PSOSD",77,0)
 D EXIT
"RTN","PSOSD",78,0)
 Q
"RTN","PSOTPRX1")
0^7^B51097782^B52223271
"RTN","PSOTPRX1",1,0)
PSOTPRX1 ;BIR/MHA-TPB medication procesing driver ;08/21/03
"RTN","PSOTPRX1",2,0)
 ;;7.0;OUTPATIENT PHARMACY;**146,182,227,268,300**;DEC 1997;Build 4
"RTN","PSOTPRX1",3,0)
 ;External reference ^PS(55 supported by DBIA 2228
"RTN","PSOTPRX1",4,0)
 ;External reference ^DIC(31 supported by DBIA 658
"RTN","PSOTPRX1",5,0)
 ;External reference EN2^GMRAPEM0 supported by DBIA 190
"RTN","PSOTPRX1",6,0)
 Q  ;placed out of order by patch PSO*7*227
"RTN","PSOTPRX1",7,0)
START K PSOQFLG,PSOID,PSOFIN,PSOQUIT,PSODRUG S (PSOBCK,PSOERR)=1 D INIT
"RTN","PSOTPRX1",8,0)
 W:'$D(PSOTPBFG) !!,"*** Transitional Pharmacy Benefit Flag Undefined - Quitting ***"
"RTN","PSOTPRX1",9,0)
 G:PSORX("QFLG")!('$D(PSOTPBFG)) END
"RTN","PSOTPRX1",10,0)
 D PT G:$G(PSORX("QFLG")) END D FULL^VALM1 I $G(NOPROC) K NOPROC G NX
"RTN","PSOTPRX1",11,0)
 ;call to add bingo board data to file 52.11
"RTN","PSOTPRX1",12,0)
 F SLPPL=0:0 S SLPPL=$O(RXRS(SLPPL)) Q:'SLPPL  D
"RTN","PSOTPRX1",13,0)
 .I $P($G(^PSRX(SLPPL,"STA")),"^")'=5 K RXRS(SLPPL) Q
"RTN","PSOTPRX1",14,0)
 .S RXREC=SLPPL D WIND^PSOSUPOE I $G(PBINGRTE) D BBADD^PSOSUPOE S (BINGCRT,BINGRTE)=1 S:$G(PSOFROM)'="NEW" PSOFROM="REFILL"
"RTN","PSOTPRX1",15,0)
 K TM,TM1 I $G(PSORX("PSOL",1))]""!($D(RXRS)) D ^PSORXL K PSORX S PSOPBM1=1
"RTN","PSOTPRX1",16,0)
 G:$G(NOBG) NX
"RTN","PSOTPRX1",17,0)
 S TM=$P(^TMP("PSOBB",$J),"^"),TM1=$P(^TMP("PSOBB",$J),"^",2) K ^TMP("PSOBB",$J)
"RTN","PSOTPRX1",18,0)
 I $G(PSOFROM)="NEW"!($G(PSOFROM)="REFILL")!($G(PSOFROM)="PARTIAL") D:$D(BINGCRT)&($D(BINGRTE)&($D(DISGROUP))) ^PSOBING1 K BINGCRT,BINGRTE,BBRX,BBFLG
"RTN","PSOTPRX1",19,0)
 I $G(PSOPBM),$G(PSOPBM1) S $P(^PS(55,PSODFN,0),"^",7)=PSOPBM,$P(^(0),"^",8)="A" K PSOPBM,PSOPBM1
"RTN","PSOTPRX1",20,0)
NX D:$G(PSODFN) EXFLAG^PSOTPCAN(PSODFN) D EOJ G START
"RTN","PSOTPRX1",21,0)
END Q
"RTN","PSOTPRX1",22,0)
 ;---------------------------------------------------------
"RTN","PSOTPRX1",23,0)
INIT ;
"RTN","PSOTPRX1",24,0)
 S PSORX("QFLG")=0
"RTN","PSOTPRX1",25,0)
 D:'$D(PSOPAR) ^PSOLSET I '$D(PSOPAR) S PSORX("QFLG")=1
"RTN","PSOTPRX1",26,0)
 I $P($G(PSOPAR),"^",2),'$D(^XUSEC("PSORPH",DUZ)) S PSORX("VERIFY")=1
"RTN","PSOTPRX1",27,0)
INITX Q
"RTN","PSOTPRX1",28,0)
 ;
"RTN","PSOTPRX1",29,0)
PT ;
"RTN","PSOTPRX1",30,0)
 K ^TMP("PSORXDC",$J),CLOZPAT,DIC,PSODFN,PSOPBM,PSOPBM1 S PSORX("QFLG")=0
"RTN","PSOTPRX1",31,0)
 S DIC("S")="I '$P(^PS(52.91,+Y,0),""^"",3)!($P(^(0),""^"",3)>DT)"
"RTN","PSOTPRX1",32,0)
 S DIC=52.91,DIC(0)="QEAM" D ^DIC K DIC,DA
"RTN","PSOTPRX1",33,0)
 I +Y'>0 S PSORX("QFLG")=1 G PTX
"RTN","PSOTPRX1",34,0)
OERR N:$G(MEDP) PAT,POERR K PSOXFLG S (DFN,PSODFN)=+Y,PSORX("NAME")=$P($G(^DPT(PSODFN,0)),"^")
"RTN","PSOTPRX1",35,0)
 K NPPROC,PSOQFLG,DIC,DR,DIQ S DIC=2,DA=PSODFN,DR=.351,DIQ="PSOPTPST" D EN^DIQ1 K DIC,DA,DR,DIQ D DEAD^PSOPTPST I $G(PSOQFLG) S NOPROC=1 Q
"RTN","PSOTPRX1",36,0)
 I $P($G(^PS(55,PSODFN,"LAN")),"^") W !,"Patient has another language preference!",! H 3
"RTN","PSOTPRX1",37,0)
 D NOW^%DTC S TM=$E(%,1,12),TM1=$P(TM,".",2) S ^TMP("PSOBB",$J)=TM_"^"_TM1
"RTN","PSOTPRX1",38,0)
 S PSOQFLG=0,DIC="^PS(55,",DLAYGO=55
"RTN","PSOTPRX1",39,0)
 I $G(PSOFIN) S SSN=$P(^DPT(PSODFN,0),"^",9) W !!?10,$C(7),PSORX("NAME")_" ("_$E(SSN,1,3)_"-"_$E(SSN,4,5)_"-"_$E(SSN,6,9)_")" K SSN
"RTN","PSOTPRX1",40,0)
 K PSOPBM ; KILL SO THAT WON'T CARRY OVER PRIOR PATIENT'S VALUE
"RTN","PSOTPRX1",41,0)
 I '$D(^PS(55,PSODFN,0)) D
"RTN","PSOTPRX1",42,0)
 .S PSOPBM=$P(TM,".")
"RTN","PSOTPRX1",43,0)
 .K DD,DO S DIC(0)="L",(DINUM,X)=PSODFN D FILE^DICN D:Y<1  K DIC,DA,DR,DD,DO
"RTN","PSOTPRX1",44,0)
 ..S $P(^PS(55,PSODFN,0),"^")=PSODFN K DIK S DA=PSODFN,DIK="^PS(55,",DIK(1)=.01 D EN^DIK K DIK
"RTN","PSOTPRX1",45,0)
 S PSOLOUD=1 D:$P($G(^PS(55,PSODFN,0)),"^",6)'=2 EN^PSOHLUP(PSODFN) K PSOLOUD
"RTN","PSOTPRX1",46,0)
 I $G(^PS(55,PSODFN,"PS"))']"" D  I $G(POERR("QFLG")) G EOJ
"RTN","PSOTPRX1",47,0)
 .L +^PS(55,PSODFN):$S(+$G(^DD("DILOCKTM"))>0:+^DD("DILOCKTM"),1:3) I '$T W $C(7),!!,"Patient Data is Being Edited by Another User!",! S POERR("QFLG")=1 S:$G(PSOFIN) PSOQUIT=1 Q
"RTN","PSOTPRX1",48,0)
 .S PSOXFLG=1,SSN=$P(^DPT(PSODFN,0),"^",9) W !!?10,$C(7),PSORX("NAME")_" ("_$E(SSN,1,3)_"-"_$E(SSN,4,5)_"-"_$E(SSN,6,9)_")",! K SSN
"RTN","PSOTPRX1",49,0)
 .S DIE=55,DR=".02;.03;.04;.05;1;D ELIG^PSORX1;@1;3//NON-VA;D CHK^PSOTPRX1;50;106;106.1"
"RTN","PSOTPRX1",50,0)
 .S DA=PSODFN W !!,?5,">>PHARMACY PATIENT DATA<<",! D ^DIE L -^PS(55,PSODFN)
"RTN","PSOTPRX1",51,0)
 .I $D(Y)!($D(DTOUT)) S PSOX=$G(^PS(55,PSODFN,"PS")) D:+$P(PSOX,"^")
"RTN","PSOTPRX1",52,0)
 ..I $$UP^XLFSTR($P(^PS(53,$P(PSOX,"^"),0),"^"))'="NON-VA" S DR="3////@" D ^DIE
"RTN","PSOTPRX1",53,0)
 S PSOX=$G(^PS(55,PSODFN,"PS"))
"RTN","PSOTPRX1",54,0)
 I PSOX]"" S (X,PSORX("PATIENT STATUS"))=$$UP^XLFSTR($P(^PS(53,$P(PSOX,"^"),0),"^")) D:X'="NON-VA" WRN
"RTN","PSOTPRX1",55,0)
 I PSOX']"" D  I $G(POERR("QFLG")) G EOJ
"RTN","PSOTPRX1",56,0)
 .W !!,"Patient Status Required!!",! D ELIG
"RTN","PSOTPRX1",57,0)
 .W ! K POERR("QFLG"),DIC,DR,DIE S DIC("B")="NON-VA"
"RTN","PSOTPRX1",58,0)
 .S DIC("A")="PATIENT STATUS: ",DIC(0)="QEAMZ",DIC=53 D ^DIC K DIC
"RTN","PSOTPRX1",59,0)
 .I $D(DIRUT)!(Y=-1) D  Q
"RTN","PSOTPRX1",60,0)
 ..W $C(7),"Required Data!",! S POERR("QFLG")=1 S:$G(PSOFIN) PSOQUIT=1
"RTN","PSOTPRX1",61,0)
 ..I $G(PSOPBM) D  K PSOPBM
"RTN","PSOTPRX1",62,0)
 ...I $O(^PS(55,PSODFN,0))="" S DA=PSODFN,DIK="^PS(55," D ^DIK
"RTN","PSOTPRX1",63,0)
 .I $$UP^XLFSTR($P(^PS(53,+Y,0),"^"))'="NON-VA" D MES S POERR("QFLG")=1 Q
"RTN","PSOTPRX1",64,0)
 .S ^PS(55,PSODFN,"PS")=+Y,PSORX("PATIENT STATUS")=$P(^PS(53,+Y,0),"^")
"RTN","PSOTPRX1",65,0)
 .D KV
"RTN","PSOTPRX1",66,0)
 Q:$G(PSOFIN)
"RTN","PSOTPRX1",67,0)
PROV ;
"RTN","PSOTPRX1",68,0)
 D ST^PSOTPPRV G:'$G(DA) NX
"RTN","PSOTPRX1",69,0)
 S PSORX("PROVIDER NAME")=$P(^VA(200,DA,0),"^")
"RTN","PSOTPRX1",70,0)
 D KV S DIR("A")="Do you want to enter allergies or adverse reactions at this time?"
"RTN","PSOTPRX1",71,0)
 S DIR("B")="Y",DIR(0)="YN" W !! D ^DIR I Y W !
"RTN","PSOTPRX1",72,0)
 D:Y EN2^GMRAPEM0
"RTN","PSOTPRX1",73,0)
 I '$G(PSOPBM),'$P(^PS(55,PSODFN,0),"^",7),$P(^(0),"^",8)']"" S PSOPBM=$P(TM,".")
"RTN","PSOTPRX1",74,0)
 D ^PSOBUILD
"RTN","PSOTPRX1",75,0)
 F PT="GET","DEAD","INP","CNH","ADDRESS","COPAY" S RTN=PT_"^PSOPTPST" D @RTN Q:$G(POERR("DEAD"))!($G(PSOQFLG))
"RTN","PSOTPRX1",76,0)
 I $G(POERR("DEAD")) S POERR("QFLG")=1 F II=0:0 S II=$O(^PS(52.41,"P",PSODFN,II)) D:$P($G(^PS(52.41,II,0)),"^",3)'="DC"&($P($G(^(0)),"^",3)'="DE") DC^PSOORFI2
"RTN","PSOTPRX1",77,0)
 K PSOERR("DEAD"),II I $G(PSOQFLG) S POERR("QFLG")=1 G EOJ Q
"RTN","PSOTPRX1",78,0)
 S (PAT,PSOXXDFN)=PSODFN,POERR=1 D ^PSOORUT2,BLD^PSOORUT1,EN^PSOLMUTL
"RTN","PSOTPRX1",79,0)
 D CLEAR^VALM1 G:$G(PSOQUIT) PTX D EN^PSOLMAO
"RTN","PSOTPRX1",80,0)
 S (DFN,PSODFN)=PSOXXDFN K DIE,DIC,DLAYGO,DR,DA,PSOX,PSORXED
"RTN","PSOTPRX1",81,0)
PTX ;
"RTN","PSOTPRX1",82,0)
 K X,Y,^TMP("PS",$J),C,DEA,PRC,PSCNT,PSOACT,PSOCLC,PSOCS,PSOCT,PSOFINFL,PSOHD,PSOLST,PSOOPT,PSOPF,PSOX,PSOX1,PSOXXDFN,SIGOK,STP,STR
"RTN","PSOTPRX1",83,0)
 Q
"RTN","PSOTPRX1",84,0)
CHK ;
"RTN","PSOTPRX1",85,0)
 Q:'X
"RTN","PSOTPRX1",86,0)
 I $$UP^XLFSTR($P(^PS(53,+X,0),"^"))'="NON-VA" D MES S Y="@1",$P(^PS(55,PSODFN,"PS"),"^")=""
"RTN","PSOTPRX1",87,0)
 Q
"RTN","PSOTPRX1",88,0)
MES W $C(7),!!,"Invalid Selection - Only 'NON-VA' patient status can be processed through"
"RTN","PSOTPRX1",89,0)
 W !,"this option. For all other statuses use the regular Patient Prescription"
"RTN","PSOTPRX1",90,0)
 W !,"Processing option"
"RTN","PSOTPRX1",91,0)
 Q
"RTN","PSOTPRX1",92,0)
WRN W $C(7),!!?15,"*** Current RX Patient Status is "_X_" ***"
"RTN","PSOTPRX1",93,0)
 W !,"Only 'NON-VA' patient status should be processed through this option."
"RTN","PSOTPRX1",94,0)
 W !,"For all other statuses use the regular Patient Prescription Processing option."
"RTN","PSOTPRX1",95,0)
 Q
"RTN","PSOTPRX1",96,0)
EOJ ;
"RTN","PSOTPRX1",97,0)
 K PSOERR,PSOMED,PSORX,PSOSD,PSODRUG,PSODFN,PSOOPT,PSOBILL,PSOIBQS,PSOCPAY,PSOPF,PSOPI,COMM,DGI,DGS,PT,PTDY,PTRF,RN,RTN,SERS,ST0,STAT,DFN,STOP,SLPPL,RXREC,PSOPBM
"RTN","PSOTPRX1",98,0)
 K:'$G(MEDP) PSOQFLG
"RTN","PSOTPRX1",99,0)
 D KVA^VADPT,FULL^VALM1 K PSOLST,PSOXFLG,PSCNT,PSDIS,PSOAL,P1,LOG,%,%DT,%I,D0,DAT,DFN,DRG,ORX,PSON,PSOPTPST,PTST,PSOBCK,PSOID,PSOBXPUL
"RTN","PSOTPRX1",100,0)
 K INCOM,SIG,SG,STP,RX0,RXN,RX2,RX3,RTS,C,DEAD,PS,PSOCLC,PSOCNT,PSOCT,PSODA,PSOFROM,PSOHD,R3,REA,RF,RFD,RFM,RLD,RXNUM,RXP,RXPR,RXRP,RXRS,STR,POERR,VALMSG
"RTN","PSOTPRX1",101,0)
 K ^TMP("PSORXDC",$J),^TMP("PSOAL",$J),^TMP("PSOAO",$J),^TMP("PSOSF",$J),^TMP("PSOPF",$J),^TMP("PSOPI",$J),^TMP("PSOPO",$J),^TMP("PSOHDR",$J) I '$G(MEDP),'$G(PSOQUIT) K PAT
"RTN","PSOTPRX1",102,0)
 K RFN,PSOXXDFN,VALM,VALMKEY,PSOBCK,SPOERR,PSOFLAG,VALMBCK,D,GMRA,GMRAL,GMRAREC,PSOSTA,PSODT,RXFL,NOBG,BBRX,BBFLG
"RTN","PSOTPRX1",103,0)
KV K DIR,DIRUT,DTOUT,DUOUT,X,Y
"RTN","PSOTPRX1",104,0)
 Q
"RTN","PSOTPRX1",105,0)
ELIG ; shows eligibility and disabilities
"RTN","PSOTPRX1",106,0)
 D ELIG^VADPT W !,"Eligibility: "_$P(VAEL(1),"^",2)_$S(+VAEL(3):"     SC%: "_$P(VAEL(3),"^",2),1:"") S N=0 F  S N=$O(VAEL(1,N)) Q:'N  W !,?10,$P(VAEL(1,N),"^",2)
"RTN","PSOTPRX1",107,0)
 W !,"Disabilities: " F I=0:0 S I=$O(^DPT(DFN,.372,I)) Q:'I  S I1=$S($D(^DPT(DFN,.372,I,0)):^(0),1:"") D:+I1
"RTN","PSOTPRX1",108,0)
 .S PSDIS=$S($P($G(^DIC(31,+I1,0)),"^")]""&($P($G(^(0)),"^",4)']""):$P(^(0),"^"),$P($G(^DIC(31,+I1,0)),"^",4)]"":$P(^(0),"^",4),1:""),PSCNT=$P(I1,"^",2)
"RTN","PSOTPRX1",109,0)
 .W:$L(PSDIS_"-"_PSCNT_"% ("_$S($P(I1,"^",3):"SC",1:"NSC")_"), ")>80 !,?15
"RTN","PSOTPRX1",110,0)
 .W $S($G(PSDIS)]"":PSDIS_"-",1:"")_PSCNT_"% ("_$S($P(I1,"^",3):"SC",1:"NSC")_"), "
"RTN","PSOTPRX1",111,0)
 K N
"RTN","PSOTPRX1",112,0)
 Q
"RTN","PSOTPRX1",113,0)
PROFILE ;
"RTN","PSOTPRX1",114,0)
 S (PSORX("REFILL"),PSORX("RENEW"))=0,PSOX="" D ^PSOBUILD
"RTN","PSOTPRX1",115,0)
 I '$G(PSOSD) W !,"This patient has no prescriptions" S:'$D(DFN) DFN=PSODFN D GMRA^PSODEM G PROFILEX
"RTN","PSOTPRX1",116,0)
 S (PSODRG,PSOX)="" F  S PSODRG=$O(PSOSD(PSODRG)) Q:PSODRG=""  F  S PSOX=$O(PSOSD(PSODRG,PSOX)) Q:PSOX=""  S:$P(PSOSD(PSODRG,PSOX),"^",3)="" PSORX("RENEW")=1 S:$P(PSOSD(PSODRG,PSOX),"^",4)="" PSORX("REFILL")=1
"RTN","PSOTPRX1",117,0)
 K PSOX
"RTN","PSOTPRX1",118,0)
PROFILEX ;
"RTN","PSOTPRX1",119,0)
 Q
"VER")
8.0^22.0
"BLD",6338,6)
^272
**END**
**END**
