Released TIU*1*234 SEQ #221
Extracted from mail message
**KIDS**:TIU*1.0*234^

**INSTALL NAME**
TIU*1.0*234
"BLD",6862,0)
TIU*1.0*234^TEXT INTEGRATION UTILITIES^0^3071211^y
"BLD",6862,1,0)
^^2^2^3071113^
"BLD",6862,1,1,0)
For a description of this build see the National Patch Module entry for 
"BLD",6862,1,2,0)
TIU*1*234.
"BLD",6862,4,0)
^9.64PA^^
"BLD",6862,6.3)
6
"BLD",6862,"INID")
n
"BLD",6862,"KRN",0)
^9.67PA^8989.52^19
"BLD",6862,"KRN",.4,0)
.4
"BLD",6862,"KRN",.401,0)
.401
"BLD",6862,"KRN",.402,0)
.402
"BLD",6862,"KRN",.403,0)
.403
"BLD",6862,"KRN",.5,0)
.5
"BLD",6862,"KRN",.84,0)
.84
"BLD",6862,"KRN",3.6,0)
3.6
"BLD",6862,"KRN",3.8,0)
3.8
"BLD",6862,"KRN",9.2,0)
9.2
"BLD",6862,"KRN",9.8,0)
9.8
"BLD",6862,"KRN",9.8,"NM",0)
^9.68A^7^7
"BLD",6862,"KRN",9.8,"NM",1,0)
TIULP^^0^B48499805
"BLD",6862,"KRN",9.8,"NM",2,0)
TIUSRVA^^0^B23503804
"BLD",6862,"KRN",9.8,"NM",3,0)
TIURA3^^0^B38623337
"BLD",6862,"KRN",9.8,"NM",4,0)
TIUPRPN1^^0^B54770889
"BLD",6862,"KRN",9.8,"NM",5,0)
TIUSRVR2^^0^B31602592
"BLD",6862,"KRN",9.8,"NM",6,0)
TIURB^^0^B46724354
"BLD",6862,"KRN",9.8,"NM",7,0)
TIUEN234^^0^B2843730
"BLD",6862,"KRN",9.8,"NM","B","TIUEN234",7)

"BLD",6862,"KRN",9.8,"NM","B","TIULP",1)

"BLD",6862,"KRN",9.8,"NM","B","TIUPRPN1",4)

"BLD",6862,"KRN",9.8,"NM","B","TIURA3",3)

"BLD",6862,"KRN",9.8,"NM","B","TIURB",6)

"BLD",6862,"KRN",9.8,"NM","B","TIUSRVA",2)

"BLD",6862,"KRN",9.8,"NM","B","TIUSRVR2",5)

"BLD",6862,"KRN",19,0)
19
"BLD",6862,"KRN",19,"NM",0)
^9.68A^^
"BLD",6862,"KRN",19.1,0)
19.1
"BLD",6862,"KRN",101,0)
101
"BLD",6862,"KRN",409.61,0)
409.61
"BLD",6862,"KRN",771,0)
771
"BLD",6862,"KRN",870,0)
870
"BLD",6862,"KRN",8989.51,0)
8989.51
"BLD",6862,"KRN",8989.52,0)
8989.52
"BLD",6862,"KRN",8994,0)
8994
"BLD",6862,"KRN","B",.4,.4)

"BLD",6862,"KRN","B",.401,.401)

"BLD",6862,"KRN","B",.402,.402)

"BLD",6862,"KRN","B",.403,.403)

"BLD",6862,"KRN","B",.5,.5)

"BLD",6862,"KRN","B",.84,.84)

"BLD",6862,"KRN","B",3.6,3.6)

"BLD",6862,"KRN","B",3.8,3.8)

"BLD",6862,"KRN","B",9.2,9.2)

"BLD",6862,"KRN","B",9.8,9.8)

"BLD",6862,"KRN","B",19,19)

"BLD",6862,"KRN","B",19.1,19.1)

"BLD",6862,"KRN","B",101,101)

"BLD",6862,"KRN","B",409.61,409.61)

"BLD",6862,"KRN","B",771,771)

"BLD",6862,"KRN","B",870,870)

"BLD",6862,"KRN","B",8989.51,8989.51)

"BLD",6862,"KRN","B",8989.52,8989.52)

"BLD",6862,"KRN","B",8994,8994)

"BLD",6862,"PRE")
TIUEN234
"BLD",6862,"QDEF")
^^^^^^^^^^YES
"BLD",6862,"QUES",0)
^9.62^^
"BLD",6862,"REQB",0)
^9.611^5^5
"BLD",6862,"REQB",1,0)
TIU*1.0*220^2
"BLD",6862,"REQB",2,0)
TIU*1.0*236^2
"BLD",6862,"REQB",3,0)
TIU*1.0*235^2
"BLD",6862,"REQB",4,0)
TIU*1.0*222^2
"BLD",6862,"REQB",5,0)
TIU*1.0*184^2
"BLD",6862,"REQB","B","TIU*1.0*184",5)

"BLD",6862,"REQB","B","TIU*1.0*220",1)

"BLD",6862,"REQB","B","TIU*1.0*222",4)

"BLD",6862,"REQB","B","TIU*1.0*235",3)

"BLD",6862,"REQB","B","TIU*1.0*236",2)

"MBREQ")
0
"PKG",193,-1)
1^1
"PKG",193,0)
TEXT INTEGRATION UTILITIES^TIU^Text Integration Utilities 
"PKG",193,20,0)
^9.402P^^
"PKG",193,22,0)
^9.49I^1^1
"PKG",193,22,1,0)
1.0^3010321^3010321^11
"PKG",193,22,1,"PAH",1,0)
234^3071211
"PKG",193,22,1,"PAH",1,1,0)
^^2^2^3071211
"PKG",193,22,1,"PAH",1,1,1,0)
For a description of this build see the National Patch Module entry for 
"PKG",193,22,1,"PAH",1,1,2,0)
TIU*1*234.
"PRE")
TIUEN234
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPI1",0)
YO
"QUES","XPI1","??")
^D INHIBIT^XPDH
"QUES","XPI1","A")
Want KIDS to INHIBIT LOGONs during the install
"QUES","XPI1","B")
NO
"QUES","XPI1","M")
D XPI1^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPO1",0)
Y
"QUES","XPO1","??")
^D MENU^XPDH
"QUES","XPO1","A")
Want KIDS to Rebuild Menu Trees Upon Completion of Install
"QUES","XPO1","B")
NO
"QUES","XPO1","M")
D XPO1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
YES
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
7
"RTN","TIUEN234")
0^7^B2843730^n/a
"RTN","TIUEN234",1,0)
TIUEN234 ; SLC/MAM - Environment Check Rtn for TIU*1*234 ; 12/11/07
"RTN","TIUEN234",2,0)
 ;;1.0;Text Integration Utilities;**234**;Jun 20, 1997;Build 6
"RTN","TIUEN234",3,0)
 ; External References
"RTN","TIUEN234",4,0)
 ;   ICR 3409  ^USR(8930,"B"
"RTN","TIUEN234",5,0)
 ;   ICR 1544 WHOIS2^USRLM
"RTN","TIUEN234",6,0)
MAIN ; Check environment.  If AMEND classes not found, abort install.
"RTN","TIUEN234",7,0)
 N TIUOK S TIUOK=0
"RTN","TIUEN234",8,0)
 N TIUCLS,TIULST S TIUCLS=+$O(^USR(8930,"B","CHIEF, MIS",""))
"RTN","TIUEN234",9,0)
 I TIUCLS>0 D  I +TIUOK G MAINX
"RTN","TIUEN234",10,0)
 . D WHOIS2^USRLM("TIULST",TIUCLS)
"RTN","TIUEN234",11,0)
 . I $P(TIULST(0),U,3)>0 S TIUOK=1
"RTN","TIUEN234",12,0)
 N TIUCLS,TIULST S TIUCLS=+$O(^USR(8930,"B","CHIEF, HIM",""))
"RTN","TIUEN234",13,0)
 I TIUCLS>0 D  I +TIUOK G MAINX
"RTN","TIUEN234",14,0)
 . D WHOIS2^USRLM("TIULST",TIUCLS)
"RTN","TIUEN234",15,0)
 . I $P(TIULST(0),U,3)>0 S TIUOK=1
"RTN","TIUEN234",16,0)
 N TIUCLS,TIULST S TIUCLS=+$O(^USR(8930,"B","PRIVACY ACT OFFICER",""))
"RTN","TIUEN234",17,0)
 I TIUCLS>0 D  I TIUOK G MAINX
"RTN","TIUEN234",18,0)
 . D WHOIS2^USRLM("TIULST",TIUCLS)
"RTN","TIUEN234",19,0)
 . I $P(TIULST(0),U,3)>0 S TIUOK=1
"RTN","TIUEN234",20,0)
 S XPDABORT=1
"RTN","TIUEN234",21,0)
 W !,"  Documents cannot be amended except by members of class CHIEF, MIS,"
"RTN","TIUEN234",22,0)
 W !,"CHIEF, HIM, or PRIVACY ACT OFFICER. (Classes must be named exactly as listed.)"
"RTN","TIUEN234",23,0)
 W !,"  I can't find any users in these classes. Please check with the person who"
"RTN","TIUEN234",24,0)
 W !,"maintains User Classes at your site."
"RTN","TIUEN234",25,0)
 W !,"  Aborting install."
"RTN","TIUEN234",26,0)
MAINX ;
"RTN","TIUEN234",27,0)
 I TIUOK W !,"  User Classes look ok."
"RTN","TIUEN234",28,0)
 Q
"RTN","TIUEN234",29,0)
 ;
"RTN","TIULP")
0^1^B48499805^B47310116
"RTN","TIULP",1,0)
TIULP ; SLC/JER - Functions determining privilege ;11/13/07
"RTN","TIULP",2,0)
 ;;1.0;TEXT INTEGRATION UTILITIES;**98,100,116,109,138,152,175,157,182,184,217,236,234**;Jun 20, 1997;Build 6
"RTN","TIULP",3,0)
 ; CANDO^USRLA: ICA 2325, ISA^USRLM: ICA 2324
"RTN","TIULP",4,0)
 ; 8930.1,2,8: IACS 3129,3128,3104 
"RTN","TIULP",5,0)
CANDO(TIUDA,TIUACT,PERSON) ; Can PERSON perform action now
"RTN","TIULP",6,0)
 ; Receives: TIUDA=Record number in file 8925
"RTN","TIULP",7,0)
 ;           TIUACT=Name of user action in 8930.8 (USR ACTION)
"RTN","TIULP",8,0)
 ;           PERSON=New Person file IFN.
"RTN","TIULP",9,0)
 ;                  Assumed to be DUZ if not received.
"RTN","TIULP",10,0)
 ;                  New **100** ID param, backward compatible.
"RTN","TIULP",11,0)
 ;  Returns:   TIUY=1:yes,0:no_"^"_why not message
"RTN","TIULP",12,0)
 N TIUI,TIUTYP,TIUROLE,STATUS,TIUY,TIUATYP,MSG,WHO,MODIFIER,TIUD0,TIUACTW
"RTN","TIULP",13,0)
 S TIUY=0 I '$G(PERSON) S PERSON=DUZ
"RTN","TIULP",14,0)
 S TIUD0=$G(^TIU(8925,+TIUDA,0)) I 'TIUD0 G CANDOX
"RTN","TIULP",15,0)
 I $$ISPRFDOC^TIUPRF(TIUDA),((TIUACT="ATTACH ID ENTRY")!(TIUACT="ATTACH TO ID NOTE")) S TIUY="0^Patient Record Flag notes may not be used as Interdisciplinary notes." G CANDOX
"RTN","TIULP",16,0)
 S TIUACTW=$G(TIUACT)
"RTN","TIULP",17,0)
 ;**100** was I +TIUACT'>0 S TIUACT etc.
"RTN","TIULP",18,0)
 S TIUACT=$$USREVNT(TIUACT) I +TIUACT'>0 G CANDOX
"RTN","TIULP",19,0)
 ; -- Historical Procedures - Prohibit actions detailed in
"RTN","TIULP",20,0)
 ;    HPCAN^TIUCP: P182
"RTN","TIULP",21,0)
 N HPCAN I $$ISHISTCP^TIUCP(+TIUD0) S HPCAN=$$HPCAN^TIUCP(+TIUACT) I 'HPCAN S TIUY=HPCAN G CANDOX
"RTN","TIULP",22,0)
 ; **152 Get status
"RTN","TIULP",23,0)
 S STATUS=+$P(TIUD0,U,5)
"RTN","TIULP",24,0)
 ; **152[234] prevents editing or sending back a completed or uncosigned document.
"RTN","TIULP",25,0)
 I STATUS>5,(+TIUACT=9)!(+TIUACT=17) D  G CANDOX
"RTN","TIULP",26,0)
 . ; **152[234] Displays message to user
"RTN","TIULP",27,0)
 . I +TIUACT=9 S TIUY="0^ You may not edit uncosigned or completed documents."
"RTN","TIULP",28,0)
 . I +TIUACT=17 S TIUY="0^You may not send back uncosigned or completed documents."
"RTN","TIULP",29,0)
 ; -- In case business rules have changed, & children already existed:
"RTN","TIULP",30,0)
 I +TIUACT=24,$D(^TIU(8925,"GDAD",TIUDA)) D  G CANDOX
"RTN","TIULP",31,0)
 . S TIUY="0^ This note cannot be attached; it has its own children."
"RTN","TIULP",32,0)
 I +TIUACT=25,+$G(^TIU(8925,TIUDA,21)) D  G CANDOX
"RTN","TIULP",33,0)
 . S TIUY="0^ This note cannot receive interdisciplinary children; it is itself a child."
"RTN","TIULP",34,0)
 I +TIUACT=4!(+TIUACT=5),+$$BLANK^TIULC(TIUDA) D  G CANDOX ;Sets TIUPRM1
"RTN","TIULP",35,0)
 . S TIUY="0^ Contains blanks ("_$P(TIUPRM1,U,6)_") which must be filled before "_$P(TIUACT,U,2)_"ATURE."
"RTN","TIULP",36,0)
 S TIUROLE=$$USRROLE(TIUDA,PERSON)
"RTN","TIULP",37,0)
 S TIUTYP=+TIUD0
"RTN","TIULP",38,0)
 I $$ISADDNDM^TIULC1(+TIUDA) S TIUATYP=TIUTYP,TIUTYP=+$G(^TIU(8925,+$P(TIUD0,U,6),0))
"RTN","TIULP",39,0)
 I TIUROLE']"" S TIUY=$$CANDO^USRLA(TIUTYP,STATUS,+TIUACT,PERSON)
"RTN","TIULP",40,0)
 F TIUI=1:1:($L(TIUROLE,U)-1) D  Q:+$G(TIUY)>0
"RTN","TIULP",41,0)
 . S TIUY=$$CANDO^USRLA(TIUTYP,STATUS,+TIUACT,PERSON,$P(TIUROLE,U,TIUI))
"RTN","TIULP",42,0)
 I +$G(TIUATYP) S TIUTYP=+$G(TIUATYP)
"RTN","TIULP",43,0)
 ;**100** update for PERSON param; update for verb modifier:
"RTN","TIULP",44,0)
 I +TIUY'>0 D  G CANDOX
"RTN","TIULP",45,0)
 . S WHO=" You"
"RTN","TIULP",46,0)
 . ;I PERSON'=DUZ S WHO=$P(^VA(200,PERSON,0),U),WHO=$$NAME^TIULS(WHO,"FIRST LAST")
"RTN","TIULP",47,0)
 . I PERSON'=DUZ S WHO=$$NAME^TIULS($$GET1^DIQ(200,PERSON,.01),"FIRST LAST") ;P182
"RTN","TIULP",48,0)
 . S MODIFIER=$P(TIUACT,U,3) I $L(MODIFIER) S MODIFIER=" "_MODIFIER
"RTN","TIULP",49,0)
 . ;e.g. "You may not ATTACH this UNSIGNED TELEPHONE NOTE TO AN ID NOTE."
"RTN","TIULP",50,0)
 . S MSG=WHO_" may not "_$P(TIUACT,U,2)_" this "_$P($G(^TIU(8925.6,+STATUS,0)),U)_" "_$$PNAME^TIULC1(TIUTYP)_MODIFIER_"."
"RTN","TIULP",51,0)
 . S TIUY=TIUY_U_MSG
"RTN","TIULP",52,0)
 I +TIUACT=15,$$HASIMG^TIURB2(+TIUDA) D  G CANDOX
"RTN","TIULP",53,0)
 . S TIUY="0^ This document contains linked images. You must ""delete"" the Images using the Imaging package before proceeding."
"RTN","TIULP",54,0)
 ;VMP/ELR P217. Do not allow deletion of a parent with child
"RTN","TIULP",55,0)
 I $G(TIUACTW)["DELETE RECORD",$$HASIDKID^TIUGBR(+TIUDA) D  G CANDOX
"RTN","TIULP",56,0)
 . S TIUY="0^ "_$$EZBLD^DIALOG(89250013)
"RTN","TIULP",57,0)
CANDOX Q TIUY
"RTN","TIULP",58,0)
 ;
"RTN","TIULP",59,0)
CANLINK(TIUTYP) ; Can user (DUZ) link (attach) a document of a particular type
"RTN","TIULP",60,0)
 ;to an ID note.
"RTN","TIULP",61,0)
 ; For use in ADD NEW ID NOTE, where docmt is not entered yet.
"RTN","TIULP",62,0)
 ; Assume most favorable circumstances (user will complete
"RTN","TIULP",63,0)
 ;the note, so if user still can't attach, can tell them no,
"RTN","TIULP",64,0)
 ;when they first select title for the new entry.
"RTN","TIULP",65,0)
 ; Rule out if TIUTYP can be an ID parent, since ID parent
"RTN","TIULP",66,0)
 ;and ID kid function as mutually exclusive, (regardless of
"RTN","TIULP",67,0)
 ;business rules).
"RTN","TIULP",68,0)
 N TIUACT,STATUS,USRROLE,TIUY
"RTN","TIULP",69,0)
 S TIUACT=$$USREVNT("ATTACH TO ID NOTE"),STATUS=7 ; complete
"RTN","TIULP",70,0)
 S USRROLE=+$O(^USR(8930.2,"B","COMPLETER",0))
"RTN","TIULP",71,0)
 S TIUY=$$CANDO^USRLA(TIUTYP,STATUS,+TIUACT,DUZ,USRROLE)
"RTN","TIULP",72,0)
 I '$G(TIUY) S TIUY="0^ You may not use this title for interdisciplinary child entries." Q TIUY
"RTN","TIULP",73,0)
 ; -- If user can attach a certain note, but note can also receive
"RTN","TIULP",74,0)
 ;    ID entries, don't let user attach it. --
"RTN","TIULP",75,0)
 I $$POSSPRNT^TIULP(TIUTYP) S TIUY="0^ This interdisciplinary PARENT title cannot be used for CHILD entries."
"RTN","TIULP",76,0)
 ; -- If selected type is a CWAD, don't let user attach it: --
"RTN","TIULP",77,0)
 I $$ISCWAD^TIULX(TIUTYP) S TIUY="0^ CWAD titles cannot be used for interdisciplinary entries."
"RTN","TIULP",78,0)
 ; -- If selected type is a PRF, don't let user attach it: --
"RTN","TIULP",79,0)
 I $$ISPFTTL^TIUPRFL(TIUTYP) S TIUY="0^ Patient Record Flag titles cannot be used for interdisciplinary entries."
"RTN","TIULP",80,0)
 ; -- If selected type is a consult, don't let user attach it: --
"RTN","TIULP",81,0)
 I $$ISA^TIULX(TIUTYP,+$$CLASS^TIUCNSLT) S TIUY="0^ Consult titles cannot be used for interdisciplinary entries."
"RTN","TIULP",82,0)
 Q TIUY
"RTN","TIULP",83,0)
 ;
"RTN","TIULP",84,0)
POSSPRNT(TIUTYP) ; Is a docmt intended as a possible ID parent?
"RTN","TIULP",85,0)
 ;Returns 1^WHYCAN'TATTACH if there are business rules permitting ANYONE
"RTN","TIULP",86,0)
 ;to attach ID entries to notes of type TIUTYP.
"RTN","TIULP",87,0)
 ;Else returns 0.
"RTN","TIULP",88,0)
 N TIUACT,STATUS,TIUY,DADTYP
"RTN","TIULP",89,0)
 S TIUY=0,TIUACT=+$$USREVNT("ATTACH ID ENTRY")
"RTN","TIULP",90,0)
 F STATUS=6,7,8 D  G:TIUY POSSX
"RTN","TIULP",91,0)
 . I $O(^USR(8930.1,"AR",TIUTYP,STATUS,TIUACT,0)) S TIUY=1 Q
"RTN","TIULP",92,0)
 . I $O(^USR(8930.1,"AC",TIUTYP,STATUS,TIUACT,0)) S TIUY=1
"RTN","TIULP",93,0)
 ; -- If no rules for TIUTYP, try its parent: --
"RTN","TIULP",94,0)
 S DADTYP=$O(^TIU(8925.1,"AD",TIUTYP,0)) G:DADTYP'>0 POSSX
"RTN","TIULP",95,0)
 S TIUY=$$POSSPRNT(DADTYP)
"RTN","TIULP",96,0)
POSSX I TIUY S TIUY="1^ Interdisciplinary PARENT notes cannot be attached as CHILD entries."
"RTN","TIULP",97,0)
 Q TIUY
"RTN","TIULP",98,0)
 ;
"RTN","TIULP",99,0)
CANENTR(TIUTYP) ; Evaluate privilege to enter a document of a particular type
"RTN","TIULP",100,0)
 N TIUACT,STATUS,USRROLE,TIUY
"RTN","TIULP",101,0)
 S TIUACT=$$USREVNT("ENTRY"),STATUS=2 ; untranscribed
"RTN","TIULP",102,0)
 S USRROLE=3 ; transcriber
"RTN","TIULP",103,0)
 S TIUY=$$CANDO^USRLA(TIUTYP,STATUS,+TIUACT,DUZ,USRROLE)
"RTN","TIULP",104,0)
 Q TIUY
"RTN","TIULP",105,0)
USRROLE(TIUDA,PERSON) ; Identify the user's role with respect to the document
"RTN","TIULP",106,0)
 ; 3/20/00 **100** Added role COMPLETER
"RTN","TIULP",107,0)
 ; 3/20/00 **100** Added PERSON param
"RTN","TIULP",108,0)
 N TIU0,TIU12,TIU13,TIUY,TIU15,COMPLTR,STATUS
"RTN","TIULP",109,0)
 S PERSON=$G(PERSON,DUZ)
"RTN","TIULP",110,0)
 S TIU0=$G(^TIU(8925,+TIUDA,0)),STATUS=$P(TIU0,U,5)
"RTN","TIULP",111,0)
 S TIU12=$G(^TIU(8925,+TIUDA,12))
"RTN","TIULP",112,0)
 S TIU13=$G(^TIU(8925,+TIUDA,13)),TIU15=$G(^TIU(8925,+TIUDA,15))
"RTN","TIULP",113,0)
 I PERSON=+$P(TIU13,U,2) S TIUY=+$O(^USR(8930.2,"B","TRANSCRIBER",0))_U
"RTN","TIULP",114,0)
 I PERSON=+$P(TIU12,U,2) S TIUY=$G(TIUY)_+$O(^USR(8930.2,"B","AUTHOR/DICTATOR",0))_U
"RTN","TIULP",115,0)
 I PERSON=+$P(TIU12,U,9) S TIUY=$G(TIUY)_+$O(^USR(8930.2,"B","ATTENDING PHYSICIAN",0))_U
"RTN","TIULP",116,0)
 I PERSON=+$P(TIU12,U,4) S TIUY=$G(TIUY)_+$O(^USR(8930.2,"B","EXPECTED SIGNER",0))_U
"RTN","TIULP",117,0)
 I PERSON=+$P(TIU12,U,8) S TIUY=$G(TIUY)_+$O(^USR(8930.2,"B","EXPECTED COSIGNER",0))_U
"RTN","TIULP",118,0)
 I $$ASURG^TIUADSIG(TIUDA) S TIUY=$G(TIUY)_+$O(^USR(8930.2,"B","SURROGATE",0))_U ;P157
"RTN","TIULP",119,0)
 ;Check if the person can be an Interpreter for this document via a Consult API
"RTN","TIULP",120,0)
 I $$CPINTERP^GMRCCP(+TIUDA,PERSON) S TIUY=$G(TIUY)_+$O(^USR(8930.2,"B","INTERPRETER",0))_U
"RTN","TIULP",121,0)
 I STATUS>6 D  I COMPLTR S TIUY=$G(TIUY)_+$O(^USR(8930.2,"B","COMPLETER",0))_U
"RTN","TIULP",122,0)
 . S COMPLTR=0
"RTN","TIULP",123,0)
 . I PERSON=+$P(TIU15,U,8) S COMPLTR=1 Q
"RTN","TIULP",124,0)
 . I '$P(TIU15,U,8),PERSON=+$P(TIU15,U,2) S COMPLTR=1
"RTN","TIULP",125,0)
 I +$O(^TIU(8925.7,"AE",+TIUDA,+PERSON,0)) D
"RTN","TIULP",126,0)
 . N TIUXTRA S TIUXTRA=+$O(^TIU(8925.7,"AE",+TIUDA,+PERSON,0))
"RTN","TIULP",127,0)
 . I +$P($G(^TIU(8925.7,+TIUXTRA,0)),U,4) Q
"RTN","TIULP",128,0)
 . S TIUY=$G(TIUY)_+$O(^USR(8930.2,"B","ADDITIONAL SIGNER",0))_U
"RTN","TIULP",129,0)
 Q $G(TIUY)
"RTN","TIULP",130,0)
USREVNT(EVENT) ; Given event name, return:
"RTN","TIULP",131,0)
 ;EVENT = event pointer^user verb^verb modifier
"RTN","TIULP",132,0)
 ; **100** added verb modifier piece (.07)
"RTN","TIULP",133,0)
 N TIUY,TIUDA,NODE0
"RTN","TIULP",134,0)
 S TIUDA=+$O(^USR(8930.8,"B",EVENT,0))
"RTN","TIULP",135,0)
 S NODE0=$G(^USR(8930.8,TIUDA,0))
"RTN","TIULP",136,0)
 S TIUY=TIUDA_U_$P(NODE0,U,5)_U_$P(NODE0,U,7)
"RTN","TIULP",137,0)
 Q TIUY
"RTN","TIULP",138,0)
CANPICK(TIUTYP) ; Screens selection of title by title status and
"RTN","TIULP",139,0)
 ;(for status TEST), by owner.
"RTN","TIULP",140,0)
 N TIUPOWN,TIUCOWN,TIUT0,TIUTSTAT,TIUY S TIUY=0
"RTN","TIULP",141,0)
 S TIUT0=$G(^TIU(8925.1,+TIUTYP,0)),TIUTSTAT=$P(TIUT0,U,7)
"RTN","TIULP",142,0)
 I TIUTSTAT']"" S TIUY=0 G CANPIX
"RTN","TIULP",143,0)
 I TIUTSTAT=13 S TIUY=0 G CANPIX
"RTN","TIULP",144,0)
 I TIUTSTAT=11 S TIUY=1 G CANPIX
"RTN","TIULP",145,0)
 S TIUPOWN=$P(TIUT0,U,5),TIUCOWN=+$P(TIUT0,U,6)
"RTN","TIULP",146,0)
 I TIUTSTAT=10 S TIUY=$S(TIUPOWN=DUZ:1,+$$ISA^USRLM(DUZ,TIUCOWN):1,1:0)
"RTN","TIULP",147,0)
CANPIX Q +$G(TIUY)
"RTN","TIULP",148,0)
REQCOSIG(TIUTYP,TIUDA,USER,TIUDT) ; Evaluate whether user requires cosignature
"RTN","TIULP",149,0)
 N TIUI,TIUY,TIUDPRM S USER=$S(+$G(USER):+$G(USER),1:+$G(DUZ))
"RTN","TIULP",150,0)
 D DOCPRM^TIULC1(TIUTYP,.TIUDPRM,+$G(TIUDA))
"RTN","TIULP",151,0)
 I $G(TIUDPRM(5))="" G REQCOSX
"RTN","TIULP",152,0)
 I +$G(TIUDT)'>0 S TIUDT=+$P($P(+$G(^TIU(8925,+$G(TIUDA),13)),U),".")
"RTN","TIULP",153,0)
 F TIUI=1:1:$L(TIUDPRM(5),U) D  Q:+TIUY>0
"RTN","TIULP",154,0)
 . S TIUY=+$$ISA^USRLM(+USER,+$P(TIUDPRM(5),U,TIUI),,+$G(TIUDT))
"RTN","TIULP",155,0)
REQCOSX Q +$G(TIUY)
"RTN","TIULP",156,0)
 ;
"RTN","TIULP",157,0)
REQCPF(TIUCDA) ;Check if clinical procedure fields are required
"RTN","TIULP",158,0)
 ; Input  -- TIUCDA   Request/Consult File (#123) IEN
"RTN","TIULP",159,0)
 ; Output -- 1=Required and 0=Not Required
"RTN","TIULP",160,0)
 N TIUCPACT,REQF
"RTN","TIULP",161,0)
 I '$G(TIUCDA) G REQCPFQ
"RTN","TIULP",162,0)
 S TIUCPACT=$$CPACTM^GMRCCP(TIUCDA)
"RTN","TIULP",163,0)
 I TIUCPACT=1!(TIUCPACT=3) S REQF=1
"RTN","TIULP",164,0)
REQCPFQ Q +$G(REQF)
"RTN","TIUPRPN1")
0^4^B54770889^B53973292
"RTN","TIUPRPN1",1,0)
TIUPRPN1 ;SLC/JER - Print SF 509-Progress Notes ;11/23/07
"RTN","TIUPRPN1",2,0)
 ;;1.0;TEXT INTEGRATION UTILITIES;**45,52,87,100,162,182,211,222,234**;Jun 20, 1997;Build 6
"RTN","TIUPRPN1",3,0)
 ; DBIA 908 ^SC(D0,0)
"RTN","TIUPRPN1",4,0)
PRINT(TIUFLAG,TIUSPG) ; Print Document
"RTN","TIUPRPN1",5,0)
 ; ^TMP("TIUPR",$J) is array of records to be printed
"RTN","TIUPRPN1",6,0)
 ; TIUFLAG=1 --> Chart Copy     TIUSPG=1 --> Contiguous
"RTN","TIUPRPN1",7,0)
 ; TIUFLAG=0 --> Work Copy      TIUSPG=0 --> Fresh Page- each note
"RTN","TIUPRPN1",8,0)
 ; TIUCONT=1 --> Continue printing
"RTN","TIUPRPN1",9,0)
 ; TIUCONT1=1 --> Write "Continue to next/from previous-page" msgs
"RTN","TIUPRPN1",10,0)
 ; TIUPFNBR ---> Print Form # like vice 509
"RTN","TIUPRPN1",11,0)
 ; TIUMISC=TIUFLAG_U_TIUPFNBR_U_TIUDA
"RTN","TIUPRPN1",12,0)
 N CONT,TIUASK,TIUI,TIUJ,TIUKID,TIUPAGE,TIUFOOT,TIUK,TIUDA,TIUCONT,TIUPGRP,TIUTYP
"RTN","TIUPRPN1",13,0)
 N TIUPFHDR,TIUPFNBR,TIUMISC,TIUCONT1,TIUIDONE,TMP
"RTN","TIUPRPN1",14,0)
 S TIUFLAG=+$G(TIUFLAG),TIUSPG=+$G(TIUSPG)
"RTN","TIUPRPN1",15,0)
 S (CONT,TIUCONT)=1,(TIUASK,TIUCONT1)=0
"RTN","TIUPRPN1",16,0)
 S TIUI=0 F  S TIUI=$O(^TMP("TIUPR",$J,TIUI)) Q:TIUI=""  D  Q:'TIUCONT
"RTN","TIUPRPN1",17,0)
 . N DFN,TIU
"RTN","TIUPRPN1",18,0)
 . ; -- P182 TIUI has form PGRP$PFHDR;DFN with PGRP possibly 0, and
"RTN","TIUPRPN1",19,0)
 . ;    PFHDR possibly null (see TIURA):
"RTN","TIUPRPN1",20,0)
 . S TIUPGRP=+$P(TIUI,"$"),TIUPFHDR=$P($P(TIUI,";"),"$",2)
"RTN","TIUPRPN1",21,0)
 . I TIUPFHDR']"" S TIUPFHDR="Progress Notes"
"RTN","TIUPRPN1",22,0)
 . S DFN=$P(TIUI,";",2)
"RTN","TIUPRPN1",23,0)
 . I $G(TIUPGRP)>2 S TIUSPG=0
"RTN","TIUPRPN1",24,0)
 . D PATPN^TIULV(.TIUFOOT,DFN)
"RTN","TIUPRPN1",25,0)
 . I +$G(TIUSPG) D HEADER^TIUPRPN2(.TIUFOOT,TIUFLAG,.TIUPFHDR,TIUCONT1)
"RTN","TIUPRPN1",26,0)
 . ; Use TIUJ="" (not TIUJ=0), to print "complete" notes w/o sigdt:
"RTN","TIUPRPN1",27,0)
 . S TIUJ="" F  S TIUJ=$O(^TMP("TIUPR",$J,TIUI,TIUJ)) Q:TIUJ=""  D  Q:'TIUCONT
"RTN","TIUPRPN1",28,0)
 . . S TIUK=0 F  S TIUK=$O(^TMP("TIUPR",$J,TIUI,TIUJ,TIUK)) Q:'TIUK  D  Q:'TIUCONT
"RTN","TIUPRPN1",29,0)
 . . . S TIUCONT1=0 S TIUPFNBR=^TMP("TIUPR",$J,TIUI,TIUJ,TIUK)
"RTN","TIUPRPN1",30,0)
 . . . ; Note: TIUPFNBR may be null
"RTN","TIUPRPN1",31,0)
 . . . ;P182 Set TIUMISC BEFORE quitting if deleted
"RTN","TIUPRPN1",32,0)
 . . . S TIUDA=TIUK,TIUMISC=TIUFLAG_U_TIUPFNBR_U_TIUDA
"RTN","TIUPRPN1",33,0)
 . . . ; Quit docmt if deleted:
"RTN","TIUPRPN1",34,0)
 . . . I '$D(^TIU(8925,+TIUDA,0)) D  Q
"RTN","TIUPRPN1",35,0)
 . . . . S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT)) Q:'TIUCONT
"RTN","TIUPRPN1",36,0)
 . . . . W !!,"NOTE DATED:",!,"Document #",TIUDA," for ",$G(TIUFOOT("PNMP")),!,"no longer exists in the TIU DOCUMENT file.",!!!
"RTN","TIUPRPN1",37,0)
 . . . . S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT))
"RTN","TIUPRPN1",38,0)
 . . . N TIUROOT
"RTN","TIUPRPN1",39,0)
 . . . I '+$G(TIUSPG) D HEADER^TIUPRPN2(.TIUFOOT,TIUFLAG,.TIUPFHDR,TIUCONT1)
"RTN","TIUPRPN1",40,0)
 . . . K ^TMP("TIULQ",$J)
"RTN","TIUPRPN1",41,0)
 . . . D EXTRACT^TIULQ(+TIUDA,"^TMP(""TIULQ"",$J)",.TIUERR,"","",1)
"RTN","TIUPRPN1",42,0)
 . . . I +$G(TIUERR) W !,$P(TIUERR,U,2) Q
"RTN","TIUPRPN1",43,0)
 . . . Q:'$D(^TMP("TIULQ",$J))
"RTN","TIUPRPN1",44,0)
 . . . S TIUROOT="^TMP(""TIULQ"",$J,"_TIUDA_")"
"RTN","TIUPRPN1",45,0)
 . . . D REPORT(TIUROOT,.TIUFOOT,TIUMISC,.TIUCONT) Q:'TIUCONT
"RTN","TIUPRPN1",46,0)
 . . . D IDKIDS(TIUROOT,.TIUFOOT,TIUMISC,TIUCONT1,.TIUCONT) Q:'TIUCONT
"RTN","TIUPRPN1",47,0)
 . . . I '+$G(TIUKID),'+$G(TIUSPG) S TIUCONT1=0 S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,1,$G(TIUROOT))
"RTN","TIUPRPN1",48,0)
 . Q:'TIUCONT
"RTN","TIUPRPN1",49,0)
 . I $E(IOST,1,2)="C-" S TIUCONT=$$STOP^TIUPRPN2() Q:'TIUCONT
"RTN","TIUPRPN1",50,0)
 . I '+$G(TIUKID),+$G(TIUSPG),$E(IOST,1,2)'="C-" S TIUCONT1=0 S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,1,$G(TIUROOT))
"RTN","TIUPRPN1",51,0)
 Q
"RTN","TIUPRPN1",52,0)
 ;
"RTN","TIUPRPN1",53,0)
REPORT(TIUROOT,TIUFOOT,TIUMISC,TIUCONT,TIUIDEND) ; Report Text
"RTN","TIUPRPN1",54,0)
 ; Requires array TIUFOOT, vars TIUMISC, TIUCONT
"RTN","TIUPRPN1",55,0)
 ; Requires TIUROOT =
"RTN","TIUPRPN1",56,0)
 ; ^TMP("TIULQ",$J,NOTEIFN) for parent/stand-alone note, or
"RTN","TIUPRPN1",57,0)
 ; ^TMP("TIULQ",$J,NOTEIFN,"ZADD",ADDMIFN) for addendum, or
"RTN","TIUPRPN1",58,0)
 ; ^TMP("TIULQ",$J,NOTEIFN,"ZZID",KIDSEQ#,IDKIDIFN) for ID kid, or
"RTN","TIUPRPN1",59,0)
 ; ^TMP("TIULQ",$J,NOTEIFN,"ZZID",KIDSEQ#,IDKIDIFN,"ZADD",KIDADDMIFN)
"RTN","TIUPRPN1",60,0)
 ;       for ID kid addm.
"RTN","TIUPRPN1",61,0)
 N DIW,DIWF,DIWL,DIWR,DIWT,TIUERR,TIU,TIUI,X,Z,LOC
"RTN","TIUPRPN1",62,0)
 N REFDT,TITLE,LOINCNM,ADT,HLOC,SUBJ
"RTN","TIUPRPN1",63,0)
 N TIUDA,TIUCONT1,HASIDKID,HASIDDAD
"RTN","TIUPRPN1",64,0)
 S TIUDA=$P(TIUMISC,U,3),TIUCONT1=0
"RTN","TIUPRPN1",65,0)
 S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT)) Q:'TIUCONT
"RTN","TIUPRPN1",66,0)
 S HASIDKID=$G(^TMP("TIULQ",$J,TIUDA,"ZZID",0)) ;how many ID kids
"RTN","TIUPRPN1",67,0)
 S HASIDDAD=$S(TIUROOT["ZZID":1,1:0)
"RTN","TIUPRPN1",68,0)
 I HASIDKID W "<< Interdisciplinary Note - Begin >>",!
"RTN","TIUPRPN1",69,0)
 I HASIDDAD W "<< Interdisciplinary Note - Cont. >>",!
"RTN","TIUPRPN1",70,0)
 W $S('HASIDKID&'HASIDDAD:"NOTE DATED: ",1:"ENTRY DATED: ")
"RTN","TIUPRPN1",71,0)
 S REFDT=@TIUROOT@(1301,"I")
"RTN","TIUPRPN1",72,0)
 W $$DATE^TIULS(REFDT,"MM/DD/CCYY HR:MIN")
"RTN","TIUPRPN1",73,0)
 S TITLE=@TIUROOT@(.01,"E"),LOINCNM=@TIUROOT@(89261,"E")
"RTN","TIUPRPN1",74,0)
 W !,"LOCAL TITLE: ",$$UP^XLFSTR(TITLE),!
"RTN","TIUPRPN1",75,0)
 I $L(LOINCNM)>1 W "STANDARD TITLE: ",$$UP^XLFSTR(LOINCNM),!
"RTN","TIUPRPN1",76,0)
 S LOC=$G(@TIUROOT@(1205,"I"))
"RTN","TIUPRPN1",77,0)
 I +LOC D
"RTN","TIUPRPN1",78,0)
 . W $S($P(^SC(LOC,0),U,3)="W":"ADMITTED: ",1:"VISIT: ")
"RTN","TIUPRPN1",79,0)
 . S ADT=$G(@TIUROOT@(.07,"I"))
"RTN","TIUPRPN1",80,0)
 . W $$DATE^TIULS(ADT,"MM/DD/CCYY HR:MIN")
"RTN","TIUPRPN1",81,0)
 . S HLOC=$G(@TIUROOT@(1205,"E"))
"RTN","TIUPRPN1",82,0)
 . W " ",HLOC
"RTN","TIUPRPN1",83,0)
 S SUBJ=$G(@TIUROOT@(1701,"E"))
"RTN","TIUPRPN1",84,0)
 I SUBJ]"" W !,"SUBJECT: ",^("E"),! ; @TIUROOT@(1701,"E")
"RTN","TIUPRPN1",85,0)
 S TIUCONT1=1
"RTN","TIUPRPN1",86,0)
 I $D(@TIUROOT@("PROBLEM")) D  Q:'TIUCONT
"RTN","TIUPRPN1",87,0)
 . S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT)) Q:'TIUCONT
"RTN","TIUPRPN1",88,0)
 . W !,"ASSOCIATED PROBLEMS:"
"RTN","TIUPRPN1",89,0)
 . N TIUI S TIUI=0
"RTN","TIUPRPN1",90,0)
 . F  S TIUI=$O(@TIUROOT@("PROBLEM",TIUI)) Q:'TIUI  D  Q:'TIUCONT
"RTN","TIUPRPN1",91,0)
 ..W !,^(TIUI,0) ; @TIUROOT@("PROBLEM",TIUI,0) 
"RTN","TIUPRPN1",92,0)
 ..S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT)) Q:'TIUCONT
"RTN","TIUPRPN1",93,0)
 W !
"RTN","TIUPRPN1",94,0)
 S TIUI=0,DIWF="WN",DIWL=1,DIWR=79 K ^UTILITY($J,"W")
"RTN","TIUPRPN1",95,0)
 F  S TIUI=$O(@TIUROOT@("TEXT",TIUI)) Q:TIUI'>0  D  Q:'TIUCONT  ; D ^DIWW
"RTN","TIUPRPN1",96,0)
 . S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT)) Q:'TIUCONT
"RTN","TIUPRPN1",97,0)
 . S X=@TIUROOT@("TEXT",TIUI,0) S:X="" X=" " D ^DIWP
"RTN","TIUPRPN1",98,0)
 D ^DIWW K ^UTILITY($J,"W")
"RTN","TIUPRPN1",99,0)
 Q:'TIUCONT
"RTN","TIUPRPN1",100,0)
 D GETSIG(TIUROOT,.TIUSIG)
"RTN","TIUPRPN1",101,0)
 S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT)) Q:'TIUCONT
"RTN","TIUPRPN1",102,0)
 W !
"RTN","TIUPRPN1",103,0)
 D SIGBLK^TIUPRPN8(.TIUFOOT,TIUMISC,TIUCONT1,.TIUCONT,.TIUSIG,TIUROOT)
"RTN","TIUPRPN1",104,0)
 Q:'TIUCONT
"RTN","TIUPRPN1",105,0)
ADDENDA ; Fall through and do Addenda of docmt TIUDA
"RTN","TIUPRPN1",106,0)
 N DIW,DIWF,DIWL,DIWR,DIWT,X,Z,TIUI,TIUADD,ADDMRDT
"RTN","TIUPRPN1",107,0)
 S TIUADD=0,DIWF="WN",DIWL=1,DIWR=79 K ^UTILITY($J,"W")
"RTN","TIUPRPN1",108,0)
 F  S TIUADD=$O(@TIUROOT@("ZADD",TIUADD)) Q:TIUADD'>0  D  Q:'TIUCONT
"RTN","TIUPRPN1",109,0)
 . S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT)) Q:'TIUCONT
"RTN","TIUPRPN1",110,0)
 . S ADDMRDT=@TIUROOT@("ZADD",TIUADD,1301,"I")
"RTN","TIUPRPN1",111,0)
 . W !!,$$DATE^TIULS(ADDMRDT,"MM/DD/CCYY HR:MIN"),?21,"ADDENDUM"
"RTN","TIUPRPN1",112,0)
 . W ?39,"STATUS: ",@TIUROOT@("ZADD",TIUADD,.05,"E") ;P162
"RTN","TIUPRPN1",113,0)
 . S TIUI=0
"RTN","TIUPRPN1",114,0)
 . F  S TIUI=$O(@TIUROOT@("ZADD",TIUADD,"TEXT",TIUI)) Q:TIUI'>0  D  Q:'TIUCONT
"RTN","TIUPRPN1",115,0)
 . . S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,0,$G(TIUROOT)) Q:'TIUCONT
"RTN","TIUPRPN1",116,0)
 . . S X=@TIUROOT@("ZADD",TIUADD,"TEXT",TIUI,0) S:X="" X=" " D ^DIWP
"RTN","TIUPRPN1",117,0)
 . D ^DIWW
"RTN","TIUPRPN1",118,0)
 . Q:'TIUCONT
"RTN","TIUPRPN1",119,0)
 . N TIUADRT
"RTN","TIUPRPN1",120,0)
 . S TIUADRT=$P(TIUROOT,")")_",""ZADD"","_TIUADD_")"
"RTN","TIUPRPN1",121,0)
 . D GETSIG(TIUADRT,.TIUSIG)
"RTN","TIUPRPN1",122,0)
 . D SIGBLK^TIUPRPN8(.TIUFOOT,TIUMISC,TIUCONT1,.TIUCONT,.TIUSIG,TIUADRT)
"RTN","TIUPRPN1",123,0)
 ; Need ! in front for amended notes:
"RTN","TIUPRPN1",124,0)
 I $G(TIUIDEND) W !,"<< Interdisciplinary Note - End >>",!
"RTN","TIUPRPN1",125,0)
 K ^UTILITY($J,"W")
"RTN","TIUPRPN1",126,0)
 ; Write 2 linefeeds between records
"RTN","TIUPRPN1",127,0)
 S:$E(IOST,1,2)="C-" TIUCONT=$$STOP^TIUFLP1,TIUASK=1
"RTN","TIUPRPN1",128,0)
 W:TIUCONT !!
"RTN","TIUPRPN1",129,0)
 Q
"RTN","TIUPRPN1",130,0)
 ;
"RTN","TIUPRPN1",131,0)
IDKIDS(TIUROOT,TIUFOOT,TIUMISC,TIUCONT1,TIUCONT) ; Print ID kids
"RTN","TIUPRPN1",132,0)
 ;of docmt TIUDA (each kid does its own addenda)
"RTN","TIUPRPN1",133,0)
 N TIUL,KIDDA,TIUDA,TIUSORT,TIUIDRT,TIUIDEND
"RTN","TIUPRPN1",134,0)
 S TIUDA=$P(TIUMISC,U,3),TIUIDEND=0
"RTN","TIUPRPN1",135,0)
 S TIUL=0
"RTN","TIUPRPN1",136,0)
 F  S TIUL=$O(^TMP("TIULQ",$J,TIUDA,"ZZID",TIUL)) Q:'TIUL  D  Q:'TIUCONT
"RTN","TIUPRPN1",137,0)
 . S KIDDA=$O(^TMP("TIULQ",$J,TIUDA,"ZZID",TIUL,0))
"RTN","TIUPRPN1",138,0)
 . I +$$MEMBEROF^TIUPR222(+$G(^TIU(8925,+KIDDA,0)),"FORM LETTERS") D  Q  ; hand off to TIUFLP1 (Form Letter Print)
"RTN","TIUPRPN1",139,0)
 . . I '+$G(TIUKID),'+$G(TIUSPG) S TIUCONT1=0 S TIUCONT=$$SETCONT(.TIUFOOT,TIUMISC,TIUCONT1,1,$G(TIUROOT))
"RTN","TIUPRPN1",140,0)
 . . I 'TIUCONT!'CONT Q
"RTN","TIUPRPN1",141,0)
 . . I $E(IOST,1,2)="C-",'+TIUASK S CONT=$$STOP^TIUFLP1,TIUCONT=CONT Q:'+CONT
"RTN","TIUPRPN1",142,0)
 . . S TIUASK=0,TIUKID=1 D IDKID^TIUFLP1(TIUDA,KIDDA)
"RTN","TIUPRPN1",143,0)
 . S TIUMISC=TIUFLAG_U_TIUPFNBR_U_KIDDA
"RTN","TIUPRPN1",144,0)
 . S TIUIDRT="^TMP(""TIULQ"",$J,"_TIUDA_",""ZZID"","_TIUL_","_KIDDA_")"
"RTN","TIUPRPN1",145,0)
 . I '$O(^TMP("TIULQ",$J,TIUDA,"ZZID",TIUL)) S TIUIDEND=1
"RTN","TIUPRPN1",146,0)
 . D REPORT(TIUIDRT,.TIUFOOT,TIUMISC,.TIUCONT,TIUIDEND)
"RTN","TIUPRPN1",147,0)
 Q
"RTN","TIUPRPN1",148,0)
 ;
"RTN","TIUPRPN1",149,0)
GETSIG(TIUROOT,TIUSIG) ; Get signature info from TIULQ global;
"RTN","TIUPRPN1",150,0)
 ; Set info into TIUSIG array **100**
"RTN","TIUPRPN1",151,0)
 ; Requires array name TIUROOT; passes back array TIUSIG
"RTN","TIUPRPN1",152,0)
 ; TIUROOT = ^TMP("TIULQ",$J,NOTEIFN) for parent note, or
"RTN","TIUPRPN1",153,0)
 ;           ^TMP("TIULQ",$J,NOTEIFN,"ZADD",ADDMIFN) for addendum, or
"RTN","TIUPRPN1",154,0)
 ;           ^TMP("TIULQ",$J,NOTEIFN,"ZZID",IDKIDIFN) for ID kid.
"RTN","TIUPRPN1",155,0)
 ; Signature should be on bottom of form, Addenda on Subsequent pages
"RTN","TIUPRPN1",156,0)
 N TIULINE S $P(TIULINE,"-",81)=""
"RTN","TIUPRPN1",157,0)
 S TIUSIG("AUTHOR")=$G(@TIUROOT@(1202,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",158,0)
 S TIUSIG("EXPSIGNR")=$G(@TIUROOT@(1204,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",159,0)
 S TIUSIG("EXPCOSNR")=$G(@TIUROOT@(1208,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",160,0)
 S TIUSIG("SIGNDATE")=$G(@TIUROOT@(1501,"I"))
"RTN","TIUPRPN1",161,0)
 S TIUSIG("SIGNEDBY")=$G(@TIUROOT@(1502,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",162,0)
 S TIUSIG("SIGNNAME")=$G(@TIUROOT@(1503,"E"))
"RTN","TIUPRPN1",163,0)
 S TIUSIG("SIGTITL")=$G(@TIUROOT@(1504,"E"))
"RTN","TIUPRPN1",164,0)
 S TIUSIG("SIGNMODE")=$G(@TIUROOT@(1505,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",165,0)
 S TIUSIG("COSGDATE")=$G(@TIUROOT@(1507,"I"))
"RTN","TIUPRPN1",166,0)
 S TIUSIG("COSGEDBY")=$G(@TIUROOT@(1508,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",167,0)
 S TIUSIG("COSGNAME")=$G(@TIUROOT@(1509,"E"))
"RTN","TIUPRPN1",168,0)
 S TIUSIG("COSGTITL")=$G(@TIUROOT@(1510,"E"))
"RTN","TIUPRPN1",169,0)
 S TIUSIG("COSGMODE")=$G(@TIUROOT@(1511,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",170,0)
 S TIUSIG("SIGCHRT")=$G(@TIUROOT@(1512,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",171,0)
 S TIUSIG("COSCHRT")=$G(@TIUROOT@(1513,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",172,0)
 ; -- P182 Set Admin Clos Date:
"RTN","TIUPRPN1",173,0)
 S TIUSIG("ADMINCDT")=$G(@TIUROOT@(1606,"I"))_";"_$G(^("E"))
"RTN","TIUPRPN1",174,0)
 Q
"RTN","TIUPRPN1",175,0)
 ;
"RTN","TIUPRPN1",176,0)
SETCONT(TIUFOOT,TIUMISC,TIUCONT1,TIUHEAD,TIUROOT) ;Does footer
"RTN","TIUPRPN1",177,0)
 ;and returns TIUCONT
"RTN","TIUPRPN1",178,0)
 ; Requires array TIUFOOT, vars TIUMISC,TIUCONT1; optional TIUHEAD
"RTN","TIUPRPN1",179,0)
 ; Optional TIUROOT
"RTN","TIUPRPN1",180,0)
 Q $$FOOTER^TIUPRPN2(.TIUFOOT,TIUMISC,TIUCONT1,TIUHEAD,$G(TIUROOT))
"RTN","TIURA3")
0^3^B38623337^B23238249
"RTN","TIURA3",1,0)
TIURA3 ; SLC/JER - Review screen actions ; 11/21/07
"RTN","TIURA3",2,0)
 ;;1.0;TEXT INTEGRATION UTILITIES;**220,234**;Jun 20, 1997;Build 6
"RTN","TIURA3",3,0)
 ; Call to ISA^USRLM supported by DBIA 2324
"RTN","TIURA3",4,0)
 ; Call to ISTERM^USRLM supported by DBIA 2712
"RTN","TIURA3",5,0)
EDITCOS ; Edit Expected Cosigner
"RTN","TIURA3",6,0)
 N TIUDA,TIUDATA,TIUCHNG,TIUI,DIROUT,TIUDAARY
"RTN","TIURA3",7,0)
 N TIULST,MSGVERB,TIUXNOD
"RTN","TIURA3",8,0)
 S TIUXNOD=$G(XQORNOD(0))
"RTN","TIURA3",9,0)
 I $P(TIUXNOD,U,3)="EC" W "Edit Cosigner",! S $P(TIUXNOD,U,4)="EC="_$P($P(TIUXNOD,U,4),"==",2)
"RTN","TIURA3",10,0)
 S TIUI=0
"RTN","TIURA3",11,0)
 I '$D(VALMY) D EN^VALM2(TIUXNOD)
"RTN","TIURA3",12,0)
 F  S TIUI=$O(VALMY(TIUI)) Q:+TIUI'>0  D  Q:$D(DIROUT)
"RTN","TIURA3",13,0)
 . N RSTRCTD
"RTN","TIURA3",14,0)
 . S TIUDATA=$G(^TMP("TIURIDX",$J,TIUI))
"RTN","TIURA3",15,0)
 . D CLEAR^VALM1 W !!,"Editing #",+TIUDATA
"RTN","TIURA3",16,0)
 . S TIUDA=+$P(TIUDATA,U,2) S RSTRCTD=$$DOCRES^TIULRR(TIUDA)
"RTN","TIURA3",17,0)
 . I RSTRCTD D  Q
"RTN","TIURA3",18,0)
 . . W !!,$C(7),"Ok, no harm done...",!
"RTN","TIURA3",19,0)
 . . I $$READ^TIUU("EA","RETURN to continue...") ; pause
"RTN","TIURA3",20,0)
 . S TIUDAARY(TIUI)=TIUDA
"RTN","TIURA3",21,0)
 . S TIUCHNG=0
"RTN","TIURA3",22,0)
 . I +$D(^TIU(8925,+TIUDA,0)) D EDITCOS1
"RTN","TIURA3",23,0)
 . I +$G(TIUCHNG) D
"RTN","TIURA3",24,0)
 . . S TIULST=$G(TIULST)_$S($G(TIULST)]"":",",1:"")_TIUI
"RTN","TIURA3",25,0)
 ; -- Update or Rebuild list, restore video: --
"RTN","TIURA3",26,0)
 S TIUCHNG("UPDATE")=1
"RTN","TIURA3",27,0)
 D UPRBLD^TIURL(.TIUCHNG,.VALMY) K VALMY
"RTN","TIURA3",28,0)
 S VALMBCK="R"
"RTN","TIURA3",29,0)
 S MSGVERB="edited"
"RTN","TIURA3",30,0)
 D VMSG^TIURS1($G(TIULST),.TIUDAARY,MSGVERB)
"RTN","TIURA3",31,0)
 Q
"RTN","TIURA3",32,0)
EDITCOS1 ; Edit expected cosigner/attending for single record
"RTN","TIURA3",33,0)
 ; Receives TIUDA
"RTN","TIURA3",34,0)
 I '+$G(TIUDA) W !,"No Documents selected." H 2 Q
"RTN","TIURA3",35,0)
 ; Evaluate edit privilege
"RTN","TIURA3",36,0)
 N NODE0,STATUS,OK2CHNG,NODE12,REQCOSIG
"RTN","TIURA3",37,0)
 N ECSIGNER,ESIGNER,OKCLASS,TIUISDS,DA,DR,DIE,X
"RTN","TIURA3",38,0)
 N ALTNODE0,ALTTIUDA,NESIGNR,NECSIGNR,ATTEND,NATTEND,CHKSUM,LNO,MSGNO
"RTN","TIURA3",39,0)
 N CANDO,TIUISCP,TIUISCST,TIUISPN,MSG
"RTN","TIURA3",40,0)
 ; NECSIGNER,NATTEND etc,(N for new) means post-edit. It may not differ
"RTN","TIURA3",41,0)
 ;from the original.  It may be null if the original was null.
"RTN","TIURA3",42,0)
 S NODE0=^TIU(8925,TIUDA,0),STATUS=$P(NODE0,U,5),(OK2CHNG,OKCLASS)=1
"RTN","TIURA3",43,0)
 S ALTNODE0=NODE0,ALTTIUDA=TIUDA,NODE12=$G(^TIU(8925,TIUDA,12))
"RTN","TIURA3",44,0)
 I $$ISADDNDM^TIULC1(TIUDA) D
"RTN","TIURA3",45,0)
 . S ALTTIUDA=$P(NODE0,U,6)
"RTN","TIURA3",46,0)
 . S ALTNODE0=^TIU(8925,ALTTIUDA,0)
"RTN","TIURA3",47,0)
 S TIUISDS=$$ISDS^TIULX(+ALTNODE0),TIUISPN=$$ISPN^TIULX(+ALTNODE0)
"RTN","TIURA3",48,0)
 S TIUISCST=$$ISA^TIULX(+ALTNODE0,$$CLASS^TIUCNSLT())
"RTN","TIURA3",49,0)
 S TIUISCP=$$ISA^TIULX(+ALTNODE0,$$CLASS^TIUCP())
"RTN","TIURA3",50,0)
 I 'TIUISDS,'TIUISPN,'TIUISCST,'TIUISCP D  G COS1X
"RTN","TIURA3",51,0)
 . S MSG(1,1)="  This action is permitted only for Progress Notes, Discharge"
"RTN","TIURA3",52,0)
 . S MSG(1,2)="Summaries, Clinical Procedures and Consults."
"RTN","TIURA3",53,0)
 I STATUS>6 S MSG(2,1)="  This document has already been Completed!" G COS1X
"RTN","TIURA3",54,0)
 I STATUS<5 S MSG(3,1)="  This document still needs Release or Verification!" G COS1X
"RTN","TIURA3",55,0)
 ;  Status = 5 unsigned or 6 uncosigned:
"RTN","TIURA3",56,0)
 ;  Try rules for EDIT COSIGNER:
"RTN","TIURA3",57,0)
 S CANDO=$$CANDO^TIULP(TIUDA,"EDIT COSIGNER")
"RTN","TIURA3",58,0)
 I 'CANDO S MSG(4,1)="  "_$P(CANDO,U,2) G:STATUS=6 COS1X
"RTN","TIURA3",59,0)
 ;  If docmt is unsigned and EDIT COSIGNER rules failed,
"RTN","TIURA3",60,0)
 ;    try EDIT RECORD rules:
"RTN","TIURA3",61,0)
 I STATUS=5,'CANDO D  G:'CANDO COS1X
"RTN","TIURA3",62,0)
 . S CANDO=$$CANDO^TIULP(TIUDA,"EDIT RECORD")
"RTN","TIURA3",63,0)
 . I CANDO K MSG(4) Q
"RTN","TIURA3",64,0)
 . S MSG(5,1)="  You are not authorized to edit any aspect of this document."
"RTN","TIURA3",65,0)
 ; User authorized to change Expected Cosigner/attending:
"RTN","TIURA3",66,0)
 S DA=TIUDA,DIE=8925
"RTN","TIURA3",67,0)
 ;
"RTN","TIURA3",68,0)
 ;                **Docmt is PN, CP or Consult**
"RTN","TIURA3",69,0)
 I 'TIUISDS D  G COS1X
"RTN","TIURA3",70,0)
 . S ESIGNER=$P(NODE12,U,4)
"RTN","TIURA3",71,0)
 . S ECSIGNER=$P(NODE12,U,8)
"RTN","TIURA3",72,0)
 . I ESIGNER'>0 S MSG(6,1)="  This document has no Expected Signer!" Q
"RTN","TIURA3",73,0)
 . S REQCOSIG=$$REQCOSIG^TIULP(+NODE0,+TIUDA,ESIGNER)
"RTN","TIURA3",74,0)
 . ;
"RTN","TIURA3",75,0)
 . ;        **Cosig NOT REQUIRED:**
"RTN","TIURA3",76,0)
 . I 'REQCOSIG D  Q
"RTN","TIURA3",77,0)
 . . ;  Status Uncosigned - Do not permit completion of notes:
"RTN","TIURA3",78,0)
 . . I STATUS=6 D  Q
"RTN","TIURA3",79,0)
 . . . S MSG(7,1)="  Cosignature is not currently required. This option cannot be"
"RTN","TIURA3",80,0)
 . . . S MSG(7,2)="used to change document status to COMPLETED. It looks like the author's"
"RTN","TIURA3",81,0)
 . . . S MSG(7,3)="requirement has changed since this document was written."
"RTN","TIURA3",82,0)
 . . . S MSG(7,4)="Please contact your CAC and/or HIMS for assistance."
"RTN","TIURA3",83,0)
 . . ;  Unsigned, Has no EC:
"RTN","TIURA3",84,0)
 . . I ECSIGNER']"" S MSG(8,1)="  ?? Cosignature not required." Q
"RTN","TIURA3",85,0)
 . . ;  Unsigned, Has EC:
"RTN","TIURA3",86,0)
 . . S MSG(8,1)="  Cosignature not required. Expected Cosigner deleted."
"RTN","TIURA3",87,0)
 . . S DR="1208///@;1506///@" D ^DIE S TIUCHNG=1
"RTN","TIURA3",88,0)
 . . ;
"RTN","TIURA3",89,0)
 . ;        **Cosig REQUIRED:**
"RTN","TIURA3",90,0)
 . W !!,"  You may edit the Expected Cosigner:"
"RTN","TIURA3",91,0)
 . S DR="1208R//;1506////1" D ^DIE
"RTN","TIURA3",92,0)
 . S NECSIGNR=$P(^TIU(8925,TIUDA,12),U,8)
"RTN","TIURA3",93,0)
 . I NECSIGNR']"" D  Q
"RTN","TIURA3",94,0)
 . . S MSG(9,1)="  Cosignature is required!  Expected Cosigners cannot be alerted "
"RTN","TIURA3",95,0)
 . . S MSG(9,2)="until they are designated. "
"RTN","TIURA3",96,0)
 . . I STATUS=6 S MSG(9,3)="Please designate an Expected Cosigner as soon as possible!!"
"RTN","TIURA3",97,0)
 . I NECSIGNR=ECSIGNER D  Q
"RTN","TIURA3",98,0)
 . . W !!,"  Expected Cosigner not changed." H 1
"RTN","TIURA3",99,0)
 . W !!,"  Expected Cosigner edited." H 1 S TIUCHNG=1 Q
"RTN","TIURA3",100,0)
 ;
"RTN","TIURA3",101,0)
 ;                **Docmt is a Discharge Summary. Attending required: **
"RTN","TIURA3",102,0)
 S ATTEND=$P($G(^TIU(8925,TIUDA,12)),U,9)
"RTN","TIURA3",103,0)
 W !!,"You may edit the Attending Physician:"
"RTN","TIURA3",104,0)
 S DR="1209R//" D ^DIE
"RTN","TIURA3",105,0)
 S NATTEND=$P(^TIU(8925,TIUDA,12),U,9)
"RTN","TIURA3",106,0)
 S MSG("ALERT")="  Attendings cannot be alerted until designated!"
"RTN","TIURA3",107,0)
 I NATTEND']0 S MSG(1,1)="  Attending is Required!",MSG(1,2)=MSG("ALERT") G COS1X
"RTN","TIURA3",108,0)
 ;  NATTEND is not null. Does it pass screen from TIU*1*219?
"RTN","TIURA3",109,0)
 ;  (Needed even after 219 for ^ or Return with no Attending)
"RTN","TIURA3",110,0)
 ;  Overwrite most likely msgs with least likely:
"RTN","TIURA3",111,0)
 I +$$REQCOSIG^TIULP(+NODE0,+TIUDA,NATTEND) S MSG(2,1)="  This person requires a cosignature. Please select a different Attending.",MSG(2,2)=MSG("ALERT")
"RTN","TIURA3",112,0)
 I '$$ISA^USRLM(NATTEND,"PROVIDER") D
"RTN","TIURA3",113,0)
 . K MSG(2)
"RTN","TIURA3",114,0)
 . S MSG(2,1)="  This person is not in User Class PROVIDER.  Please check User "
"RTN","TIURA3",115,0)
 . S MSG(2,2)="Class or select a different Attending."
"RTN","TIURA3",116,0)
 . S MSG(2,3)=MSG("ALERT")
"RTN","TIURA3",117,0)
 I $$ISTERM^USRLM(NATTEND) K MSG(2) S MSG(2,1)="  This person is terminated! Please select a different Attending.",MSG(2,2)=MSG("ALERT")
"RTN","TIURA3",118,0)
 ; Att fails. Restore old att:
"RTN","TIURA3",119,0)
 I $D(MSG(2)) D  G COS1X
"RTN","TIURA3",120,0)
 . S X=$S((STATUS=5)&(ATTEND']""):"@",1:ATTEND),DR="1209////" D ^DIE
"RTN","TIURA3",121,0)
 ; Attending exists and is good:
"RTN","TIURA3",122,0)
 S NESIGNR=$$WHOSIGNS^TIULC1(DA),NECSIGNR=$$WHOCOSIG^TIULC1(DA)
"RTN","TIURA3",123,0)
 S DR="1204////^S X=NESIGNR"
"RTN","TIURA3",124,0)
 S DR=DR_";1208////^S X=NECSIGNR"
"RTN","TIURA3",125,0)
 S DR=DR_";1506////^S X=$S(+NESIGNR=+NATTEND:0,1:1)"
"RTN","TIURA3",126,0)
 D ^DIE
"RTN","TIURA3",127,0)
 I NATTEND=ATTEND D  G COS1X
"RTN","TIURA3",128,0)
 . W !!,"  Attending Physician not changed." H 1
"RTN","TIURA3",129,0)
 ; New Attend Changed - Go on to audit
"RTN","TIURA3",130,0)
 W !!,"  Attending Physician edited." S TIUCHNG=1 H 1
"RTN","TIURA3",131,0)
COS1X ;
"RTN","TIURA3",132,0)
 I $G(TIUCHNG) D
"RTN","TIURA3",133,0)
 . D SEND^TIUALRT(TIUDA)
"RTN","TIURA3",134,0)
 . Q:$G(STATUS)'=6  D  ; Audit uncosigned docmts only
"RTN","TIURA3",135,0)
 . S CHKSUM=+$$CHKSUM^TIULC("^TIU(8925,"_+TIUDA_",""TEXT"")")
"RTN","TIURA3",136,0)
 . D AUDIT^TIUEDI1(TIUDA,CHKSUM,CHKSUM)
"RTN","TIURA3",137,0)
 I $D(MSG) W ! F MSGNO=1:1:9 D
"RTN","TIURA3",138,0)
 . F LNO=1:1:10 Q:'$D(MSG(MSGNO,LNO))  W !,MSG(MSGNO,LNO)
"RTN","TIURA3",139,0)
 I $D(MSG),$$READ^TIUU("EA","RETURN to continue...")
"RTN","TIURA3",140,0)
 Q
"RTN","TIURB")
0^6^B46724354^B44977489
"RTN","TIURB",1,0)
TIURB ; SLC/JER - More Review Screen Actions ;12/11/07
"RTN","TIURB",2,0)
 ;;1.0;TEXT INTEGRATION UTILITIES;**4,32,52,78,58,100,109,155,184,234**;Jun 20, 1997;Build 6
"RTN","TIURB",3,0)
 ; DBIA 3473 TIU use of GMRCTIU
"RTN","TIURB",4,0)
AMEND ; Amendment action
"RTN","TIURB",5,0)
 N TIUDA,DFN,DIE,DR,TIU,TIUDATA,TIUI,TIUSIG,TIUY,X,X1,Y
"RTN","TIURB",6,0)
 N DIROUT,TIUCHNG,TIUDAARY,TIULST
"RTN","TIURB",7,0)
 I '$D(VALMY) D EN^VALM2(XQORNOD(0))
"RTN","TIURB",8,0)
 S TIUI=0
"RTN","TIURB",9,0)
 F  S TIUI=$O(VALMY(TIUI)) Q:+TIUI'>0  D  Q:$D(DIROUT)
"RTN","TIURB",10,0)
 . N RSTRCTD
"RTN","TIURB",11,0)
 . S TIUDATA=$G(^TMP("TIURIDX",$J,TIUI))
"RTN","TIURB",12,0)
 . S TIUDA=+$P(TIUDATA,U,2) S RSTRCTD=$$DOCRES^TIULRR(TIUDA)
"RTN","TIURB",13,0)
 . I RSTRCTD D  Q
"RTN","TIURB",14,0)
 . . W !!,$C(7),"Ok, no harm done...",! ; Echo denial message
"RTN","TIURB",15,0)
 . . I $$READ^TIUU("EA","RETURN to continue...") ; pause
"RTN","TIURB",16,0)
 . W !!,"Amending #",+TIUDATA
"RTN","TIURB",17,0)
 . S TIUCHNG=0
"RTN","TIURB",18,0)
 . D AMEND1
"RTN","TIURB",19,0)
 . I $G(TIUDAARY(TIUI)) D
"RTN","TIURB",20,0)
 . . S TIULST=$G(TIULST)_$S($G(TIULST)]"":",",1:"")_TIUI
"RTN","TIURB",21,0)
 ; -- Update or Rebuild list, restore video:
"RTN","TIURB",22,0)
 D UPRBLD^TIURL(.TIUCHNG,.VALMY) K VALMY
"RTN","TIURB",23,0)
 S VALMBCK="R"
"RTN","TIURB",24,0)
 D VMSG^TIURS1($G(TIULST),.TIUDAARY,"amended")
"RTN","TIURB",25,0)
 Q
"RTN","TIURB",26,0)
AMEND1 ; Single record amend
"RTN","TIURB",27,0)
 N TIUCMT,TIUT0,TIUTYP,TIUAMND,TIUSNM,TIUSBLK,TIUCSNM,TIUCSBLK,DIE,DR
"RTN","TIURB",28,0)
 N DA,DFN,DIWESUB,TIU,TIUODA,TIUTITL,TIUCLSS,TIUCON,TIUCNSLT,TIUPRF,TIUFLAG
"RTN","TIURB",29,0)
 K ^TMP("TIURTRCT",$J)
"RTN","TIURB",30,0)
 ; TIU*155 Gets consult data if exists
"RTN","TIURB",31,0)
 S TIUTITL=$P($G(^TIU(8925,TIUDA,0)),U)
"RTN","TIURB",32,0)
 S TIUCLSS=$$CLASS^TIUCNSLT()
"RTN","TIURB",33,0)
 S TIUCON=+$$ISA^TIULX(TIUTITL,TIUCLSS)
"RTN","TIURB",34,0)
 S TIUCNSLT=+$P($G(^TIU(8925,TIUDA,14)),U,5)
"RTN","TIURB",35,0)
 S TIUPRF=0,TIUFLAG=0
"RTN","TIURB",36,0)
 D ISPRFTTL^TIUPRF2(.TIUPRF,TIUTITL)
"RTN","TIURB",37,0)
 I TIUPRF S TIUFLAG=$$FNDACTIF^TIUPRFL(TIUDA)
"RTN","TIURB",38,0)
 L +^TIU(8925,+TIUDA):1
"RTN","TIURB",39,0)
 E  D  Q
"RTN","TIURB",40,0)
 . W !?5,$C(7),"Another user is editing this entry." H 3
"RTN","TIURB",41,0)
 . S TIUCHNG("REFRESH")=1
"RTN","TIURB",42,0)
 I +$P($G(^TIU(8925,+TIUDA,0)),U,5)'>6 D  Q
"RTN","TIURB",43,0)
 . W !?5,$C(7),"Only SIGNED Documents may be amended."
"RTN","TIURB",44,0)
 . I $$READ^TIUU("EA","Press RETURN to continue...") ; pause
"RTN","TIURB",45,0)
 . S TIUCHNG("REFRESH")=1
"RTN","TIURB",46,0)
 I '$$ISA^USRLM(+$G(DUZ),"PRIVACY ACT OFFICER"),'$$ISA^USRLM(+$G(DUZ),"CHIEF, MIS"),'$$ISA^USRLM(+$G(DUZ),"CHIEF, HIM") D  Q
"RTN","TIURB",47,0)
 . W !?5,$C(7),"Only Privacy Act Officers or MIS/HIM Chiefs may amend documents."
"RTN","TIURB",48,0)
 . I $$READ^TIUU("EA","Press RETURN to continue...") ; pause
"RTN","TIURB",49,0)
 . S TIUCHNG("REFRESH")=1
"RTN","TIURB",50,0)
 I +$$HASIMG^TIURB2(TIUDA) D IMGNOTE^TIURB2 Q
"RTN","TIURB",51,0)
 ;S TIUAMND=$$CANDO^TIULP(TIUDA,"AMENDMENT")
"RTN","TIURB",52,0)
 ;I +TIUAMND'>0 D  Q
"RTN","TIURB",53,0)
 ;. W !!,$C(7),$C(7),$C(7),$P(TIUAMND,U,2),!
"RTN","TIURB",54,0)
 ;. S TIUCHNG("REFRESH")=1
"RTN","TIURB",55,0)
 ;. I $$READ^TIUU("EA","Press RETURN to continue...") ; pause
"RTN","TIURB",56,0)
 W !!,"Before proceeding, please enter your Electronic Signature Code..."
"RTN","TIURB",57,0)
 S TIUAMND=$$GETSIG^TIURD2
"RTN","TIURB",58,0)
 I +TIUAMND'>0 D  Q
"RTN","TIURB",59,0)
 . W !!,"  Ok, no harm done...",!
"RTN","TIURB",60,0)
 . S TIUCHNG("REFRESH")=1
"RTN","TIURB",61,0)
 . I $$READ^TIUU("EA","Press RETURN to continue...") ; pause
"RTN","TIURB",62,0)
 W !!,"The ORIGINAL document will be RETRACTED, and a copy will be amended...",!
"RTN","TIURB",63,0)
 S TIUODA=TIUDA
"RTN","TIURB",64,0)
 S TIUDA=+$$RETRACT^TIURD2(TIUDA,"",7)
"RTN","TIURB",65,0)
 I '+TIUDA D  Q
"RTN","TIURB",66,0)
 . W !!,$C(7),$C(7),$C(7),"Retraction of Original Document Failed.",!
"RTN","TIURB",67,0)
 . I $$READ^TIUU("EA","Press RETURN to continue...") ; pause
"RTN","TIURB",68,0)
 . S TIUDA=TIUODA,TIUCHNG("REFRESH")=1
"RTN","TIURB",69,0)
 L +^TIU(8925,TIUDA):1
"RTN","TIURB",70,0)
 E  D  Q
"RTN","TIURB",71,0)
 . W !?5,$C(7),"Another user is editing this entry."
"RTN","TIURB",72,0)
 . D RECOVER^TIURD4(TIUODA,TIUDA) H 3
"RTN","TIURB",73,0)
 . S TIUPRF=$$LINK^TIUPRF1(TIUODA,+TIUFLAG,$P(TIUFLAG,U,2),$P($G(^TIU(8925,TIUODA,0)),U,2))
"RTN","TIURB",74,0)
 . S TIUDA=TIUODA,TIUCHNG("REFRESH")=1
"RTN","TIURB",75,0)
 S TIUSNM=$$DECRYPT^TIULC1($P(^TIU(8925,TIUDA,15),U,3),1,$$CHKSUM^TIULC("^TIU(8925,"_TIUDA_",""TEXT"")"))
"RTN","TIURB",76,0)
 S TIUSBLK=$$DECRYPT^TIULC1($P($G(^TIU(8925,TIUDA,15)),U,4),1,$$CHKSUM^TIULC("^TIU(8925,"_TIUDA_",""TEXT"")"))
"RTN","TIURB",77,0)
 S TIUCSNM=$$DECRYPT^TIULC1($P(^TIU(8925,TIUDA,15),U,9),1,$$CHKSUM^TIULC("^TIU(8925,"_TIUDA_",""TEXT"")"))
"RTN","TIURB",78,0)
 S TIUCSBLK=$$DECRYPT^TIULC1($P($G(^TIU(8925,TIUDA,15)),U,10),1,$$CHKSUM^TIULC("^TIU(8925,"_TIUDA_",""TEXT"")"))
"RTN","TIURB",79,0)
 S TIUTYP=+$G(^TIU(8925,+TIUDA,0)),TIUT0=$G(^TIU(8925.1,+TIUTYP,0))
"RTN","TIURB",80,0)
 S TIUTYP(1)="1^"_+TIUTYP_U_$P(TIUT0,U,3)_U
"RTN","TIURB",81,0)
 S DFN=$P($G(^TIU(8925,+TIUDA,0)),U,2)
"RTN","TIURB",82,0)
 D GETTIU^TIULD(.TIU,TIUDA)
"RTN","TIURB",83,0)
 S DIWESUB="Patient: "_$G(TIU("PNM"))
"RTN","TIURB",84,0)
 S TIUCHNG=0 D FULL^VALM1,TEXTEDIT^TIUEDI4(TIUDA,.TIUCMT,.TIUCHNG)
"RTN","TIURB",85,0)
 I '+$G(TIUCHNG) D  Q
"RTN","TIURB",86,0)
 . L -^TIU(8925,TIUDA)
"RTN","TIURB",87,0)
 . D RECOVER^TIURD4(TIUODA,TIUDA)
"RTN","TIURB",88,0)
 . S TIUPRF=$$LINK^TIUPRF1(TIUODA,+TIUFLAG,$P(TIUFLAG,U,2),$P($G(^TIU(8925,TIUODA,0)),U,2))
"RTN","TIURB",89,0)
 . L -^TIU(8925,TIUODA) H 3
"RTN","TIURB",90,0)
 . S TIUDA=TIUODA,TIUCHNG("REFRESH")=1
"RTN","TIURB",91,0)
 I +$G(TIUCHNG) D
"RTN","TIURB",92,0)
 . S DR=".05///AMENDED;1601////"_$$NOW^XLFDT_";1602////"_DUZ,DA=TIUDA,TIUSIG=0
"RTN","TIURB",93,0)
 . S DR=DR_";1603////"_$$NOW^XLFDT_";1604///^S X=$$SIGNAME^TIULS(DUZ);1605///^S X=$$SIGTITL^TIULS(DUZ)",TIUSIG=1
"RTN","TIURB",94,0)
 . S DIE=8925 D ^DIE
"RTN","TIURB",95,0)
 . ; Refile /es/-block fields
"RTN","TIURB",96,0)
 . S DR="1503///^S X=TIUSNM;1504///^S X=TIUSBLK;1509///^S X=TIUCSNM;1510///^S X=TIUCSBLK"
"RTN","TIURB",97,0)
 . D ^DIE
"RTN","TIURB",98,0)
 ; Drop Locks on both documents
"RTN","TIURB",99,0)
 L -^TIU(8925,+TIUDA)
"RTN","TIURB",100,0)
 L -^TIU(8925,+TIUODA)
"RTN","TIURB",101,0)
 S TIUDAARY(TIUI)=TIUDA
"RTN","TIURB",102,0)
 S TIUCHNG("RBLD")=1
"RTN","TIURB",103,0)
 ; if note is associated with a patient record flag - clean up
"RTN","TIURB",104,0)
 I +TIUFLAG S TIUPRF=$$LINK^TIUPRF1(TIUDA,+TIUFLAG,$P(TIUFLAG,U,2),$P($G(^TIU(8925,TIUDA,0)),U,2))
"RTN","TIURB",105,0)
 ; TIU*155 If note is associated with a consult update ^GMR global
"RTN","TIURB",106,0)
 ; to include the amended note
"RTN","TIURB",107,0)
 ; Rollback retracted note from ^GMR(123 node 50
"RTN","TIURB",108,0)
 I $G(TIUCON)=1 D
"RTN","TIURB",109,0)
 . N STATUS,GMRCSTAT,TIUAUTH
"RTN","TIURB",110,0)
 . S STATUS=$P($G(^TIU(8925,TIUDA,0)),U,5)
"RTN","TIURB",111,0)
 . S GMRCSTAT=$S(STATUS>6:"COMPLETED",1:"INCOMPLETE")
"RTN","TIURB",112,0)
 . S TIUAUTH=$P($G(^TIU(8925,TIUDA,12)),U,2)
"RTN","TIURB",113,0)
 . D ROLLBACK^TIUCNSLT(TIUODA)
"RTN","TIURB",114,0)
 . D GET^GMRCTIU(TIUCNSLT,TIUDA,GMRCSTAT,TIUAUTH)
"RTN","TIURB",115,0)
 Q
"RTN","TIURB",116,0)
SENDBACK ; Send back a Document to transcription
"RTN","TIURB",117,0)
 N TIUDA,DFN,TIU,TIUDATA,TIUCHNG,TIUI,TIUY,Y,DIROUT,TIULST
"RTN","TIURB",118,0)
 N TIUDAARY
"RTN","TIURB",119,0)
 I '$D(VALMY) D EN^VALM2(XQORNOD(0))
"RTN","TIURB",120,0)
 S TIUI=0
"RTN","TIURB",121,0)
 I +$O(VALMY(0)) D CLEAR^VALM1
"RTN","TIURB",122,0)
 F  S TIUI=$O(VALMY(TIUI)) Q:+TIUI'>0  D  Q:$D(DIROUT)
"RTN","TIURB",123,0)
 . N TIU,RSTRCTD
"RTN","TIURB",124,0)
 . S TIUDATA=$G(^TMP("TIURIDX",$J,TIUI))
"RTN","TIURB",125,0)
 . S TIUDA=+$P(TIUDATA,U,2) S RSTRCTD=$$DOCRES^TIULRR(TIUDA)
"RTN","TIURB",126,0)
 . I RSTRCTD D  Q
"RTN","TIURB",127,0)
 . . W !!,$C(7),"Ok, no harm done...",! ; Echo denial message
"RTN","TIURB",128,0)
 . . I $$READ^TIUU("EA","RETURN to continue...") ; pause
"RTN","TIURB",129,0)
 . S TIUDAARY(TIUI)=TIUDA
"RTN","TIURB",130,0)
 . S TIUCHNG=0
"RTN","TIURB",131,0)
 . D EN^VALM("TIU SEND BACK")
"RTN","TIURB",132,0)
 . I +$G(TIUCHNG) D
"RTN","TIURB",133,0)
 . . S TIULST=$G(TIULST)_$S($G(TIULST)]"":",",1:"")_TIUI
"RTN","TIURB",134,0)
SENDX ; Revise list and cycle back as appropriate
"RTN","TIURB",135,0)
 I $G(TIUCHNG("ADDM"))!$G(TIUCHNG("DELETE")) S TIUCHNG("RBLD")=1
"RTN","TIURB",136,0)
 E  S TIUCHNG("UPDATE")=1
"RTN","TIURB",137,0)
 D UPRBLD^TIURL(.TIUCHNG,.VALMY) K VALMY
"RTN","TIURB",138,0)
 S VALMBCK="R"
"RTN","TIURB",139,0)
 D VMSG^TIURS1($G(TIULST),.TIUDAARY,"sent back")
"RTN","TIURB",140,0)
 Q
"RTN","TIURB",141,0)
LINK ; Link to problem(s)
"RTN","TIURB",142,0)
 N TIUCHNG,TIUDA,DFN,TIU,TIUDATA,TIUEDIT,TIUI,TIUY,TIULST,Y,DIROUT
"RTN","TIURB",143,0)
 N TIUDAARY
"RTN","TIURB",144,0)
 I '$D(VALMY) D EN^VALM2(XQORNOD(0))
"RTN","TIURB",145,0)
 S TIUI=0
"RTN","TIURB",146,0)
 I +$O(VALMY(0)) D CLEAR^VALM1
"RTN","TIURB",147,0)
 F  S TIUI=$O(VALMY(TIUI)) Q:+TIUI'>0  D  Q:$D(DIROUT)
"RTN","TIURB",148,0)
 . N TIU,VALMY,XQORM,VA,VADM,GMPDFN,GMPLUSER,RSTRCTD
"RTN","TIURB",149,0)
 . S TIUDATA=$G(^TMP("TIURIDX",$J,TIUI))
"RTN","TIURB",150,0)
 . S TIUDA=+$P(TIUDATA,U,2),GMPLUSER=1
"RTN","TIURB",151,0)
 . I '$D(^TIU(8925,+TIUDA,0)) D  Q
"RTN","TIURB",152,0)
 . . W !,$C(7),"Document no longer exists.",!
"RTN","TIURB",153,0)
 . . I $$READ^TIUU("EA","Press RETURN to continue...") W ""
"RTN","TIURB",154,0)
 . S RSTRCTD=$$DOCRES^TIULRR(TIUDA)
"RTN","TIURB",155,0)
 . I RSTRCTD D  Q
"RTN","TIURB",156,0)
 . . W !!,$C(7),"Ok, no harm done...",! ; Echo denial message
"RTN","TIURB",157,0)
 . . I $$READ^TIUU("EA","RETURN to continue...") ; pause
"RTN","TIURB",158,0)
 . S TIUDAARY(TIUI)=TIUDA
"RTN","TIURB",159,0)
 . S DFN=+$P($G(^TIU(8925,+TIUDA,0)),U,2)
"RTN","TIURB",160,0)
 . I +DFN D DEM^VADPT S GMPDFN=DFN_U_VADM(1)_U_$E(VADM(1))_VA("BID")
"RTN","TIURB",161,0)
 . S TIUCHNG=0
"RTN","TIURB",162,0)
 . D EN^VALM("TIU LINK TO PROBLEM")
"RTN","TIURB",163,0)
 . I +$G(TIUCHNG) S TIULST=$G(TIULST)_$S($G(TIULST)]"":",",1:"")_TIUI
"RTN","TIURB",164,0)
LINKX ; Revise list and cycle back as appropriate
"RTN","TIURB",165,0)
 S TIUCHNG("REFRESH")=1
"RTN","TIURB",166,0)
 D UPRBLD^TIURL(.TIUCHNG,.VALMY) K VALMY
"RTN","TIURB",167,0)
 S VALMBCK="R"
"RTN","TIURB",168,0)
 D VMSG^TIURS1($G(TIULST),.TIUDAARY,"linked to problems")
"RTN","TIURB",169,0)
 Q
"RTN","TIURB",170,0)
DEL(DA) ; -- Call to DEL for backward compatibility
"RTN","TIURB",171,0)
 G GODEL^TIURB2
"RTN","TIURB",172,0)
 Q
"RTN","TIUSRVA")
0^2^B23503804^B22071569
"RTN","TIUSRVA",1,0)
TIUSRVA ; SLC/JER,AJB - API's for Authorization ; 11/13/07
"RTN","TIUSRVA",2,0)
 ;;1.0;TEXT INTEGRATION UTILITIES;**19,28,47,80,100,116,152,160,178,175,157,236,234**;Jun 20, 1997;Build 6
"RTN","TIUSRVA",3,0)
 ;
"RTN","TIUSRVA",4,0)
 ;External reference to File ^AUPNVSIT supported by DBIA 3580
"RTN","TIUSRVA",5,0)
REQCOS(TIUY,TIUTYP,TIUDA,TIUSER,TIUDT) ; Evaluate cosignature requirement
"RTN","TIUSRVA",6,0)
 ; Initialize return value
"RTN","TIUSRVA",7,0)
 N TIUDPRM
"RTN","TIUSRVA",8,0)
 S TIUY=0
"RTN","TIUSRVA",9,0)
 I +$G(TIUTYP)'>0,'+$G(TIUDA) Q
"RTN","TIUSRVA",10,0)
 I +$G(TIUDA) S TIUTYP=+$G(^TIU(8925,+$G(TIUDA),0))
"RTN","TIUSRVA",11,0)
 S:'+$G(TIUSER) TIUSER=+$G(DUZ)
"RTN","TIUSRVA",12,0)
 S TIUY=+$$REQCOSIG^TIULP(TIUTYP,+$G(TIUDA),+$G(TIUSER),+$G(TIUDT))
"RTN","TIUSRVA",13,0)
 Q
"RTN","TIUSRVA",14,0)
URGENCY(TIUY) ; -- retrieve set values from dd for discharge summary urgency
"RTN","TIUSRVA",15,0)
 N TIUDD,TIUI,TIUX
"RTN","TIUSRVA",16,0)
 D FIELD^DID(8925,.09,"","POINTER","TIUDD")
"RTN","TIUSRVA",17,0)
 F TIUI=1:1 S TIUX=$P(TIUDD("POINTER"),";",TIUI) Q:TIUX=""   S TIUY(TIUI)=$TR(TIUX,":","^")
"RTN","TIUSRVA",18,0)
 Q
"RTN","TIUSRVA",19,0)
CANDO(TIUY,TIUDA,TIUACT) ; Boolean function to evaluate privilege
"RTN","TIUSRVA",20,0)
 N TIUPOP,TIUDPRM S TIUPOP=0
"RTN","TIUSRVA",21,0)
 ; **152** prevent editing completed [uncosigned] documents.
"RTN","TIUSRVA",22,0)
 I $P($G(^TIU(8925,TIUDA,0)),U,5)>5,(TIUACT="EDIT RECORD") S TIUY="0^ You may not edit uncosigned or completed documents" Q
"RTN","TIUSRVA",23,0)
 I $S(TIUACT["SIGN":1,TIUACT="EDIT RECORD":1,TIUACT="DELETE RECORD":1,1:0) D  Q:+TIUPOP=1
"RTN","TIUSRVA",24,0)
 . L +^TIU(8925,+TIUDA):1
"RTN","TIUSRVA",25,0)
 . E  S TIUY="0^ Another session is editing this entry.",TIUPOP=1
"RTN","TIUSRVA",26,0)
 . L -^TIU(8925,+TIUDA)
"RTN","TIUSRVA",27,0)
 I TIUACT["SIGN",+$$NEEDCS(TIUDA) S TIUY="0^ You must name a cosigner before signing this document." Q
"RTN","TIUSRVA",28,0)
 S TIUY=$$CANDO^TIULP(TIUDA,TIUACT)
"RTN","TIUSRVA",29,0)
 Q
"RTN","TIUSRVA",30,0)
NEEDCS(TIUDA) ; Does user need a cosigner?
"RTN","TIUSRVA",31,0)
 N TIUD0,TIUD12,TIUY,SIGNER,COSIGNER,XTRASGNR
"RTN","TIUSRVA",32,0)
 S TIUD0=$G(^TIU(8925,TIUDA,0)),TIUD12=$G(^(12))
"RTN","TIUSRVA",33,0)
 S SIGNER=$P(TIUD12,U,4),COSIGNER=$P(TIUD12,U,8),XTRASGNR=0
"RTN","TIUSRVA",34,0)
 I (DUZ'=SIGNER),(DUZ'=COSIGNER) S XTRASGNR=+$O(^TIU(8925.7,"AE",+TIUDA,+DUZ,0))
"RTN","TIUSRVA",35,0)
 I +XTRASGNR S TIUY=0
"RTN","TIUSRVA",36,0)
 E  I +$$REQCOSIG^TIULP(+TIUD0,TIUDA,DUZ),(+$P(TIUD12,U,8)'>0) S TIUY=1
"RTN","TIUSRVA",37,0)
 Q +$G(TIUY)
"RTN","TIUSRVA",38,0)
USRINACT(TIUY,TIUDA) ; Is user inactive?
"RTN","TIUSRVA",39,0)
 S TIUY=+$$GET1^DIQ(200,TIUDA_",",7,"I")
"RTN","TIUSRVA",40,0)
 Q
"RTN","TIUSRVA",41,0)
AUTHSIGN(TIUY,TIUDA,TIUUSR) ; Has Author signed?
"RTN","TIUSRVA",42,0)
 ; if TIUY = 
"RTN","TIUSRVA",43,0)
 ; 0 = Author has NOT signed & TIUUSR = Expected Cosigner
"RTN","TIUSRVA",44,0)
 ; 1 = Author HAS signed or TIUUSR '= Expected Cosigner
"RTN","TIUSRVA",45,0)
 ;
"RTN","TIUSRVA",46,0)
 N TIUD12,TIUD15
"RTN","TIUSRVA",47,0)
 S TIUD12=$G(^TIU(8925,TIUDA,12)),TIUD15=$G(^(15))
"RTN","TIUSRVA",48,0)
 S TIUY=1
"RTN","TIUSRVA",49,0)
 D:$P(TIUD12,U,8)=TIUUSR  Q
"RTN","TIUSRVA",50,0)
 . S:$P(TIUD12,U,2)'=$P(TIUD15,U,2) TIUY=0
"RTN","TIUSRVA",51,0)
 Q
"RTN","TIUSRVA",52,0)
TIUVISIT(TIUY,DOCTYP,DFN,VISIT) ;  Check for a 1 time only doc
"RTN","TIUSRVA",53,0)
 ;  TIUY    =    return value
"RTN","TIUSRVA",54,0)
 ;          = 0 if can add more than one or none already exist
"RTN","TIUSRVA",55,0)
 ;          = 1 if cannot add more than one and one already exists
"RTN","TIUSRVA",56,0)
 ;  DOCTYP  =    Pointer to ^TUI(8925.1,   TIU DOCUMENT DEFINITION
"RTN","TIUSRVA",57,0)
 ;  DFN     =    Patient IEN
"RTN","TIUSRVA",58,0)
 ;  VISIT   =    Visit String "LOC;VDATE;VTYP"
"RTN","TIUSRVA",59,0)
 I $$PATCH^XPDUTL("OR*3.0*195") D
"RTN","TIUSRVA",60,0)
 . Q:($G(DOCTYP)="")!($G(DFN)="")!($G(VISIT)="")
"RTN","TIUSRVA",61,0)
 . N TIUDPRM,TIUTEST
"RTN","TIUSRVA",62,0)
 . D DOCPRM^TIULC1(DOCTYP,.TIUDPRM)
"RTN","TIUSRVA",63,0)
 . S TIUY=$S($P(TIUDPRM(0),U,10)="":1,1:$P(TIUDPRM(0),U,10))
"RTN","TIUSRVA",64,0)
 . I TIUY=1 S TIUY=0 Q
"RTN","TIUSRVA",65,0)
 . I $L(VISIT,";")=3 D
"RTN","TIUSRVA",66,0)
 . . S TIUTEST=$$EXIST^TIUEDI3(DFN,DOCTYP,VISIT)
"RTN","TIUSRVA",67,0)
 . . I TIUTEST S TIUY=1
"RTN","TIUSRVA",68,0)
 . . I 'TIUTEST S TIUY=0
"RTN","TIUSRVA",69,0)
 I '$$PATCH^XPDUTL("OR*3.0*195") D
"RTN","TIUSRVA",70,0)
 . Q:($G(DOCTYP)="")!($G(DFN)="")!($G(VISIT)="")
"RTN","TIUSRVA",71,0)
 . N TIUX3
"RTN","TIUSRVA",72,0)
 . S TIUX3=+$O(^TIU(8925.95,"B",DOCTYP,""))
"RTN","TIUSRVA",73,0)
 . S TIUY=$P($G(^TIU(8925.95,TIUX3,0)),U,10) S TIUY=$S(TIUY=0:1,1:0)
"RTN","TIUSRVA",74,0)
 . Q:'TIUY
"RTN","TIUSRVA",75,0)
 . S VISIT=((9999999-$P(VISIT,"."))_"."_$P(VISIT,".",2))
"RTN","TIUSRVA",76,0)
 . S VISIT=+$O(^AUPNVSIT("AA",DFN,VISIT,""))
"RTN","TIUSRVA",77,0)
 . S TIUY=$S($D(^TIU(8925,"AV",DFN,DOCTYP,VISIT)):0,1:1)
"RTN","TIUSRVA",78,0)
 . S TIUY=$S(TIUY=0:1,1:0)
"RTN","TIUSRVA",79,0)
 Q
"RTN","TIUSRVA",80,0)
WHATACT(TIUY,TIUDA) ; Evaluate/return whether signature or cosignature
"RTN","TIUSRVA",81,0)
 N TIUD0,TIUD12,TIUSTAT,SIGNER,COSIGNER,XTRASGNR
"RTN","TIUSRVA",82,0)
 S TIUD0=$G(^TIU(8925,+TIUDA,0)),TIUD12=$G(^TIU(8925,+TIUDA,12))
"RTN","TIUSRVA",83,0)
 S SIGNER=$P(TIUD12,U,4),COSIGNER=$P(TIUD12,U,8)
"RTN","TIUSRVA",84,0)
 I (DUZ'=SIGNER),(DUZ'=COSIGNER) S XTRASGNR=+$O(^TIU(8925.7,"AE",+TIUDA,+DUZ,0))
"RTN","TIUSRVA",85,0)
 I '$G(XTRASGNR) S XTRASGNR=$$ASURG^TIUADSIG(TIUDA)
"RTN","TIUSRVA",86,0)
 S TIUSTAT=+$P(TIUD0,U,5)
"RTN","TIUSRVA",87,0)
 S TIUY=$S(TIUSTAT'>5:"SIGNATURE",+$G(XTRASGNR):"SIGNATURE",1:"COSIGNATURE")
"RTN","TIUSRVA",88,0)
 Q
"RTN","TIUSRVA",89,0)
CANCHCOS(TIUY,TIUDA) ; Evaluate/return whether user can change cosigner
"RTN","TIUSRVA",90,0)
 S TIUY=$$MAYCHNG^TIURA1(TIUDA)
"RTN","TIUSRVA",91,0)
 Q
"RTN","TIUSRVA",92,0)
NEEDJUST(TIUY,TIUDA) ; Is justification required for deletion?
"RTN","TIUSRVA",93,0)
 N TIUD0 S TIUD0=$G(^TIU(8925,+TIUDA,0)),TIUY=0
"RTN","TIUSRVA",94,0)
 I +$P(TIUD0,U,5)'<6 S TIUY=1
"RTN","TIUSRVA",95,0)
 Q
"RTN","TIUSRVA",96,0)
GETTITLE(TIUY,TIUDA) ; Get the title from a TIU Document Record
"RTN","TIUSRVA",97,0)
 S TIUY=+$G(^TIU(8925,+TIUDA,0))
"RTN","TIUSRVA",98,0)
 Q
"RTN","TIUSRVA",99,0)
CANATTCH(TIUY,TIUDA) ; Can this document be attached as an ID Child
"RTN","TIUSRVA",100,0)
 N TITLEDA,PARENTDA
"RTN","TIUSRVA",101,0)
 S TITLEDA=+$G(^TIU(8925,TIUDA,0))
"RTN","TIUSRVA",102,0)
 I TITLEDA'>0 S TIUY="0^Document #"_TIUDA_" does not exist." Q
"RTN","TIUSRVA",103,0)
 S PARENTDA=+$G(^TIU(8925,TIUDA,21))
"RTN","TIUSRVA",104,0)
 S TIUY=$$POSSPRNT^TIULP(TITLEDA)
"RTN","TIUSRVA",105,0)
 I +TIUY S TIUY="-1"_U_$P(TIUY,U,2) Q
"RTN","TIUSRVA",106,0)
 I +$$ISCWAD^TIULX(TITLEDA) D  Q
"RTN","TIUSRVA",107,0)
 . S TIUY="0^ CWAD Documents may not be Attached as Interdisciplinary Entries."
"RTN","TIUSRVA",108,0)
 I +$$ISA^TIULX(TITLEDA,+$$CLASS^TIUCNSLT) D  Q
"RTN","TIUSRVA",109,0)
 . S TIUY="0^ Consult Results may not be Attached as Interdisciplinary Entries."
"RTN","TIUSRVA",110,0)
 S TIUY=$$CANDO^TIULP(TIUDA,"ATTACH TO ID NOTE")
"RTN","TIUSRVA",111,0)
 I PARENTDA D  ; action must be "detach"
"RTN","TIUSRVA",112,0)
 . I 'TIUY S TIUY="0^ You may not detach this note from an interdisciplinary note." Q
"RTN","TIUSRVA",113,0)
 . S TIUY=$$CANDO^TIULP(PARENTDA,"ATTACH ID ENTRY")
"RTN","TIUSRVA",114,0)
 . I 'TIUY S TIUY="0^ You may not detach this note from its interdisciplinary note."
"RTN","TIUSRVA",115,0)
 Q
"RTN","TIUSRVA",116,0)
CANRCV(TIUY,TIUDA) ; Can this document receive an ID Child?
"RTN","TIUSRVA",117,0)
 S TIUY=$$CANDO^TIULP(TIUDA,"ATTACH ID ENTRY")
"RTN","TIUSRVA",118,0)
 Q
"RTN","TIUSRVR2")
0^5^B31602592^B31534657
"RTN","TIUSRVR2",1,0)
TIUSRVR2 ; SLC/JER - RPC for record-wise GET ; 11/23/07
"RTN","TIUSRVR2",2,0)
 ;;1.0;TEXT INTEGRATION UTILITIES;**100,109,162,222,234**;Jun 20, 1997;Build 6
"RTN","TIUSRVR2",3,0)
 ; 4/12/01 Moved signature modules to new rtn TIUSRVR3
"RTN","TIUSRVR2",4,0)
LOADREC(TIUDA,TIUL,TIUGDATA,TIUGWHOL,ACTION) ; Load ^TMP
"RTN","TIUSRVR2",5,0)
 ;Requires TIUDA, array TIUL, TIUGDATA
"RTN","TIUSRVR2",6,0)
 ;optional TIUGWHOL = 1 if we're mid-load for browse, and we're already
"RTN","TIUSRVR2",7,0)
 ;                    loading the whole note after the original entry,
"RTN","TIUSRVR2",8,0)
 ;                    so DON'T load the whole note again.
"RTN","TIUSRVR2",9,0)
 N TIUKID,TIUDADT,TIUI,CANSEE
"RTN","TIUSRVR2",10,0)
 N TIUPARNT,TIUPNAME,TIUPDATE
"RTN","TIUSRVR2",11,0)
 N TIUGPRNT,TIUGPNM,TIUGPDT,TIUPDATA,TIUHASKD
"RTN","TIUSRVR2",12,0)
 S ACTION=$G(ACTION,"VIEW")
"RTN","TIUSRVR2",13,0)
 ; ---- If user cannot view, say so and quit: ----
"RTN","TIUSRVR2",14,0)
 ;      TIU*1*100
"RTN","TIUSRVR2",15,0)
 S CANSEE=$S(+$$ISCOMP^TIUSRVR1(TIUDA)>0:1,1:$$CANDO^TIULP(+TIUDA,ACTION))
"RTN","TIUSRVR2",16,0)
 I +CANSEE'>0 D  Q
"RTN","TIUSRVR2",17,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=$P(CANSEE,U,2)
"RTN","TIUSRVR2",18,0)
 ; ---- Load text of TIUDA: ----
"RTN","TIUSRVR2",19,0)
 S TIUI=0
"RTN","TIUSRVR2",20,0)
 F  S TIUI=$O(^TIU(8925,+TIUDA,"TEXT",TIUI)) Q:+TIUI'>0  D
"RTN","TIUSRVR2",21,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=$G(^TIU(8925,+TIUDA,"TEXT",+TIUI,0))
"RTN","TIUSRVR2",22,0)
 ; ---- if TIUDA is a COMPONENT, QUIT
"RTN","TIUSRVR2",23,0)
 Q:+$$ISCOMP^TIUSRVR1(TIUDA)
"RTN","TIUSRVR2",24,0)
 ; ---- If TIUDA **IS** an addendum, load addm signature,
"RTN","TIUSRVR2",25,0)
 ;         load original document, quit: ----
"RTN","TIUSRVR2",26,0)
 I +$$ISADDNDM^TIULC1(+TIUDA) D  Q
"RTN","TIUSRVR2",27,0)
 . N TIULINE,TIUPARNT S $P(TIULINE,"=",79)=""
"RTN","TIUSRVR2",28,0)
 . D LOADSIG^TIUSRVR3(TIUDA,.TIUL)
"RTN","TIUSRVR2",29,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=""
"RTN","TIUSRVR2",30,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=TIULINE
"RTN","TIUSRVR2",31,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=""
"RTN","TIUSRVR2",32,0)
 . S TIUPARNT=+$P(^TIU(8925,+TIUDA,0),U,6)
"RTN","TIUSRVR2",33,0)
 . S TIUPNAME=$$PNAME^TIULC1(+^TIU(8925,TIUPARNT,0))
"RTN","TIUSRVR2",34,0)
 . S TIUPDATE=+$G(^TIU(8925,TIUPARNT,13))
"RTN","TIUSRVR2",35,0)
 . S TIUPDATE=$$DATE^TIULS(TIUPDATE,"MM/DD/YY")
"RTN","TIUSRVR2",36,0)
 . S TIUPDATA=$$IDDATA^TIURECL1(TIUPARNT)
"RTN","TIUSRVR2",37,0)
 . S TIUHASKD=$P(TIUPDATA,U,2),TIUGPRNT=+$P(TIUPDATA,U,3)
"RTN","TIUSRVR2",38,0)
 . S TIUL=+$G(TIUL)+1
"RTN","TIUSRVR2",39,0)
 . I TIUHASKD D
"RTN","TIUSRVR2",40,0)
 . . S @TIUARR@(TIUL)=" --- Original Addended Interdisciplinary Entry ---"
"RTN","TIUSRVR2",41,0)
 . I TIUGPRNT D
"RTN","TIUSRVR2",42,0)
 . . S @TIUARR@(TIUL)=" --- Original Addended Interdisciplinary Entry ---"
"RTN","TIUSRVR2",43,0)
 . . S TIUGPNM=$$PNAME^TIULC1(+^TIU(8925,TIUGPRNT,0))
"RTN","TIUSRVR2",44,0)
 . . S TIUGPDT=+$G(^TIU(8925,TIUGPRNT,13))
"RTN","TIUSRVR2",45,0)
 . . S TIUGPDT=$$DATE^TIULS(TIUGPDT,"MM/DD/YY")
"RTN","TIUSRVR2",46,0)
 . I 'TIUHASKD,'TIUGPRNT S @TIUARR@(TIUL)=" --- Original Document ---"
"RTN","TIUSRVR2",47,0)
 . S TIUL=+$G(TIUL)+1,@TIUARR@(TIUL)=""
"RTN","TIUSRVR2",48,0)
 . S TIUL=+$G(TIUL)+1
"RTN","TIUSRVR2",49,0)
 . I TIUHASKD D
"RTN","TIUSRVR2",50,0)
 . . S @TIUARR@(TIUL)="                    << Addended Interdisciplinary Entry >>"
"RTN","TIUSRVR2",51,0)
 . . S TIUL=+$G(TIUL)+1
"RTN","TIUSRVR2",52,0)
 . . S @TIUARR@(TIUL)=TIUPDATE_" "_TIUPNAME_":"
"RTN","TIUSRVR2",53,0)
 . I TIUGPRNT D
"RTN","TIUSRVR2",54,0)
 . . S @TIUARR@(TIUL)="                         << Interdisciplinary Note >>"
"RTN","TIUSRVR2",55,0)
 . . S TIUL=+$G(TIUL)+1
"RTN","TIUSRVR2",56,0)
 . . S @TIUARR@(TIUL)=TIUGPDT_" "_TIUGPNM
"RTN","TIUSRVR2",57,0)
 . . S TIUL=+$G(TIUL)+1
"RTN","TIUSRVR2",58,0)
 . . S @TIUARR@(TIUL)="                    << Addended Interdisciplinary Entry >>"
"RTN","TIUSRVR2",59,0)
 . . S TIUL=+$G(TIUL)+1,@TIUARR@(TIUL)=TIUPDATE_" "_TIUPNAME_":"
"RTN","TIUSRVR2",60,0)
 . I 'TIUHASKD,'TIUGPRNT D
"RTN","TIUSRVR2",61,0)
 . . S @TIUARR@(TIUL)=TIUPDATE_" "_TIUPNAME_":"
"RTN","TIUSRVR2",62,0)
 . D LOADREC(TIUPARNT,.TIUL,TIUGDATA)
"RTN","TIUSRVR2",63,0)
 ; ---- Load components of TIUDA: ----
"RTN","TIUSRVR2",64,0)
 S TIUKID=0
"RTN","TIUSRVR2",65,0)
 F  S TIUKID=$O(^TIU(8925,"DAD",+TIUDA,TIUKID)) Q:+TIUKID'>0  D
"RTN","TIUSRVR2",66,0)
 . I +$$ISADDNDM^TIULC1(TIUKID)'>0 D LOADREC(TIUKID,.TIUL,$G(TIUGDATA))
"RTN","TIUSRVR2",67,0)
 ; ---- Load signature of TIUDA if TIUDA is not addm
"RTN","TIUSRVR2",68,0)
 ;           or comp: ----
"RTN","TIUSRVR2",69,0)
 ; *222 don't display sig info. for FORM LETTERS
"RTN","TIUSRVR2",70,0)
 I '+$$MEMBEROF^TIUPR222(+$G(^TIU(8925,+TIUDA,0)),"FORM LETTERS") D
"RTN","TIUSRVR2",71,0)
 . I '$$ISCOMP^TIUSRVR1(TIUDA) D LOADSIG^TIUSRVR3(TIUDA,.TIUL)
"RTN","TIUSRVR2",72,0)
 ; ---- Load addenda of TIUDA: ----
"RTN","TIUSRVR2",73,0)
 S TIUKID=0
"RTN","TIUSRVR2",74,0)
 F  S TIUKID=$O(^TIU(8925,"DAD",+TIUDA,TIUKID)) Q:+TIUKID'>0  D
"RTN","TIUSRVR2",75,0)
 . ; If acting on an addendum, don't show it again.
"RTN","TIUSRVR2",76,0)
 . I +TIUKID=+$G(^TMP("TIU FOCUS",$J)) Q
"RTN","TIUSRVR2",77,0)
 . I +$$ISADDNDM^TIULC1(TIUKID) D LOADADD(TIUKID,.TIUL)
"RTN","TIUSRVR2",78,0)
 N IDDAD
"RTN","TIUSRVR2",79,0)
 S IDDAD=+$P(TIUGDATA,U,3)
"RTN","TIUSRVR2",80,0)
 ; ---- If Browsed Record is an ID Note, & this cycle has
"RTN","TIUSRVR2",81,0)
 ;      just loaded the parent entry, then load ID kids
"RTN","TIUSRVR2",82,0)
 ;      and quit: **100** ----
"RTN","TIUSRVR2",83,0)
 I $P(TIUGDATA,U,2),TIUDA=+TIUGDATA D LOADKIDS(TIUDA,.TIUL,TIUGDATA) Q
"RTN","TIUSRVR2",84,0)
 ; ---- If Browsed Record is an ID Entry, & this cycle hasn't begun
"RTN","TIUSRVR2",85,0)
 ;      loading the whole note, then load the whole ID Note after
"RTN","TIUSRVR2",86,0)
 ;      the browsed entry and quit: ----
"RTN","TIUSRVR2",87,0)
 I IDDAD,'$G(TIUGWHOL) D  Q
"RTN","TIUSRVR2",88,0)
 . S TIUGWHOL=1
"RTN","TIUSRVR2",89,0)
 . N TIULINE S $P(TIULINE,"=",79)=""
"RTN","TIUSRVR2",90,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=""
"RTN","TIUSRVR2",91,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=TIULINE
"RTN","TIUSRVR2",92,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=""
"RTN","TIUSRVR2",93,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=" --- Interdisciplinary Note ---"
"RTN","TIUSRVR2",94,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=""
"RTN","TIUSRVR2",95,0)
 . D LOADID(IDDAD,.TIUL,TIUGDATA,TIUGWHOL)
"RTN","TIUSRVR2",96,0)
 ; ---- If Browsed Record is an ID Entry, & this cycle has begun
"RTN","TIUSRVR2",97,0)
 ;      loading the whole ID note, and is currently loading the first
"RTN","TIUSRVR2",98,0)
 ;      entry of the whole note, then load kids and quit: ----
"RTN","TIUSRVR2",99,0)
 I IDDAD,$G(TIUGWHOL),TIUDA=IDDAD D LOADKIDS(TIUDA,.TIUL,TIUGDATA,TIUGWHOL) K TIUGWHOL
"RTN","TIUSRVR2",100,0)
 Q
"RTN","TIUSRVR2",101,0)
 ;
"RTN","TIUSRVR2",102,0)
LOADKIDS(TIUDA,TIUL,TIUGDATA,TIUGWHOL) ; Load ID kids of TIUDA
"RTN","TIUSRVR2",103,0)
 ; Requires TIUDA, array TIUL, TIUGDATA
"RTN","TIUSRVR2",104,0)
 N TIUK,PRMSORT,KIDDA,TIUD0,TIUD21
"RTN","TIUSRVR2",105,0)
 I $G(^TMP("TIUR",$J,"IDDATA",TIUDA)) S PRMSORT=$P(^TMP("TIUR",$J,"IDDATA",TIUDA),U,4)
"RTN","TIUSRVR2",106,0)
 E  S TIUD0=$G(^TIU(8925,TIUDA,0)),TIUD21=$G(^TIU(8925,TIUDA,21)),PRMSORT=$P($$IDDATA^TIURECL1(TIUDA,TIUD0,TIUD21),U,4)
"RTN","TIUSRVR2",107,0)
 D GETIDKID^TIURECL2(TIUDA,PRMSORT) ; sets array ^TMP("TIUIDKID",$J,
"RTN","TIUSRVR2",108,0)
 S TIUK=0
"RTN","TIUSRVR2",109,0)
 F  S TIUK=$O(^TMP("TIUIDKID",$J,TIUDA,TIUK)) Q:+TIUK'>0  D
"RTN","TIUSRVR2",110,0)
 . S KIDDA=^TMP("TIUIDKID",$J,TIUDA,TIUK)
"RTN","TIUSRVR2",111,0)
 . D LOADID(KIDDA,.TIUL,TIUGDATA,$G(TIUGWHOL))
"RTN","TIUSRVR2",112,0)
 K ^TMP("TIUIDKID",$J)
"RTN","TIUSRVR2",113,0)
 Q
"RTN","TIUSRVR2",114,0)
 ;
"RTN","TIUSRVR2",115,0)
LOADID(TIUDA,TIUL,TIUGDATA,TIUWHOL) ; Load ID note for browse
"RTN","TIUSRVR2",116,0)
 N TIUREC,TIU
"RTN","TIUSRVR2",117,0)
 I '$D(^TIU(8925,+TIUDA,0)) Q
"RTN","TIUSRVR2",118,0)
 ; ---- If ID Kid has focus, don't show it again ----
"RTN","TIUSRVR2",119,0)
 ; I TIUDA=+$G(^TMP("TIU FOCUS",$J)) Q
"RTN","TIUSRVR2",120,0)
 S TIUL=TIUL+1,@TIUARR@(TIUL)=""
"RTN","TIUSRVR2",121,0)
 D GETTIU^TIULD(.TIU,+TIUDA)
"RTN","TIUSRVR2",122,0)
 D INQUIRE(TIUDA,.TIUREC)
"RTN","TIUSRVR2",123,0)
 ; ---- Load info missing from header since this is ID note entry: ----
"RTN","TIUSRVR2",124,0)
 ; ---- Load dictation, transcription data, etc.: ----
"RTN","TIUSRVR2",125,0)
 D LOADTOP^TIUSRVR1(.TIUREC,TIUDA,.TIUL,$G(TIUGDATA))
"RTN","TIUSRVR2",126,0)
 ; ---- Load the remainder of the record: ----
"RTN","TIUSRVR2",127,0)
 D LOADREC(TIUDA,.TIUL,$G(TIUGDATA),$G(TIUWHOL))
"RTN","TIUSRVR2",128,0)
 Q
"RTN","TIUSRVR2",129,0)
 ;
"RTN","TIUSRVR2",130,0)
INQUIRE(TIUDA,TIUREC,TIUCPF) ; Inquire to document TIUDA and set TIUREC
"RTN","TIUSRVR2",131,0)
 N DA,DIC,DIQ,DR
"RTN","TIUSRVR2",132,0)
 S DA=TIUDA,DIC=8925,DIQ="TIUREC("
"RTN","TIUSRVR2",133,0)
 S DR=".01;.02;.05;.09;1201;1202;1208;1209;1301;1307;1501;1502;1505;1506;89261"
"RTN","TIUSRVR2",134,0)
 ;If the document is a member of the Clinical Procedures Class, include the
"RTN","TIUSRVR2",135,0)
 ;Procedure Summary Code field and the Date/Time Performed field
"RTN","TIUSRVR2",136,0)
 I $G(TIUCPF) S DR=DR_";70201;70202"
"RTN","TIUSRVR2",137,0)
 D EN^DIQ1
"RTN","TIUSRVR2",138,0)
 Q
"RTN","TIUSRVR2",139,0)
LOADADD(TIUDADD,TIUL) ; Load addenda
"RTN","TIUSRVR2",140,0)
 N TIUDAUTH,TIUDATT,TIUJ,TIUSIG,TIUCSIG,TIUVIEW
"RTN","TIUSRVR2",141,0)
 S TIUL=TIUL+1,@TIUARR@(TIUL)=""
"RTN","TIUSRVR2",142,0)
 S TIUDADT=$$DATE^TIULS($P($G(^TIU(8925,+TIUDADD,13)),U),"MM/DD/CCYY")
"RTN","TIUSRVR2",143,0)
 S TIUL=TIUL+1,@TIUARR@(TIUL)=TIUDADT_" ADDENDUM"_"                      STATUS: "_$$STATUS^TIULF(TIUDADD) ;P162
"RTN","TIUSRVR2",144,0)
 S TIUVIEW=$$CANDO^TIULP(+TIUDADD,"VIEW")
"RTN","TIUSRVR2",145,0)
 I '+TIUVIEW D  Q
"RTN","TIUSRVR2",146,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=$P(TIUVIEW,U,2)
"RTN","TIUSRVR2",147,0)
 S TIUJ=0
"RTN","TIUSRVR2",148,0)
 F  S TIUJ=$O(^TIU(8925,+TIUDADD,"TEXT",TIUJ)) Q:+TIUJ'>0  D
"RTN","TIUSRVR2",149,0)
 . S TIUL=TIUL+1,@TIUARR@(TIUL)=$G(^TIU(8925,+TIUDADD,"TEXT",TIUJ,0))
"RTN","TIUSRVR2",150,0)
 D LOADSIG^TIUSRVR3(TIUDADD,.TIUL)
"RTN","TIUSRVR2",151,0)
 Q
"VER")
8.0^22.0
"BLD",6862,6)
^221
**END**
**END**
